### ISSUE TITLE
Compiling error on OS/2

### ISSUE THREAD

**Issue by TeLLie** [dail8859/NotepadNext#1]
Just let you know that i have ported you're NotepadNext to good old OS/2
Yes its still alive

I used Qt v5.1.3 and GCC 9.2.0

The only trouble i came across where:

 ../../NotepadNext/IFaceTable.h:143:22: error: 'string' is not a member of 'std'

Fixed with by adding to IFacceTable.h #include <string>

next error i faced where....

../../NotepadNext/LuaExtension.cpp: In member function 'bool LuaExtension::RunFile(const wchar_t*)':
../../NotepadNext/LuaExtension.cpp:774:71: error: no matching function for call to 'std::basic_ifstream<char>::basic_ifstream(const wchar_t*&, std::_Ios_Openmode)'
  774 |     std::ifstream filestream(filename, std::ios::in | std::ios::binary);
| ^
In file included from ../../NotepadNext/LuaExtension.cpp:30:
C:/usr/include/c++/9/fstream:587:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(std::basic_ifstream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]'
  587 |       basic_ifstream(basic_ifstream&& __rhs)
      |       ^~~~~~~~~~~~~~
C:/usr/include/c++/9/fstream:587:7: note:   candidate expects 1 argument, 2 provided
C:/usr/include/c++/9/fstream:579:2: note: candidate: 'template<class _Path, class _Require> std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const _Path&, std::ios_base::openmode)'
  579 |  basic_ifstream(const _Path& __s,
      |  ^~~~~~~~~~~~~~
C:/usr/include/c++/9/fstream:579:2: note:   template argument deduction/substitution failed:
C:/usr/include/c++/9/fstream:578:32: error: request for member 'make_preferred' in 'std::declval<const wchar_t*&>()', which is of non-class type 'const wchar_t*'
  578 |       template<typename _Path, typename _Require = _If_fs_path<_Path>>
      |                                ^~~~~~~~
I think this is a dirty fix ...
--- LuaExtension-os2.cpp    2020-05-24 11:19:38.000000000 +0200
+++ LuaExtension.cpp    2020-05-24 11:18:40.000000000 +0200
@@ -770,7 +770,6 @@
     return true;
 }

-#ifndef __OS2__
 bool LuaExtension::RunFile(const wchar_t *filename) {
     std::ifstream filestream(filename, std::ios::in | std::ios::binary);
     std::string buff;
@@ -790,7 +789,6 @@

     return RunString(&buff.c_str()[idx]);
 }
-#endif

 bool LuaExtension::OnExecute(const char *s) {
     static bool isFirstLine = true;

Maybe you have a better solution for this.

**Comment by TeLLie** [comment]
> Just let you know that i have ported you're NotepadNext to good old OS/2
> Yes its still alive
> 
> I used Qt v5.1.3 and GCC 9.2.0
> 
> The only trouble i came across where:
> 
> ../../NotepadNext/IFaceTable.h:143:22: error: 'string' is not a member of 'std'
> 
> Fixed with by adding to IFacceTable.h #include <string>
> 
> next error i faced where....
> 
> ../../NotepadNext/LuaExtension.cpp: In member function 'bool LuaExtension::RunFile(const wchar_t*)':
> ../../NotepadNext/LuaExtension.cpp:774:71: error: no matching function for call to 'std::basic_ifstream::basic_ifstream(const wchar_t*&, std::_Ios_Openmode)'
> 774 | std::ifstream filestream(filename, std::ios::in | std::ios::binary);
> | ^
> In file included from ../../NotepadNext/LuaExtension.cpp:30:
> C:/usr/include/c++/9/fstream:587:7: note: candidate: 'std::basic_ifstream<_CharT, _Traits>::basic_ifstream(std::basic_ifstream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits]'
> 587 | basic_ifstream(basic_ifstream&& __rhs)
> | ^~~~~~~~~~~~~~
> C:/usr/include/c++/9/fstream:587:7: note: candidate expects 1 argument, 2 provided
> C:/usr/include/c++/9/fstream:579:2: note: candidate: 'template<class _Path, class _Require> std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const _Path&, std::ios_base::openmode)'
> 579 | basic_ifstream(const _Path& __s,
> | ^~~~~~~~~~~~~~
> C:/usr/include/c++/9/fstream:579:2: note: template argument deduction/substitution failed:
> C:/usr/include/c++/9/fstream:578:32: error: request for member 'make_preferred' in 'std::declval<const wchar_t*&>()', which is of non-class type 'const wchar_t*'
> 578 | template<typename _Path, typename _Require = _If_fs_path<_Path>>
> | ^~~~~~~~
> I think this is a dirty fix ...
> --- LuaExtension-os2.cpp 2020-05-24 11:19:38.000000000 +0200
> +++ LuaExtension.cpp 2020-05-24 11:18:40.000000000 +0200
> @@ -770,7 +770,6 @@
> return true;
> }
> 
> -#ifndef **OS2**
> bool LuaExtension::RunFile(const wchar_t *filename) {
> std::ifstream filestream(filename, std::ios::in | std::ios::binary);
> std::string buff;
> @@ -790,7 +789,6 @@
> 
> ```
>  return RunString(&buff.c_str()[idx]);
> ```
> 
> }
> -#endif
> 
> bool LuaExtension::OnExecute(const char *s) {
> static bool isFirstLine = true;
> 
> Maybe you have a better solution for this.

**Comment by dail8859** [comment]
Thanks for the interest!

> Qt 5.1.3

You mean 5.13?

If there are some changes that need made to support various operating systems then I'm fine including those if they dont clutter up the main code base too much. I develop on Windows and tried building it on Ubuntu at one point and was successful. Other than that I'm sure other platforms could use some attention.

If you'd create a pull request I'd be glad to take a look at the changes and get them merged in!
