### ISSUE TITLE
Option to comment/uncomment code

### ISSUE THREAD

**Issue by Satharus** [dail8859/NotepadNext#107]
This is more of a suggestion than an issue.

Like most text editors, a comment/uncomment feature should be present. It's usually Ctrl + / in most editors but Notepad++ used these:

![image](https://user-images.githubusercontent.com/29730368/164067402-6d44d4e3-b6f5-48c9-8122-bef0c845dd39.png)

**Comment by dail8859** [comment]
Closed by #110
