### ISSUE TITLE
Tab filename poorly integrates with Breeze Dark

### ISSUE THREAD

**Issue by KrazyKirby99999** [dail8859/NotepadNext#109]
Having installed the linux flatpak version, I found that the tabs containing the filename of the open file are difficult to read.

![Screenshot_20220419_163356](https://user-images.githubusercontent.com/69373044/164106262-dc57e142-ac54-49fb-82f9-666a7d0a99c2.png)

My desktop environment is KDE Plasma 5.24.4 and I am using the built-in Breeze Dark theme.

**Comment by Satharus** [comment]
I have the same issue here. I am using the [Nordic Theme](https://store.kde.org/s/KDE%20Store/p/1327093/).

![image](https://user-images.githubusercontent.com/29730368/164114435-be260bd7-6f21-478d-b304-fde526c1e586.png)

**Comment by dail8859** [comment]
Just some additional info...the tabbing/docking functionally comes from the [Advanced Docking System](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System) (ADS), and I also apply a custom [stylesheet](https://github.com/dail8859/NotepadNext/blob/91949c7d6a62734713d44f35394031d05bbbf710/src/NotepadNext/stylesheets/npp.css) to it. So I'm not sure if this is an ADS issue, or styling issue currently.

**Comment by mutageneral** [comment]
I have the same issue here. I am on the GNOME desktop environment and using the Dark Adiwata GTK theme ported to QT for a seamless experience between GTK and QT applications.

The application when in focus:
![image](https://user-images.githubusercontent.com/62779748/164132269-e199f36e-6f28-4b82-8375-36c324d42639.png)

The application when not in focus. Notice that now the text label is now readable: 
![image](https://user-images.githubusercontent.com/62779748/164132771-11308e6c-0915-4397-ab17-cc8d59af66d5.png)

QT theme settings:
![gnome-shell-screenshot-cg1xsm](https://user-images.githubusercontent.com/62779748/164132122-3109b0c1-6089-4e5b-a04f-175c26b9839e.png)

**Comment by mutageneral** [comment]
Just downloaded the AppImage to see if it has the same issue, but it seems that the AppImage ignores my system theme and uses a built-in one. Is this the desired behaviour? Usually it is Flatpaks that have a hard time using system themes, not AppImages...
Tell me if you want me to open an issue for this specifically.
![image](https://user-images.githubusercontent.com/62779748/164133256-6dc5b6be-6ffc-467d-9ecb-f33388e7dbcd.png)

**Comment by dail8859** [comment]
> Is this the desired behaviour?

That's a good question. I'm not aware of anything specifically controlling whether the application should adhere to the system theme or not.

@zocker-160 Thoughts?

**Comment by zocker-160** [comment]
> Thoughts?

Appimages bundle their own precompiled version of Qt which comes with the default Qt theme and they ignore the system theme unless you specifically add support for it.
It is not really desirable behaviour, but it is normal.

Flatpaks on the other hand always prefer the system theme and apply that, because the version of Qt that comes with the Flatpak is built that way.

**Comment by zocker-160** [comment]
> It may be a simple as specifically setting the color of that label on the tab in the stylesheet so that it doesn't get overridden by the theme.

I think enforcing that part to be black would be a quick fix to this issue. 

Adding "proper" support for dark colors in the text field as well is probably not as easy I guess?

**Comment by dail8859** [comment]
> Adding "proper" support for dark colors in the text field as well is probably not as easy I guess?

I would assume not. Those controls are custom from the ADS package and I don't know enough about the ADS package or KDE custom themes.

Another option would be allow the application to load the stylesheet from an external file so the user could at least adjust it manually to make it look "better" but I really don't think there's an easy way to make it work automagically.

**Comment by creesch** [comment]
Not sure if I should be making a different issue or it is suitable here. On MacOS with dark mode the same thing happens 

![image](https://user-images.githubusercontent.com/2502190/164401701-aa74198d-9f8b-409d-ae23-77b8c0378e8c.png)

**Comment by dail8859** [comment]
@creesch Thanks for the info. I think the root cause is the same. I have a change I'll push later today which should fix it on both MacOS and Linux.

**Comment by dail8859** [comment]
@creesch @cschlosser 

You can try the new dmg here: https://github.com/dail8859/NotepadNext/suites/6213600272/artifacts/219672270

@zocker-160

I'm assuming if it fixes it for MacOS it will fix it for the flatpak distribution but is there an easy way to make snapshots available for testing via flatpak?

**Comment by KrazyKirby99999** [comment]
https://docs.flatpak.org/en/latest/single-file-bundles.html ?

**Comment by zocker-160** [comment]
> I'm assuming if it fixes it for MacOS it will fix it for the flatpak distribution but is there an easy way to make snapshots available for testing via flatpak?

Yes there are two options, either we create a file bundle or we push it to the beta branch on Flathub.

I would prefer the latter, since I have already created one for testing the titlebar icon. All I need is the commit ID to build from.

**Comment by dail8859** [comment]
@zocker-160 283691cf5c62eedc4d591529adb3446cab4963db

**Comment by zocker-160** [comment]
pushed to beta branch: 
https://github.com/flathub/com.github.dail8859.NotepadNext/commit/108ecb7aa283d07e847e0b22bf028406ac1bf50c

build is currently in the queue

**Comment by dail8859** [comment]
@zocker-160 Thanks! Guess that was easier than I realized :) Now I know!

**Comment by zocker-160** [comment]
for anyone that wants to test Notepad Next from the beta branch, one can join flathub-beta with this command:

`flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`
and then install using:
`flatpak install flathub-beta com.github.dail8859.NotepadNext`

**Comment by KrazyKirby99999** [comment]
The problem still occurs.

**Comment by dail8859** [comment]
@KrazyKirby99999 That shows a build date of April 20th at 4:50PM. Looks like the beta build that was just started isn't quite available yet.

**Comment by zocker-160** [comment]
there is currently a 2 hour backlog on the build server, so it will take a bit.

You will find out once flatpak shows you that an update is available.

**Comment by zocker-160** [comment]
build is available now and it looks good to me:
![Screenshot_20220422_031349](https://user-images.githubusercontent.com/36563538/164577305-8fa99e84-b988-465f-af8f-8c4416f6d5e1.png)

**Comment by dail8859** [comment]
@zocker-160 Thanks for testing!
