### ISSUE TITLE
Editor font size very small on MacOS

### ISSUE THREAD

**Issue by szabodanika** [dail8859/NotepadNext#111]
Hello, I just installed NotepadNext on my Macbook Air M1 with MacOS Monterey and everything works perfectly, but the default font size is very tiny. I can zoom in, but I wonder if some extra configuration is needed for high resolution displays? Interestingly the rest of the UI has perfect font size, only the editor is very tiny. 

<img width="772" alt="image" src="https://user-images.githubusercontent.com/25702868/164238842-393dfd5a-81d1-49bb-a19e-b3d202b9ebb8.png">

**Comment by dail8859** [comment]
The other thing to try is running:

```lua
print(editor.StyleSize[0])
```

To see what the default value is before manually changing it. I think it should default to 10.

**Comment by szabodanika** [comment]
You were right, it is 10 by default. Around 16-18 would be optimal I think.

<img width="926" alt="image" src="https://user-images.githubusercontent.com/25702868/164243668-d50e5036-7bea-4a85-8111-43f3ecb44c26.png">

**Comment by dail8859** [comment]
Thanks for checking!

Note to self...might be able to use [QApplication::font()](https://doc.qt.io/qt-5/qapplication.html#font) to get the system default font and see if that has an accurate font size to use by default for the editor.

**Comment by cschlosser** [comment]
This is something I didn't consider a bug of the application but rather an unfortunate default setting for my usecase ;)
The only bug for me I found is with dark mode on macOS is already in https://github.com/dail8859/NotepadNext/issues/109#issuecomment-1104816726

Having the font size configurable through settings instead of the lua console would certainly help though :)

**Comment by dail8859** [comment]
> Having the font size configurable through settings instead of the lua console would certainly help though :)

Yep I totally agree. The Lua console is meant for debugging/testing and not intended for normal use.

If I can use the system font that would at least be a nice default value to start with and allow it to be configured after that.

**Comment by dail8859** [comment]
This .dmg should try to adjust the default font based on the UI font. Give it a try and let me know.

https://github.com/dail8859/NotepadNext/suites/6214197185/artifacts/219721396

**Comment by szabodanika** [comment]
![image](https://user-images.githubusercontent.com/25702868/164673536-065277f4-a18d-4e39-a71f-03b074fa88c1.png)

It defaulted to 15 with this version. Looks very nice, thanks!!

**Comment by dail8859** [comment]
@szabodanika Thanks for testing it out! I'll check Linux to see if the logic provides a reasonable default before closing the issue.

**Comment by dail8859** [comment]
Font size looks fine on Linux. Thanks for reporting the issue!
