### ISSUE TITLE
Suggestion autoupdate for portable windows version

### ISSUE THREAD

**Issue by spupuz** [dail8859/NotepadNext#115]
Could you add an update menu in order to autoupdate the windows portable versione?

thanks in advance.

**Comment by dail8859** [comment]
I think the short answer is it's not (easily) possible.

The application could check if there's an update, download the zip...and then...attempt to extract it over itself? 

I'm open to suggestions if there's some creative and simple solution I may not be thinking of right now. I don't want to try to do anything like windows services, additional exes, etc just to check for portable updates.

**Comment by spupuz** [comment]
i'm not an expert but other portable apps can do it, like for example mremoteng if i'm not wrong

**Comment by dail8859** [comment]
Not saying its impossible, just more effort than its worth currently. Closing for now but maybe at somepoint in the future this might make more sense to invest some time into.
