### ISSUE TITLE
Info on additional language script ?

### ISSUE THREAD

**Issue by docop** [dail8859/NotepadNext#119]
Hi  Very great app so far and nice to see a recreation of npp direct for linux. Just to know, can it be possible to have the option for adding extra language and coding theme ? Like to import .xml  as of :   [https://github.com/cxlpun/Tradingview-Pinescript-UDL](https://github.com/cxlpun/Tradingview-Pinescript-UDL)

 Also the appimage is quite the perfect fit as it is : truly portable. Not having to download like 300megs of useless extra data of flatpack and being all time connected to the net. your v0.5 do work good on ubu20.04 and on arch linux.
 Thanks again

**Comment by dail8859** [comment]
> can it be possible to have the option for adding extra language and coding theme ?

This kind of functionality is probably not going to happen very soon, but ideally yes there will be was to configure the theme, add extra languages, or something similar to user defined languages. Again probably won't happen soon unless someone is really interested in implementing it.

> Also the appimage is quite the perfect fit as it is : truly portable.

Glad to hear!

**Comment by docop** [comment]
Thanks for precision. but hope the addition of custom language can make it.. as having this and dark theme all in appimage is quite a winner. hehe

**Comment by wangdemon** [comment]
I'm looking forward to the author to realize the highlighting of the custom language. That would be a great feature.Thank you very much for the selfless dedication of the author.

**Comment by faultaddr** [comment]
> I'm looking forward to the author to realize the highlighting of the custom language. That would be a great feature.Thank you very much for the selfless dedication of the author.

I think u can make it by modifying the code by yourself. such an easy thing, no need to bother dail8859.
-  add xxx.cxx
-  add xxx.lua
-  modify some code and add the file link

I have already made it. best wishes.

**Comment by wangdemon** [comment]
> 

Yeah. You are quite right, but I don't know how to add code yet. Can I have a look at your code

**Comment by wangdemon** [comment]
> > I'm looking forward to the author to realize the highlighting of the custom language. That would be a great feature.Thank you very much for the selfless dedication of the author.
> 
> I think u can make it by modifying the code by yourself. such an easy thing, no need to bother dail8859.
> 
>     * add xxx.cxx
> 
>     * add xxx.lua
> 
>     * modify some code and add the file link
> 
> 
> I have already made it. best wishes.

Yeah. You are quite right, but I don't know how to add code yet. Can I have a look at your code
