### ISSUE TITLE
Build fails: too many arguments to function call, expected 0, have 1

### ISSUE THREAD

**Issue by yurivict** [dail8859/NotepadNext#122]
```
--- build/obj/FloatingWidgetTitleBar.o ---
../src/ads/src/linux/FloatingWidgetTitleBar.cpp:197:34: error: too many arguments to function call, expected 0, have 1
                        d->FloatingWidget->showNormal(true);
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~
/usr/local/include/qt5/QtWidgets/qwidget.h:486:10: note: 'showNormal' declared here
    void showNormal();
         ^
1 error generated.
```

Version: 0.5.1
clang-13
Qt-5.15.2
FreeBSD 13

**Comment by dail8859** [comment]
Hi @yurivict

The code is building fine on Ubuntu so I'd assume it is something specific to clang or FreeBSD. This particular part of the code is from the [Advanced Docking System](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System) project so any changes to fix compilation errors in that file will need addressed in that project.

**Comment by yurivict** [comment]
What Qt version do you use?

The Qt [documentation](https://doc.qt.io/qt-5/qwidget.html#showNormal) says that this functions has no arguments.

**Comment by dail8859** [comment]
> What Qt version do you use?

It has been building with Qt 5.15.2 and Qt 6.2.4

> The Qt [documentation](https://doc.qt.io/qt-5/qwidget.html#showNormal) says that this functions has no arguments.

Yeah I noticed that as well but looking at the most recent [Linux builds](https://github.com/dail8859/NotepadNext/actions/runs/2251009485) I don't see even any warnings showing up which is odd.

**Comment by elcuco** [comment]
> The Qt [documentation](https://doc.qt.io/qt-5/qwidget.html#showNormal) says that this functions has no arguments.
That specific function is not of QWidget, but from CFloatingDockContainer (at least I think).

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/23f80334f67eb445ae551f52c79f32a949bde099/src/FloatingDockContainer.cpp#L1193

The code works differently on non-linux - see this:
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/23f80334f67eb445ae551f52c79f32a949bde099/src/FloatingDockContainer.h#L36

The bug is upstream it seems - can you report it on ADS?

**Comment by dail8859** [comment]
@elcuco Good catch!

@yurivict The best option as suggested by elcuco is to open an issues in the [Advanced Docking System](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues) project

**Comment by dail8859** [comment]
Closing for now since this appears to be an upstream issue related to FreeBSD.
