### ISSUE TITLE
Find/Replace dialog has incorrect color theme in macos dark mode

### ISSUE THREAD

**Issue by yougg** [dail8859/NotepadNext#129]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/1641020/166874307-0eb21514-31ca-4edc-ada6-6bd47fba4006.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/1641020/166874342-15fe49ba-7b43-4c56-8bd8-73e9735daa49.png">

it should choose color theme like `Go to Line` dialog
<img width="200" alt="image" src="https://user-images.githubusercontent.com/1641020/166874397-53246463-3dff-4c88-be41-30a9e8ee7a12.png">

**Comment by blimeybloke** [comment]
Following as I have same issue :) But AWESOME work to everyone.

**Comment by blimeybloke** [comment]
Here is a temp fix... 
I disabled dark mode for the app..

I did <osascript -e 'id of app "NotepadNext"'>
which gave com.yourcompany.NotepadNext as the ID
I then ran:

<defaults write com.yourcompany.NotepadNext NSRequiresAquaSystemAppearance -bool Yes>

**Comment by dail8859** [comment]
@yougg @blimeybloke

Can you try this test build?

https://github.com/dail8859/NotepadNext/suites/6410300460/artifacts/233620010

**Comment by blimeybloke** [comment]
It seems to work.  I did remove the old version first just incase my "temp fix" would affect an upgrade.  So clean removal, then new install and it seems to be spot on.  
Great work bro!
