### ISSUE TITLE
What is the correct spelling of this app?

### ISSUE THREAD

**Issue by RDKRACZ** [dail8859/NotepadNext#130]
Is it NotepadNext or Notepad Next?
The repo name and files like src/NotepadNext.pro, and src/NotepadNext are written together but the app title bar and the about window have the spaced variant.

**Comment by dail8859** [comment]
`Notepad Next` is the correct spelling. Obviously some things don't allow spaces, others don't always play nice or its just easier to have a single string of non-whitespace characters.
