### ISSUE TITLE
Build suggestion/External depedencies

### ISSUE THREAD

**Issue by SebTM** [dail8859/NotepadNext#135]
I was suggested [here](https://github.com/NixOS/nixpkgs/pull/169039#discussion_r868310607) that maybe changing https://github.com/dail8859/NotepadNext/blob/master/src/Config.pri#L24 to the required C++ standard would makes it needless to specify it explicit/manually on build. Maybe a good catch for you?

NixOS is trying to reduce build-time and complexity by packaging the dependencies external. In this comment there are some resources/explanations beyond my understanding how you could make this possible for us: https://github.com/NixOS/nixpkgs/pull/169039#discussion_r868306706 (therefore I primarily opened the issue to keep track of this and move forward with getting the package merged :))

**Comment by dail8859** [comment]
> to the required C++ standard

Uh...I'm not sure I follow. Are you saying this line needs removed?

> NixOS is trying to reduce build-time and complexity by packaging the dependencies external.

The only external dependency for the application is Qt. Everything else is statically linked and I have no plan/desire to change that.

--- 

So a bit of a side question...why does this need packaged for NixOS when there is already a flatpak available for NixOS?

**Comment by SebTM** [comment]
> > to the required C++ standard
> 
> Uh...I'm not sure I follow. Are you saying this line needs removed?

I think not removed but changed - but that's just a guess from what I found here: https://stackoverflow.com/a/47944883


> > NixOS is trying to reduce build-time and complexity by packaging the dependencies external.
> 
> The only external dependency for the application is Qt. Everything else is statically linked and I have no plan/desire to change that.
> 
> So a bit of a side question...why does this need packaged for NixOS when there is already a flatpak available for NixOS?

From my understanding NixOS main-point is the reproducibility of config/packages. Therefore everything is packaged and build from source (if possible) to ensure the reproducibility. (https://nixos.wiki/wiki/NixOS)

I've also asked in https://github.com/NixOS/nixpkgs/pull/169039 for help to explain it better and also our request for external dependencies like lua (we already have packaged/built).

**Comment by dail8859** [comment]
> but that's just a guess from what I found here: https://stackoverflow.com/a/47944883

So changing it to `CONFIG += c++1z` should solve your issue then? I can create a PR and see how Windows/Linux/MacOS likes this. Though I'm familiar with C++, this kind of stuff is a bit beyond my understanding. 😄 

Another thing to keep in mind is you can pass parameters (including additional CONFIG) into qmake via command line (https://doc.qt.io/qt-5/qmake-running.html#makefile-mode-options) so that might be another option to tweak it to work better on NixOS.

Just something to keep in mind, at some point this project will be moving to Qt6 and possibly cmake (rather than qmake).

So in general I'm all for fixing minor issues with other OSs, compilers, etc. However large structural changes to the application that don't directly affect Windows/Ubuntu/MacOS and its build system are unlikely to happen.

**Comment by dail8859** [comment]
Thanks for working with me on this...I think we are all using this as a good learning experience 😄

**Comment by jtojnar** [comment]
> So changing it to `CONFIG += c++1z` should solve your issue then?

Assuming this line is responsible for setting the C++ standard level like CMake’s [`CXX_STANDARD`](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html) property, it would be generally expected to be set by the project to the version of C++ it targets.

But `1z` is a deprecated synonym of 17 according to both [GCC](https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html) (which Nixpkgs uses on Linux) and [CLang](https://clang.llvm.org/cxx_status.html) so I do not see how could it change anything.

**Comment by dail8859** [comment]
@jtojnar 

>  it would be generally expected to be set by the project to the version of C++ it targets.

I know for a fact there are `c++17` features that this code requires...but honestly that's about all I know.

> But 1z is a deprecated synonym of 17 according to both [GCC](https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html) (which Nixpkgs uses on Linux) and [CLang](https://clang.llvm.org/cxx_status.html) so I do not see how could it change anything.

That was my general understanding as well but wasn't certain. Maybe if gcc is old enough it doesn't recognize `c++17` but is fine with the `c++1z`...that's purely a guess though.

**Comment by jtojnar** [comment]
Nixpkgs [uses GCC 11 on x86_64-linux](https://github.com/NixOS/nixpkgs/commit/52f8cf58a4504e5e219faebffa51033e400e3aec) by default so that should be recent enough.

**Comment by dail8859** [comment]
I guess at this point I'm completely lost and not sure the best route. Everything seems to indicate c++1z (and gnu++1z) are deprecated as @jtojnar.

@SebTM Thoughts?

**Comment by SebTM** [comment]
I've no clue as I'm not really familiar with C++, Notepad++ just reminds me of my youth :D

Maybe @elcuco from https://github.com/dail8859/NotepadNext/issues/99#issuecomment-1100762910 can help out - he suggested the solution and explained it there?

**Comment by elcuco** [comment]
I dont fully understand the question... but, if you are talking about shared objects and dynamic linking... all 3rd parties of NotepadNext are basically unusable as shared code. Maybe... LUA.

All others contains compile time switches, which renders the library unsuitable to be shared, or too simple (just a few files, or just used *only* by NotepadNext). 

Does NixOS have libraries for Lua and chardetect? I assume that I can hack the cmake code to look for system packages, before downloading/compiling a local copy. In QMake... this is *way* harder.

**Comment by SebTM** [comment]
https://github.com/dail8859/NotepadNext/issues/135#issuecomment-1122653942
What I refereed to was the question was more about this and the c++1z and c++17 :)

But anyway what you said about third party / system dependencies with cmake sound great and exactly what was requested at nixpkgs PR 👍🏻
