### ISSUE TITLE
Packaging as a deb file

### ISSUE THREAD

**Issue by dtantono** [dail8859/NotepadNext#139]
Hi
Is there any possibility for deb file for this app?

**Comment by dail8859** [comment]
I literally have no idea what level of effort is required to create and distribute deb files. There's already an AppImage and Flatpak available for Linux so I currently don't see the value of managing another distribution mechanism.

**Comment by zocker-160** [comment]
@dail8859 small suggestion: maybe you could link to the Flathub page in the readme so ppl can find it more easily?
