### ISSUE TITLE
The find dialog not appearing from the background

### ISSUE THREAD

**Issue by RDKRACZ** [dail8859/NotepadNext#140]
When the find dialog is opened and then minimalized the only way to bring it back is to use the taskbar icon - using the ctrl+F shortcut or selecting it from the app menu doesn't do anything.
This may be an intentional functionality as the text box in the dialog is being replaced with the currently selected text but I don't see any setting in the preferences tab to turn this off so it looks like a bug to me.

I also see #132 on my machine - flatpak on Fedora SIlverblue 35 with GNOME.

**Comment by dail8859** [comment]
> find dialog is opened and then minimalized

Minimizing the actual Find dialog or the application itself? The dialog itself should not have a taskbar icon. On Windows the find dialog can't be minimized...

![image](https://user-images.githubusercontent.com/3694843/168447812-5670302b-6dcd-45fa-87ed-8f097ca5f116.png)

Also if I minimize the entire application and then refocus it, then the find dialog shows up again.

**Comment by RDKRACZ** [comment]
On Linux with gnome desktop, the dialog can be minimalized and has a taskbar icon (using dash to panel extension. It is also visible in the overview).
![image](https://user-images.githubusercontent.com/43277609/168461157-d27cf1f4-bd06-4359-9321-7d2194525109.png)

**Comment by dail8859** [comment]
Code wise this is configured so that it shouldn't have a minimize or maximize button. I'll need to spin up a Linux VM and take a look.

**Comment by dail8859** [comment]
@RDKRACZ Ubuntu doesn't show any additional buttons.

![image](https://user-images.githubusercontent.com/3694843/168675066-4fe866cc-924f-463d-8f53-e56f7c22941e.png)

The dialog is a basic Qt Dialog and anytime the shortcut is triggered it does everything it can to ensure the dialog is visible:

```cpp
frd->show();
frd->raise();
frd->activateWindow();
```

My best guess is the dash to panel extension is modifying the dialog and adding the buttons, so I won't be looking into this myself. If someone else can replicate this behavior and find a simple, non-invasive fix I'd be willing to consider it.

So unfortunately if you force non-standard features, you'll get non-standard behavior.
