### ISSUE TITLE
Add support for user defined languages

### ISSUE THREAD

**Issue by szalayg** [dail8859/NotepadNext#142]
I just started using the app on Linux, and I love it, but I could not figure out, how to add a user defined Language file (in the particular case Groovy from https://gist.github.com/Thermionix/9ff4a362f2bdc026c0ec) . Would it be possible to add support for these resources, or for Groovy itself?

**Comment by dail8859** [comment]
Glad you are finding it useful.

Any type of user defined languages are not supported. There's no immediate plan to add this functionality but as the application matures it is definitely something worth supporting in some fashion.

I looked around and there's no native support by Lexilla for Groovy.

**Comment by dail8859** [comment]
Closing this issue for now. Supporting some form of user defined languages is desirable, but I doubt this functionality will show up for quite some time. There's just much core functionality that takes priority.

**Comment by docop** [comment]
Indeed a simple section to import custom language file can be quite handy.
