### ISSUE TITLE
Application translation files are not included in AppImage

### ISSUE THREAD

**Issue by dail8859** [dail8859/NotepadNext#155]
As discovered in #152 it looks like the AppImage has never included the Notepad Next translation files. Seems to be fine for Windows.

cc @eson57

**Comment by dail8859** [comment]
For reference, QOwnNotes installs the translation files with the INSTALLS target:

https://github.com/pbek/QOwnNotes/blob/9b2df420d4c7060651f730172b2a0efca8eeb833/src/QOwnNotes.pro#L378-L408

**Comment by dail8859** [comment]
@eson57 

I think I finally have a fix for this. You can download a zip of the AppImage  to try [here](https://github.com/dail8859/NotepadNext/suites/7213471859/artifacts/288809663).

**Comment by eson57** [comment]
Sorry, I cant make translations work.

>$ ./NotepadNext-x86_64.AppImage
> qt5ct: using qt5ct plugin
> 
> (AppImageLauncher:17567): GLib-CRITICAL **: 08:03:45.767: g_file_test: assertion 'filename != NULL' failed
> [     0.161] I: =============================
> [     0.161] I: NotepadNext v0.5.2
> [     0.161] I: Build Date/Time: Jul  4 2022 21:47:45
> [     0.161] I: Qt: 5.15.2
> [     0.161] I: OS: Linux Mint 20.3
> [     0.161] I: Locale: sv_SE
> [     0.161] I: CPU: x86_64
> [     0.161] I: File Path: /tmp/.mount_NotepalRgLRM/usr/bin/NotepadNext
> [     0.161] I: Arguments: /tmp/.mount_NotepalRgLRM/AppRun.wrapped
> [     0.161] I: =============================
> [     0.161] I: bool NotepadNextApplication::init()
> [     0.161] I: void NotepadNextApplication::processArguments(const QStringList&)
> [     0.162] I: void NotepadNextApplication::loadTranslation(QLocale)
> [     0.162] I: sv_SE translation not found for Notepad Next
> [     0.162] I: sv_SE translation not found for Qt components
> [     0.162] I: LuaState::LuaState()
> [     0.180] I: MainWindow::MainWindow(NotepadNextApplication*)
> [     0.216] I: setupUi Completed
> [     0.256] I: void MainWindow::setupLanguageMenu()
> [     0.262] I: void MainWindow::restoreSettings()
> [     0.262] I: void NotepadNextApplication::openFilesFromCommandLine()
> [     0.262] I: void MainWindow::newFile()
> [     0.262] I: void EditorManager::setupEditor(ScintillaNext*)
> [     0.264] I: void MainWindow::addEditor(ScintillaNext*)
> [     0.264] I: void MainWindow::detectLanguage(ScintillaNext*)
> [     0.264] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
> [     0.264] I: Language Name: Text
> [     0.264] I: void DockedEditor::addEditor(ScintillaNext*)
> [     0.313] I: void MainWindow::activateEditor(ScintillaNext*)
> [     0.313] I: bool MainWindow::checkFileForModification(ScintillaNext*)
> [     0.313] I: void MainWindow::updateGui(ScintillaNext*)
> [     0.313] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
> [     0.313] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
> [     0.313] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
> [     0.313] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)

**Comment by dail8859** [comment]
@eson57 Ok, thanks for trying it out. I'll see if I can find the root cause.

**Comment by dail8859** [comment]
Personally I am not overly familiar with application development on Linux. I was just going off some other Qt projects in an attempt to fix this in #161, but it is quite possible you are correct that deploying the AppImage would need those files copied explicitly.
