### ISSUE TITLE
Docking system not working on Linux

### ISSUE THREAD

**Issue by dail8859** [dail8859/NotepadNext#156]
_Originally posted by @eson57 in https://github.com/dail8859/NotepadNext/issues/152#issuecomment-1163179673_

**Comment by dail8859** [comment]
Ubuntu 21.10 works fine. I'll try Linux Mint when I get a chance.

**Comment by dail8859** [comment]
Everything appears to be working for me on Linux Mint 20.3

![Animation](https://user-images.githubusercontent.com/3694843/175183962-47f179c5-8739-4c48-90e3-d081bdab47dc.gif)

**Comment by eson57** [comment]
Of course, again stupid me, didn't understand where to drop it. Sorry to have bothered you with my stupidity.

**Comment by dail8859** [comment]
No problem. Glad it's working for you!
