### ISSUE TITLE
Open with NotepadNext not working

### ISSUE THREAD

**Issue by drzazi** [dail8859/NotepadNext#158]
Notepadnext is an excellent app and it is super fast and lightweight.
I installed it on my Windows PC and a Macbook Pro (intel 2020, MacOS 12.3.1), but find it can't open any existing txt file on my MBP.
I also tried "open -a notepadnext 1.txt", but it just launched and opened an empty file "New 1", I think this is a bug. Could you help me fix it since opening existing files is a super common scenario. Thank you.

**Comment by dail8859** [comment]
I have never used Mac so I won't be able to offer too much help myself.

> but find it can't open any existing txt file on my MBP

You mean through the `File > Open...` menu?

> I also tried "open -a notepadnext 1.txt"

Might be something with the way Notepad Next is handling command line arguments but I'm just guessing at this point.

I know for Linux (not sure about Mac) but when you run the application it will log a bunch of information to the terminal. If it does that for Mac can you post that information?

**Comment by drzazi** [comment]
Hi, thank you for your reply.

Notepadnext works perfectly through the "File > Open..." menu and dragging files to the app's window.

It opened a "New 1" file when I double-clicked on any existing files, and I have set Notepadnext as the default file editor. "open -a notepadnext 1.txt" is the command I tried to open "1.txt" with notepadnext in the macOS terminal.
![CleanShot 2022-07-01 at 14 33 39](https://user-images.githubusercontent.com/101451206/176838004-17ac60cc-25fd-42e9-a9f4-f19947c75c37.gif)

**Comment by dail8859** [comment]
Thanks for the screen capture!

> I guess the app may not get the file path through command line arguments.

Yeah that's my guess as well. I'll see if I can find some specific documentation about this, but if I can't find anything then this might have to wait till someone can debug this on a Mac

**Comment by Doujang** [comment]
I encountered the same situation.The same is true in notepadqq(https://github.com/notepadqq/notepadqq). The experience was so bad that I was trying to find a substitute.
![iShot_2022-07-09_14 13 02](https://user-images.githubusercontent.com/20734553/178094190-c2dd1e0a-3cec-4978-94d5-82ec2f4c4ff8.gif)

**Comment by dail8859** [comment]
When starting the app from the command line it prints a bunch of debug info which would probably be enough to determine a fix, but running it from the "open with” menu doesn't give the normal standard output.

I'll be busy for a week or so but I might look into other ways of capturing the debug output such as a file or show it in the application itself.

**Comment by dail8859** [comment]
If you extract [this unreleased](https://github.com/dail8859/NotepadNext/suites/7492020955/artifacts/307628902) version there is a debug log under the Help menu. If you copy/paste that information on this issue, that might help see what command line arguments that are getting passed to Notepad Next during startup.

**Comment by drzazi** [comment]
Hi, here is the log.

[     0.154] I: =============================
[     0.154] I: NotepadNext v0.5.3
[     0.154] I: Build Date/Time: Jul 23 2022 22:38:19
[     0.154] I: Qt: 5.15.2
[     0.154] I: OS: macOS 12.4
[     0.154] I: Locale: en_US
[     0.154] I: CPU: x86_64
[     0.154] I: File Path: /Applications/NotepadNext.app/Contents/MacOS/NotepadNext
[     0.154] I: Arguments: /Applications/NotepadNext.app/Contents/MacOS/NotepadNext
[     0.154] I: =============================
[     0.154] I: bool NotepadNextApplication::init()
[     0.176] I: void NotepadNextApplication::loadTranslation(QLocale)
[     0.176] I: en_US translation not found for Notepad Next
[     0.177] I: en_US translation not found for Qt components
[     0.177] I: LuaState::LuaState()
[     0.184] I: MainWindow::MainWindow(NotepadNextApplication *)
[     0.250] I: setupUi Completed
[     0.290] I: void MainWindow::setupLanguageMenu()
[     0.317] I: void MainWindow::restoreSettings()
[     0.317] I: void NotepadNextApplication::openFiles(const QStringList &)
[     0.317] I: void MainWindow::newFile()
[     0.317] I: void EditorManager::setupEditor(ScintillaNext *)
[     0.318] I: void MainWindow::addEditor(ScintillaNext *)
[     0.318] I: void MainWindow::detectLanguage(ScintillaNext *)
[     0.318] I: void MainWindow::setLanguage(ScintillaNext *, const QString &)
[     0.318] I: Language Name: Text
[     0.318] I: void DockedEditor::addEditor(ScintillaNext *)
[     0.327] I: void MainWindow::activateEditor(ScintillaNext *)
[     0.327] I: bool MainWindow::checkFileForModification(ScintillaNext *)
[     0.327] I: void MainWindow::updateGui(ScintillaNext *)
[     0.327] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext *)
[     0.328] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext *)
[     0.328] I: void MainWindow::updateEOLBasedUi(ScintillaNext *)
[     0.328] I: void MainWindow::updateLanguageBasedUi(ScintillaNext *)
[     0.437] I: void MainWindow::focusIn()
[     0.437] I: bool MainWindow::checkFileForModification(ScintillaNext *)

**Comment by dail8859** [comment]
@drzazi 

Just to make sure that's the debug log when you use the Open With command?

**Comment by dail8859** [comment]
Did some searching and thinking it has something to do with needing a custom plist file for the application. I don't have a Mac myself so can't test exactly what would be needed.

**Comment by dail8859** [comment]
Finally think I found the issue. MacOS has a completely separate event for opening files, it also needs a custom plist:

https://doc.qt.io/qt-5/qfileopenevent.html

The changes look fairly straight forward but I have no way to test them or know exactly what is needed in the plist file.

**Comment by drzazi** [comment]
Thanks for your effort. I can test the app on my Mac if you could provide a complied version, since I'm not familiar with qt etc. It is better if you could tell me what cases need to be tested.

**Comment by dail8859** [comment]
I'll give it a shot at some point soon and let you know when there's something ready to test.

**Comment by dail8859** [comment]
@drzazi 

When you get a chance try [this](https://github.com/dail8859/NotepadNext/suites/7534692338/artifacts/310547243) new test release.

Not 100% sure if this will work but it may. I want to keep the changes as small as possible and not add things if they aren't needed.

**Comment by drzazi** [comment]
Hi,
I tested on my Mac, and I think the bug has beed fixed.
I tested by double clicking a file (after set Notepadnext as the default open app), using "open with..." menu and the open menu in the app.
The files are plain txt, yaml, html.
Thanks for you effort. It is now a perfect app for me.

**Comment by dail8859** [comment]
Awesome! Thanks for testing this out.
