### ISSUE TITLE
Search results expect that double-clicking can skip the content line.

### ISSUE THREAD

**Issue by ZHANGYANG-91** [dail8859/NotepadNext#159]
Hello, author, I used the search function when using windows and mac, and found that the search function is in the position where I can double-click the search result in (find all in current multiple value) to jump to the current problem. It would be great if I had this function.

**Comment by dail8859** [comment]
Agreed. The search results window is definitely a work in progress and there is still missing features (and missing features in the entire application itself). So this is definitely planned at some point.

**Comment by dail8859** [comment]
Closed by 748acdaf483cbb6d54632fecd221f1872c893e47. Not perfect but good enough for now.

**Comment by ZHANGYANG-91** [comment]
Just updated, it's really great, thank you, author
