### ISSUE TITLE
Any plan for support plugin?

### ISSUE THREAD

**Issue by kgfly** [dail8859/NotepadNext#168]
NPP supports many useful plugins.
Does NPN have any plan for support plugin?

**Comment by dail8859** [comment]
Currently there's no plans, but at some point in the future it is possible if there's enough interest. There's still alot of flux and work in the core application itself which would make it very difficult to support a stable plugin API currently..

**Comment by kgfly** [comment]
This is very cool software, since it's cross platform. Thank you.

But after trial, I will continue stick to NPP due to the lack plugin support of NPN. such hex editor, json view.. eg

![image](https://user-images.githubusercontent.com/12282281/178095324-0f18bfd7-6cec-450b-a9f0-60f94b042e05.png)
