### ISSUE TITLE
On Windows, perf (CPU/memory) seems much slower than NPP.

### ISSUE THREAD

**Issue by kgfly** [dail8859/NotepadNext#169]
Test case:
Open a big exe, such as Skype-8.85.0.409.exe, 86MB

Observed:
NPP: within 1 second. Memory consumption: 186MB
NPN: 3-4 seconds. Mem: 348MB

**Comment by dail8859** [comment]
I did some quick testing and looks to be related to codec stuff when loading the file from disk.

**Comment by dail8859** [comment]
I tested this with a ~48MB exe file. Got load time down from ~3 seconds down to 75 milliseconds. And reduced memory to roughly the same as Notepad++ had when loading the file.

![image](https://user-images.githubusercontent.com/3694843/179371463-3feeda3b-687a-40b8-afa9-2c22a7e18057.png)
