### ISSUE TITLE
how to add auto increment column

### ISSUE THREAD

**Issue by cooltnt** [dail8859/NotepadNext#174]
Column mode ,  how to add column , number increase
1 a
2 a
3 a
4 a

**Comment by dail8859** [comment]
Currently it is not possible but would be desirable to have this functionality in the future.

**Comment by PNBRQK** [comment]
noticed there're a Lua engine embedded in the app, couldn't this be done via Lua scripting?

**Comment by trdm** [comment]
> Currently it is not possible but would be desirable to have this functionality in the future.

I suggest that you give access to the editor with the promotion of the scripts of qtscript, then such manipulations can be carried out programmatically.
This is implemented in the plugin to notePad ++ [https://github.com/sieukrem/jn-npp-plugin](https://github.com/sieukrem/jn-npp-plugin).
I really look forward to this functionality, because I have a lot of finished scripts, and you like your editor :)

**Comment by dail8859** [comment]
Lua is already embedded in the application. Not saying this is a long-term solution but it at least gives a bit of programmatic control over the application. Any other possible scripting capabilities probably won't happen any time soon unless someone takes an interest in implementing it.

**Comment by trdm** [comment]
> Lua is already embedded in the application. Not saying this is a long-term solution but it at least gives a bit of programmatic control over the application. Any other possible scripting capabilities probably won't happen any time soon unless someone takes an interest in implementing it.

Something I don't want to rewrite 0.5 MB of scripts from javascript to Lua :(
https://github.com/trdm/jn-npp-scripts/tree/master/includes

**Comment by dail8859** [comment]
Even if it did support JS this application is just way too different than Notepad++ to make the scripts compatible. The underlying framework is totally different.

**Comment by trdm** [comment]
> Even if it did support JS this application is just way too different than Notepad++ to make the scripts compatible. The underlying framework is totally different.

Plugin [jN](https://github.com/sieukrem/jn-npp-plugin) provides the work of scripts through the next [API](https://github.com/trdm/jn-npp-scripts/tree/master/Doc/API)

I can try it on the fork. Or through the plugin.

**Comment by trdm** [comment]
I found the implementation of such a request to the editor+QtScript in the editor of Kate. Here is the implementation:

https://github.com/ssj-gz/emscripten-kate/tree/emscripten-kde/part/script
К сожалению у меня Windows и я не смог собрать и потестить.
Обращаю внимание на папку https://github.com/ssj-gz/emscripten-kate/tree/emscripten-kde/part/script/data
там есть готовые скрипты, которые могут очень помочь.

**Comment by cooltnt** [comment]
0.6 ver 
![image](https://user-images.githubusercontent.com/41370387/217718551-b5e0b91e-ed7e-404e-8919-3196c46bf5c6.png)
