### ISSUE TITLE
It is recommended to add plugin support

### ISSUE THREAD

**Issue by CHN-MuXin** [dail8859/NotepadNext#183]
I feel that a plugin interface should be provided as soon as possible so that more people can develop plugins for it, which will make this project better.

**Comment by dail8859** [comment]
The internals of the application are just changing way too much to begin to offer a stable API for plugins. I'd hate to either lock myself into an implementation or break plugins with every release.

There's alot more core functionality to focus on myself. So most likely plugin support won't be showing up any time soon unless someone feels really up to the task of building a basic plugin interface knowing that it will change alot.
