### ISSUE TITLE
can support vim mode input?

### ISSUE THREAD

**Issue by zhongzhichun** [dail8859/NotepadNext#191]

**Comment by PNBRQK** [comment]
Functionality of this kind should better be provided by a plugin.

**Comment by dail8859** [comment]
There's still alot of core functionality that needs finished. Some of which would make implementing things like vim mode easier (e.g. shortcut mapping, and just better shortcut handling in general). If someone was interested in contributing/maintaining a clean implementation of it I'd be willing to consider it. But for now this is not something I foresee being implemented for quite some time.
