### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by Nim** [dail8859/NotepadNext#198]
MainWindow.cpp line 1507
https://github.com/dail8859/NotepadNext/blob/master/src/NotepadNext/dialogs/MainWindow.cpp#L1507

availale ->available

and in translations too

**Comment by dail8859** [comment]
Good catch! I'll update that and run an `lupdate` (for the translations) next time I have access to my development machine.

**Comment by Nim** [comment]
don't forget on translations too

**Comment by dail8859** [comment]
Translation files were updated in b89eea7fa8a98e7b9547c4bb6930b9887f630a4e
