### ISSUE TITLE
incompatible w/ Chinese

### ISSUE THREAD

**Issue by intelyoungway** [dail8859/NotepadNext#200]
in current release: all Chinese words were replaced w/ ? question mark.

**Comment by dail8859** [comment]
Could you attach a small example text file here so I can try it out? Might be related to the encoding or possibly the font.

What OS are you using?

**Comment by dail8859** [comment]
I grabbed some random Chinese characters and everything looks fine for me on Win11.

![image](https://user-images.githubusercontent.com/3694843/192048970-9e9efc11-062d-41ba-bd06-df722582a4cf.png)

**Comment by intelyoungway** [comment]
This is traditional Chinese, have you tried simplified one?

**Comment by intelyoungway** [comment]
I tried v0.5.5 it works. I think this loop can be closed now. Thanks.
