### ISSUE TITLE
WinGet publication failed

### ISSUE THREAD

**Issue by dail8859** [dail8859/NotepadNext#208]
@sitiom 

Looks like the latest v0.5.5 release failed to create a PR for WinGet.

The [latest publication action](https://github.com/dail8859/NotepadNext/actions/runs/3119025891/jobs/5058719201) (though it says it finished correctly) seems to have failed.

```
! [remote rejected] dail8859.NotepadNext-0.5.5-75988D8EBBBADE -> dail8859.NotepadNext-0.5.5-75988D8EBBBADE (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/spellCheck.yaml` without `workflow` scope)
```

Luckily the error message is clear enough that I can fix it, but wasn't expecting this access to be required.

I guess we'll wait till the next release. This isn't so much an issue that needs addressed, just wanted to mention it in case you wanted to manually update the WinGet packages for v0.5.5.

Not a big deal.

**Comment by sitiom** [comment]
It's trying to update the workflow because your fork is too old. You can use something like the [pull](https://github.com/apps/pull) app to keep the fork updated regularly.

> I guess we'll wait till the next release.

You can update the fork and rerun the failed workflow to fix it immediately.

**Comment by dail8859** [comment]
@sitiom Oooh! I see. Let me give that a shot.

**Comment by sitiom** [comment]
> The [latest publication action](https://github.com/dail8859/NotepadNext/actions/runs/3119025891/jobs/5058719201) (though it says it finished correctly) seems to have failed.
> 
> ```
> ! [remote rejected] dail8859.NotepadNext-0.5.5-75988D8EBBBADE -> dail8859.NotepadNext-0.5.5-75988D8EBBBADE (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/spellCheck.yaml` without `workflow` scope)
> ```

@vedantmgoyal2009 It might be good to note this in the readme. Forks become too old and will eventually encounter this error.

**Comment by dail8859** [comment]
@sitiom Thanks for the quick tips! I also learned today it's possible to just re-run a job instead of the entire workflow 😄 

https://github.com/microsoft/winget-pkgs/pull/80850
