### ISSUE TITLE
[文件编码] 菜单无效、win7系统下提示缺少vs运行库dll

### ISSUE THREAD

**Issue by JJins** [dail8859/NotepadNext#210]

**Comment by dail8859** [comment]
There is an issue already open for the encoding menu. #88

I believe you'll need the [Visual C++ 2015 Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe) installed to run the application. Though I'm not sure this application will work for Windows 7 or not.

**Comment by JJins** [comment]
Thanks for reply. That was a offline PC, I pasted a DLL and app worked.

________________________________
发件人: dail8859 ***@***.***>
发送时间: Wednesday, September 28, 2022 8:10:52 PM
收件人: dail8859/NotepadNext ***@***.***>
抄送: JJins ***@***.***>; Author ***@***.***>
主题: Re: [dail8859/NotepadNext] [文件编码] 菜单无效、win7系统下提示缺少vs运行库dll (Issue #210)


There is an issue already open for the encoding menu. #88<https://github.com/dail8859/NotepadNext/issues/88>

I believe you'll need the Visual C++ 2015 Redistributable<https://aka.ms/vs/17/release/vc_redist.x64.exe> installed to run the application. Though I'm not sure this application will work for Windows 7 or not.

―
