### ISSUE TITLE
[feature-request] 实现 Npp 的 NppExec 插件

### ISSUE THREAD

**Issue by skywind3000** [dail8859/NotepadNext#220]
很喜欢本项目，基本代替 Npp 了，但 Npp 有个插件 NppExec 可以让我自定义任务，很方便，虽然 NotepadNext 目前还不支持插件，但是希望能提前支持一下这个 NppExec，我经常用它设置一些类似 gcc 编译任务和运行任务来开发运行一些小程序，执行代码格式化等，如果这个 NppExec 的功能可以被一致到 NotepadNext，那么一大票人可以跟我一样告别 Npp 了。

**Comment by keai4le** [comment]
天下苦NPP久矣

**Comment by dail8859** [comment]
I understand the need to have something like NppExec to interact with the OS to support things like compiling code, but I think this kind of functionality will not be implemented for quite some time. That doesn't mean it will never happen. If someone was interested in adding something like this I'd be interested.

Closing for now but feel free to post in the Notepad Next [discussions](https://github.com/dail8859/NotepadNext/discussions) as there may be others interested in such a chatting about such a feature.
