### ISSUE TITLE
[feature request] Identify file language by its content

### ISSUE THREAD

**Issue by NichtsHsu** [dail8859/NotepadNext#221]
~When I open a XML format file that is NOT `*.xml` suffix, NotepadNext cannot automatically identify it as a XML language file, even if it starts with `<?xml version="1.0" encoding="utf-8"?>`.~

~Benefiting from the widespread use of XML, many file types are actually organized in XML format, so I think it's worth doing a header identification for it.~

I realized that XML files don't have to start with an xml header, so this issue should be expanded to identify the language of the file based on file's content.

**Comment by dail8859** [comment]
I've added in the ability to detect a language based on the start of a file (and configured it for XML). Trying to look deeper into the file contents and make a heuristics-based guess is indeed possible but much more work.

Notepad++ can detect based on the start of the file and don't recall anyone asking for the need to look deeper into it. I think for now just looking at the start of the file is fine...anything beyond that would need a very strong use case and a way to prevent false positives.
