### ISSUE TITLE
[Feature request] Copy Search results 

### ISSUE THREAD

**Issue by xkarub** [dail8859/NotepadNext#224]
I am unable to copy the search results window. 
<img width="973" alt="image" src="https://user-images.githubusercontent.com/30411064/194765428-1cb72404-0652-40aa-b0fe-6f16530859d6.png">

It was a handy feature of notepad++. 
Can you please add it?

**Comment by xkarub** [comment]
Hi, @dail8859 , is this going to be fixed with the commit that you referenced? Could we expect a release?
This is such a handy feature.
Thank you!

**Comment by dail8859** [comment]
Sorry, that commit referenced the wrong issue.

I think the feature is definitely needed but not sure when I'll get around to it.

Would you care to describe exactly how you copy the search results in Notepad++? If I recall correctly there are several ways to do it. Just curious what your actual need is so it could be accurately addressed.

**Comment by xkarub** [comment]
The main intention of using it, is after I find all results, I copy them to a new page and analyze them do other text operations. 

![how to use notepadd copy all results](https://user-images.githubusercontent.com/30411064/198876071-e4da4179-5785-477b-bb31-c7cb6cd25f90.gif)

**Comment by xkarub** [comment]
Hi Dail,
Hope you got my message. Apprecaite you looking into it!
