### ISSUE TITLE
bug report ,thx for Next !

### ISSUE THREAD

**Issue by whizsail** [dail8859/NotepadNext#225]
macos 12.6 (21G115)

when using:
chinese  pinyin(mac) : when i click  " shift " and " - ", Next will quit 

<img width="632" alt="image" src="https://user-images.githubusercontent.com/33980241/194898245-3cfd0459-53d1-45ca-b5a0-d5400e824367.png"

**Comment by dail8859** [comment]
Possible duplicate of #194?

**Comment by dail8859** [comment]
You might also try the Qt6 version of the application to see if it has the same issue: https://github.com/dail8859/NotepadNext/suites/8689367306/artifacts/391921672

**Comment by dail8859** [comment]
Closing as a duplicate of #194

If you have any additional details feel free to post on that issue. If what you've ran across is different from that issue then this can be reopened.
