### ISSUE TITLE
Small font on 2k display

### ISSUE THREAD

**Issue by uees** [dail8859/NotepadNext#226]
win11 屏幕设置：
![图片](https://user-images.githubusercontent.com/612757/194974969-3421c448-8863-46d7-9a75-afac99b67775.png)

文件内容默认显示字体太小，TAB标题字体小，状态栏字体小，设置dialog字体小。标题栏和菜单栏显示大小正常。
![图片](https://user-images.githubusercontent.com/612757/194975424-f274ea15-ef6f-4d1c-88c6-272e50f4ebcd.png)

**Comment by imkos** [comment]
按着ctrl键, 滚动鼠标, 一般编辑工具都是这样缩放字体,设置暂无法修改字体属性

**Comment by dail8859** [comment]
Ass suggested at least for the editor you can zoom up the text. The UI font itself is something that I'm not sure how to fix immediatly.

You might try the Qt6 version to see if it has any different results. The stand alone zip can be downloaded here: https://github.com/dail8859/NotepadNext/suites/8689367306/artifacts/391921676

Not sure if that will give any different results.

**Comment by dail8859** [comment]
Also might take a look at #112 with some suggestions on how to work around the high DPI scaling issue.

**Comment by dail8859** [comment]
I'm assuming it has to do with the specific font Windows uses for your locale. It looks fine for my setup. Not sure how Qt handle's this (possible Qt bug maybe?) when determining default font sizes.


![image](https://user-images.githubusercontent.com/3694843/195998374-01f283b3-5f99-44e9-89fc-6485f6384531.png)
