### ISSUE TITLE
缺少vc++ dll反馈

### ISSUE THREAD

**Issue by yanchenyuvip** [dail8859/NotepadNext#227]
![image](https://user-images.githubusercontent.com/44298325/195044598-7c926f38-d126-448c-ab4c-b1e5e059905e.png)
在系统未装vc++模块下，会报错缺少dll，建议自带基本组件；
![image](https://user-images.githubusercontent.com/44298325/195045043-5450eb9e-5ea1-40db-a417-a35359a74632.png)
[](url)
![image](https://user-images.githubusercontent.com/44298325/195045389-6d71882b-3348-43e6-a609-ccbe8b332943.png)
https://www.123pan.com/s/tqFRVv-iQhuA

**Comment by dail8859** [comment]
Thanks for the info. I think it is safe to assume that most users should have the required VC++ runtime already installed on the computer, so I'd rather not have to include additional DLLs at this stime.
