### ISSUE TITLE
Issue with Search Replace

### ISSUE THREAD

**Issue by zeddock** [dail8859/NotepadNext#229]
It could be an "operator error" but I spent some time making sure I was doing things correctly.
Keep in mind:
1. I am running latest version of Manjaro, so not straight Arch.
2. I could be doing something wrong.

I ended up trying to edit a KMZ file.
I wanted to remove all coordinates from areas.
Example: ```<coordinates>39.00003,-81.00345</coordinates>```

**The above from memory.

So to search I expect to FIND / REPLACE with searching for:
```<coordinates>*</coordinates>```
or
```<coordinates>.*</coordinates>```
or
```<coordinates>.+</coordinates>```

...none of these worked regardless of settings.
Only searching for just the ```<coordinates>``` portion would find hits.

I hope this helps and is not a rabbit trail. I woudl love to use NPN for doing this kind of thing in the future!

**Comment by dail8859** [comment]
FYI I tweaked your post to show the XML tags...GitHub was discarding those.

My initial quick test shows it is working correctly.

![image](https://user-images.githubusercontent.com/3694843/195388719-f355d0d4-bf74-430c-a321-4b71c367bf8b.png)

Do you have other options selected on the dialog?

If that still doesn't work can you post the initial first 10ish lines or some from the `Help > Debug Log` panel?
