### ISSUE TITLE
Release zip is only for windows

### ISSUE THREAD

**Issue by sonichy** [dail8859/NotepadNext#230]
NotepadNext-v0.5.5.zip rename to NotepadNext-v0.5.5_windows.zip.

**Comment by dail8859** [comment]
When this project originally started out it just had Windows releases, but now that there are other OSs supported I agree having something in the package name would be useful. I'll probably go with something like `NotepadNext-v0.5.5_windows.zip` or `NotepadNext-v0.5.5-win64.zip`.

There may be some other opportunities to tweak the names of some of the other releases.
