### ISSUE TITLE
No response when Ctrl+h is pressed

### ISSUE THREAD

**Issue by GilaMOS** [dail8859/NotepadNext#234]
win10pro21h2  cpu i5 11   Default Settings
When I press ctrl+h, notepadnext does not use the replace function, only when I press Ctrl+f, the search function is enabled and I can switch to replace，is this a bug？

**Comment by dail8859** [comment]
Duplicate of #207

This has been added in 4775e5f9f6e6c983dd9b05f381a20bbe49c51705 and will be available in the next release.
