### ISSUE TITLE
能否优先支持++的插件呢

### ISSUE THREAD

**Issue by xbing1221** [dail8859/NotepadNext#236]
常用的SQL/JSON格式化插件如果可以使用就能直接换过来了，当然还有类似CTRL+ALT+Q这种竖向选择

**Comment by PaddyTB** [comment]
See #11, #96, #168, #183 to name but a few of the requests for this. Would be helpful if the Issues log was searched before opening a new duplicate issue.

**Comment by dail8859** [comment]
See the other issues linked for a full answer, but no, native Notepad++ won't be able to be supported. Notepad Next is a complete re-write on a completely different framework. The low-level text editing component is the same that Notepad++ uses, so in theory the same things can be achieved but interfacing it through scripting or a plugin would be completely different.
