### ISSUE TITLE
请问能否加入文件缓存功能？即关闭编辑器后为保存的文件自动缓存到某个文件夹下

### ISSUE THREAD

**Issue by bluebat1** [dail8859/NotepadNext#237]
--
请问能否加入文件缓存功能？即关闭编辑器后为保存的文件自动缓存到某个文件夹下。
即关闭编辑器时不必弹出是否保存的弹窗。或者将弹窗作为可选项。

**Comment by dail8859** [comment]
Duplicate of https://github.com/dail8859/NotepadNext/issues/11, https://github.com/dail8859/NotepadNext/issues/96, https://github.com/dail8859/NotepadNext/issues/168, https://github.com/dail8859/NotepadNext/issues/183, #236

**Comment by dail8859** [comment]
The main issue to track this feature is #81
