### ISSUE TITLE
AppImage app icon wrong path

### ISSUE THREAD

**Issue by sonichy** [dail8859/NotepadNext#238]
/tmp/.mount_NotepaeBor6k/usr/share/icons/hicolor/scalable/mimetypes/NotepadNext.svg
Should be
/tmp/.mount_NotepaeBor6k/usr/share/icons/hicolor/scalable/apps/NotepadNext.svg

**Comment by dail8859** [comment]
Any other details or documentation you can provide as to why the path needs changed?

Is the icon not working?

**Comment by sonichy** [comment]
mimetypes dir use to put filetype icon *.*.
apps dir use to put app icons.
It is a standard.

**Comment by dail8859** [comment]
So are you saying the application does not have an icon showing up for you?

**Comment by sonichy** [comment]
Have an icon

**Comment by dail8859** [comment]
I made the changes as described. Even looked at other AppImages. I don't think it is hurting anything adding it in, but from everything I could tell, it doesn't behave any differently. Maybe it will for you.

**Comment by sonichy** [comment]
It is a freedesktop standrdard, apps icon and mimetypes icon should put in right path.
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

**Comment by dail8859** [comment]
I made the change, but it doesn't make any visual difference as far as I can tell, maybe it will for your system.
