### ISSUE TITLE
DarkBackground and HighLight

### ISSUE THREAD

**Issue by sonichy** [dail8859/NotepadNext#239]
DarkBackground: https://github.com/sonichy/HTYEdit/blob/master/mdichild.cpp#L59
HighLight: https://github.com/sonichy/HTYEdit/blob/master/highlighter.cpp

**Comment by dail8859** [comment]
Please provide more details. Not sure what you are asking or hinting at.

**Comment by sonichy** [comment]
Method of change background to black.
Syntax highlight cpp.
![alt](https://raw.githubusercontent.com/sonichy/HTYEdit/master/preview.png)

**Comment by sonichy** [comment]
Menu: Help -  Lua Console

`editor.StyleBack[STYLE_DEFAULT] = 0`
Page background is good, but lines have white background.

```
editor.StyleBack[STYLE_DEFAULT] = 0
editor:StyleClearAll()
```
Text turn to white all, not good.

Can you write these commands to theme settings ?

Try color settings in wxmedit.

**Comment by sonichy** [comment]
I worked out yesterday:
https://www.gitlink.org.cn/sonichy/HTYEdit/commits/43e319cff1

**Comment by dail8859** [comment]
If you are suggesting actual code changes to this project please create a pull request, because the changes you linked to don't seem relevant at all to this project.
