### ISSUE TITLE
Add Support Drag File Open

### ISSUE THREAD

**Issue by lyh061619** [dail8859/NotepadNext#241]
Want to add new functions to automatically open the file by dragging the mouse to the editor

**Comment by dail8859** [comment]
What OS are you using? It works for me on Windows.

**Comment by lyh061619** [comment]
windows

**Comment by dail8859** [comment]
I know that Windows will not allow you to drag and drop for an uneleveated process (Explorer) to an elevated process (Notepad Next). Are you running it as admin?

If not can you describe exactly what you are doing? For me I open the application and drag a file from the desktop and it opens as expected.

You might also try viewing the "Debug Log" under the help menu to see if it shows any relevant information at the time that you drag and drop the file into the application.
