### ISSUE TITLE
No "open with NotepadNext" in right click menu in Ubuntu

### ISSUE THREAD

**Issue by zbh531** [dail8859/NotepadNext#242]
Hi! I installed NotepadNext v0.5.4 via Flatpak in Ubuntu 22.04, but I could not open file with it because it does not show in the "Open With" in the right click menu.

I would really appreciate it if you or somebody could tell if this phenomenon is true or if I installed it wrong.

**Comment by eson57** [comment]
It appear to be fixed in v0.5.5

**Comment by dail8859** [comment]
By default, Notepad Next does not register itself with any file extensions. I believe once you tell the OS to open the file extension with Notepad Next you'll get that suggestion on the right click menu.
