### ISSUE TITLE
Column editing

### ISSUE THREAD

**Issue by don6019** [dail8859/NotepadNext#244]
I haven't been able to select a column of text. Has this been implemented ?
In notepad++ in the Edit menu there is a Column mode option or selecting with mouse by dragging with Alt key.

This would be a good feature to have if not already implemented.

Thanks

**Comment by dail8859** [comment]
On Windows <kbd>Alt+Dragging</kbd> works for me. <kbd>Shift+Alt+\<arrow keys\></kbd> also works.

What OS are you using?

**Comment by don6019** [comment]
Sorry yes I should have mentioned that I am using Linux Zorin OS16
Indeed yes Shift+Alt+<arrow keys> does work.
However on Linux it seems Alt+Dragging moves the current window.
Thanks for the reply. Keep up the good work. NotepadNext is gradually becoming a good alternative on linux, thanks.

**Comment by dail8859** [comment]
> I am using Linux Zorin OS16

Thanks for the info!

> Indeed yes Shift+Alt+ does work.

Might have to just stick with that for the time being.

---

The editing component used internally (Scintilla) seems to have [documentation](https://www.scintilla.org/ScintillaDoc.html#SCI_SETRECTANGULARSELECTIONMODIFIER) describing how to change the modifier key but it doesn't seem to work at all, so this looks like a Scintilla bug.

**Comment by dail8859** [comment]
https://groups.google.com/g/scintilla-interest/c/CkSpBprC_OY

**Comment by dail8859** [comment]
This patch has been accepted in the upstream Scintilla project.

https://sourceforge.net/p/scintilla/code/ci/893cfd2686f43188a8f26ff4dafd162b8d6f44c8/

Closing this issue for now. Notepad Next has the ability to change it but it isn't currently exposed anywhere. That's part of a larger effort to make a working preference dialog.
