### ISSUE TITLE
试用了一下，很好用，提一点小建议

### ISSUE THREAD

**Issue by ccpwcn** [dail8859/NotepadNext#249]
Thanks the author for providing us with such easy software to pay tribute to you. Hope to improve better:
1. Being able to cache unbeaten files, when I built a new blank document, after entering some text in it, when the software is closed, it may not be saved into the disk(temporary working files). Now I close the software, after the next time it is opened, the file was in the document, The content was still there, Notepad++ is very practical in this regard. Because sometimes, I just record some information in the work at will. Temporarily use it for a while, and the use of it is abandoned. Each time it is forced to save, it is more troublesome. I will definitely save it on the disk manually.
2. The LOGO and Icon of the software are white and the color is too light, the line is not sharp enough that is not as clear and intuitive as Notepad++ and Sublime Text on Windows OS.
3. Open the closing button in the upper right corner of the tab page of the file. The background color should indeed be red, but this red is too dark. RGB (255,0,0) in this software, looking at other software, more friendly colors are recommended to use RGB (251,115,115)

Thanks to the author, I hope this software is getting better and better.

感谢作者给我们提供如此好用的软件，向您致敬。希望改进的更好用：
1. 能够缓存未保存的文件，当我新建了一个空白文档，在里面随意地输入了一些文字之后，关闭软件时，不一定必须要保存到磁盘上，软件可以直接关闭，下次打开之后，文件中的内容还在，notepad++在这方面很实用。因为有的时候，我只是随意地记录一些工作中的信息，暂时用一下，用完废弃掉了，每次都强制保存，比较麻烦，重要的工作，我肯定会手动保存到磁盘上的。
2. 软件的logo和icon泛白，颜色太淡，在Windows上不像notepad++和sublime text那样清晰和直观
3. 打开文件的tab页右上角的关闭按钮，背景色确实应该是红色，但是这个红色太深了。这个软件中的RGB(255,0,0)，看其他软件，比较友好的颜色推荐使用RGB(251,115115)
感谢作者，希望这个软件越来越好。

**Comment by zhongqingsong** [comment]
Boy, It'S better TO issue in English, MANY OF THEM DON't UNDERSTAND Chinese. Affecting the efficiency of communication.
最好使用英文提issue，他们很多人不懂中文的。影响沟通效率的。

**Comment by dail8859** [comment]
1. This feature has been requested many times and is planned to be added at some point but not sure when. See #81
2. I'm not completely set on the icon it has currently, but currently I don't have any immediate plans to change it myself. If someone has some examples to show I'd be willing to take a look and see if I like them. 
3. I agree with you on this suggestion. I'll adjust it and see what looks better. For my own reference I think this is the only place that would need changed: https://github.com/dail8859/NotepadNext/blob/fe75620eecb2a35e59383acfec98a252dc60a636/src/NotepadNext/stylesheets/npp.css#L63
