### ISSUE TITLE
In the process of use, there are two suggestions

### ISSUE THREAD

**Issue by thousmile** [dail8859/NotepadNext#254]
1.For the first time, press ctrl+mouse wheel to enlarge the font and close the window.
Open again, the font cannot change back to the previous size

https://user-images.githubusercontent.com/28520524/199146351-88ef0ffc-e68f-4196-b630-5460c17ae9fc.mp4

2.Open the first file, and then display it in full screen. Press win+d to return to the desktop. When you open the file again, "Notepad Next" will not be displayed. You need to open the file again to display it!

3.After closing "Notepad Next", open it again. The file history of previous calls is gone!

https://user-images.githubusercontent.com/28520524/199148443-0cae18a7-74b5-4bdf-83a8-e7589576e3fb.mp4

The operating system I use is : Windows 10 Professional 21H2

**Comment by dail8859** [comment]
Thanks for the information and videos...that is helpful to see the issue!

1. Zoom is not currently saved between sessions but I agree this is needed. There's a few technical issues I'll need to figure out how to handle first.
2. That is very odd. I was able to get the same issue, so I'll have to look into that more
3. See #81. This feature is planned.

**Comment by dail8859** [comment]
The issue of the zoom not getting saved has been addressed with 022acbc0838d9674eb778d3c9c0ca9cd9b60a2ad
