### ISSUE TITLE
v0.5.5 M1无法打开

### ISSUE THREAD

**Issue by liyanggyang** [dail8859/NotepadNext#256]
It‡T#"NotepadNext.app", a
为无法验证开发者。

macos 无法验证此 App 不包含恶意软件。

![Uploading Snipaste_2022-11-03_09-22-25.png…]()

**Comment by liyanggyang** [comment]
<img width="300" alt="Snipaste_2022-11-03_09-22-25" src="https://user-images.githubusercontent.com/23524563/199631779-3643e012-612f-476d-9a68-f9042cade322.png">

**Comment by dail8859** [comment]
Take a look at #199

I'm not a Mac expert but I believe M1 support is not officially available yet. When the Qt version is updated then I think it should work. You can discuss more on that issue as there are other users that have discussed this topic.
