### ISSUE TITLE
I can't see "Encoding menu" on my computer.

### ISSUE THREAD

**Issue by bluskai** [dail8859/NotepadNext#258]
System environment: Windows 10 22H2 19045.2130
NotepadNext version: v0.5.5
Before click "Encoding menu"
![1](https://user-images.githubusercontent.com/37144222/199859793-9bb21b80-667a-4d29-bb08-8c23555c17d7.png)
After click "Encoding menu"
![2](https://user-images.githubusercontent.com/37144222/199859806-dd8c8cbd-277d-4f9c-9794-4d472178af90.png)

**Comment by dail8859** [comment]
See #49

This is not yet implemented. I can understand the empty menu can cause a bit of confusion, so I went ahead and added a placeholder for now to let users know this is intentional.

![image](https://user-images.githubusercontent.com/3694843/199862884-97171bc4-9627-4804-890d-98f62fea7667.png)
