### ISSUE TITLE
support link open in the browser

### ISSUE THREAD

**Issue by bluebabes** [dail8859/NotepadNext#260]
example:

Selected text

Right click

If it is a link, an option can be opened in the browser

**Comment by NichtsHsu** [comment]
Hi @dail8859 ,

I tested the following text in NotepadNext:

```
[Quick Start](https://valine.js.org/quickstart.html)
```

Confusingly, NotepadNext marks `https://valine.js.org/quickstart.html)` as a link, with an unnecessary `)` at its end.

**Comment by dail8859** [comment]
@NichtsHsu Good catch. Technically a `)` is allowed in a URL, so even though it meets the spec, I agree there could be a little bit of 'cleanup'

**Comment by dail8859** [comment]
@NichtsHsu d4844cab34efe729232666e7b13dbc0d45afb007

This works pretty well now. There are still a few odd corner cases, but those would be rare and not probably not worth fixing.
