### ISSUE TITLE
Close notepadNext without saving new files

### ISSUE THREAD

**Issue by antnesswcm** [dail8859/NotepadNext#263]
# Close notepadNext without saving new files

I remember that notepad++can also close the window without saving the new file.
When you open notepad again, the unsaved file will still be displayed in the window. This is very useful when writing a draft, so you don't need to bother saving the file
I don't know whether this function is in the development plan. I hope you can consider it
English translation from Google, please forgive me

---------------------
# 不保存新文件的情况下关闭notepadNext

我记得，notepad++在没有保存新建文件时，也可以关闭窗口。
再次打开notepad时依然会以未保存的文件显示在窗口里，这在写草稿的时候很有用，不用麻烦的保存文件
不知道这个功能是否在开发计划里，希望可以考虑
英文翻译来自Google请见谅

**Comment by dail8859** [comment]
Hi @antnesswcm

This is a very popular feature request, and yes it is planned to be implemented. There is another issue for this feature request (#81) and there has been some discussion there. I've started some basic work on it but just need to find some more time to work on it.
