### ISSUE TITLE
找不到MSVCP140.dll

### ISSUE THREAD

**Issue by ukhack** [dail8859/NotepadNext#265]
win11 22H2 原版镜像刚装完 安装完NotepadNext-v0.5.5-Installer打开就报错。

考虑到可能是缺VC++库，补了两个VS2015的x86/x64库

未见效
![image](https://user-images.githubusercontent.com/17568491/201109743-cffd151a-8461-494c-88d2-a1296c8ea1de.png)

**Comment by dail8859** [comment]
I'm not sure how else to get those files. I'm assuming this is something specific to your PC as I have not heard of anyone else running into this issue yet.

I've got the `Microsoft Visual C++ 2015-2022 Redistributable Package` installed (both x86 and x64) on Windows 11.

I'll close this for now unless someone else has more details.
