### ISSUE TITLE
[Feature Request]Filename extension support on macOS

### ISSUE THREAD

**Issue by wylapp** [dail8859/NotepadNext#267]
Currently, the NotepadNext have not declared what kind of file it can handle, which makes opening files on the macOS extremely unfriendly. 
For example, when I want to browse a simple `.cpp` file, I can not find **NotepadNext** in the 'open in' context menu.
<img width="552" alt="image" src="https://user-images.githubusercontent.com/11030493/201464893-e9529416-e7bf-4703-af6e-9a5ee35f726a.png">
Then, I had to choose "others", but the OS does not think that NotepadNext have the ability to open a `.cpp` file, i.e. the icon is unclickable. 
<img width="658" alt="image" src="https://user-images.githubusercontent.com/11030493/201464968-89df098c-0ffc-4575-9c4a-61c313f59b9e.png">
Ultimately, I have to click multiple times...just to make the OS BELIEVE that NotepadNext could open a .cpp file.
I'm not a macOS developer, but I believe there should be some settings in the metafile which makes this procedure simple and easy.

**Comment by dail8859** [comment]
> I'm not a macOS developer

I'm not either. I honestly don't have a clue how to set this kind of info for the application. (I don't even know how to change to add a space in the app name so that it shows up as `Notepad Next` 🙂 )

Ideally it would be nice to tell the OS that _any_ text based file would be appropriate. It suggests using Word and Excel to open the cpp file, which on the surface seems odd, but if the application is set to try to open _anything_, then that would also be ideal for Notepad Next.

I'll see if I can look at some other Qt apps or maybe someone can suggest some solution.

**Comment by wylapp** [comment]
I did some research, and find out the filetype support declaration is defined in the `info.plist` file inside the macOS `.app` application package. Take VS Code as an example:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/11030493/201959733-c0ee8d5d-e6ce-4153-b1a8-6b58be39afdf.png">
Specified document could be find at [Apple Dev](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundledocumenttypes/cfbundletypename), to manipulate this file in Qt, [this document](https://doc.qt.io/qt-5/qmake-variable-reference.html#qmake-info-plist) can be referred.

Since this issue bothers me most, when I have time, maybe I'll take a try.

**Comment by dail8859** [comment]
@wylapp 

Excellent info! That definitely seems to be the correct way to handle it.

> Since this issue bothers me most, when I have time, maybe I'll take a try.

Any help is greatly appreciated! It doesn't look too complicated, just would take some trial and error. I don't have a Mac at all so I'd literally just be shooting in the dark with any changes I would attempt.

**Comment by dail8859** [comment]
Dig some digging into this. I'm really just shooting in the dark. You might try editing the info.plist file for Notepad Next and try using this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleExecutable</key>
	<string>NotepadNext</string>
	<key>CFBundleName</key>
	<string>Notepad Next</string>
	<key>CFBundleIconFile</key>
	<string>NotepadNext.icns</string>
	<key>CFBundleIdentifier</key>
	<string>com.yourcompany.NotepadNext</string>
	<key>CFBundleShortVersionString</key>
	<string>6.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.14</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>NSSupportsAutomaticGraphicsSwitching</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleAllowMixedLocalizations</key>
	<true/>
	<key>CFBundleDocumentTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeName</key>
			<string>Text File</string>
			<key>LSHandlerRank</key>
			<string>Alternate</string>
			<key>LSItemContentTypes</key>
			<array>
				<string>public.text</string>
			</array>
		</dict>
	</array>
</dict>
</plist>
```

**Comment by wylapp** [comment]
This Info.plist file seems not working on my Mac. I directly edited the `Info.plist` inside the NotepadNext.app, then reboot the computer, however, in the 'open in' context menu, NotepadNext is still not the alternative app for opening a .txt file.
But the good news is, I have found the answer! I replaced line 29-38 with the following code (which comes from VS code)
```xml
<dict>
	<key>CFBundleTypeExtensions</key>
	<array>
		<string>txt</string>
	</array>
	<key>CFBundleTypeIconFile</key>
	<string>default.icns</string>
	<key>CFBundleTypeName</key>
	<string>Plain Text File</string>
	<key>CFBundleTypeOSTypes</key>
	<array>
		<string>TEXT</string>
		<string>utxt</string>
		<string>TUTX</string>
		<string>****</string>
	</array>
	<key>CFBundleTypeRole</key>
	<string>Editor</string>
</dict>
```
then, I moved NotepadNext.app out from `/Applications` directory and moved it back (pretending to reinstall NotepadNext). This time, NotepadNext showed up in the 'open in' context menu. I guess MacOS will register `Info.plist` when installing the application.
<img width="536" alt="image" src="https://user-images.githubusercontent.com/11030493/219060091-4f37bf54-0b2f-4a39-b0e2-65b2fb9c1062.png">

**Comment by dail8859** [comment]
> The good news is, this Info.plist works.

Awesome! Thanks for testing it out. I literally was just kind of guessing at the changes (chatgpt may have helped me some too 😄)

I'll look into getting this plist automatically bundled in the app on build.

**Comment by dail8859** [comment]
@wylapp Can you give this a try? You'll need to unzip it first. From the looks of it the info.plist should be correct, but I have no way to verify it.

https://github.com/dail8859/NotepadNext/suites/11036377555/artifacts/560494941

**Comment by wylapp** [comment]
I’ve tried install this app package on the following machines:
- MacBook Pro, intel i5, MacOS 11.7
- MacBook Pro, apple M1, MacOS 13

The 'open in' feature works fine on both two computers.

**Comment by dail8859** [comment]
@wylapp Awesome! Thanks for testing it out!
