### ISSUE TITLE
can not open the "find in files" dialog on kali 2022.4

### ISSUE THREAD

**Issue by sfncat** [dail8859/NotepadNext#269]
open the menu "find in files",no dialog come out.
Notepad Next v0.5.5 (AppImage)

OS info:
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION="2022.4"
VERSION_ID="2022.4"
VERSION_CODENAME="kali-rolling"
ID=kali
ID_LIKE=debian

**Comment by dail8859** [comment]
Duplicate of #48

The functionality is not implemented yet, but it is planned at some point.
