### ISSUE TITLE
Not applying indent_style from .editorconfig file

### ISSUE THREAD

**Issue by JohanChane** [dail8859/NotepadNext#270]

**Comment by dail8859** [comment]
> How to translate a tab to four spaces

There is no option for this yet.

> set line ending to unix in Windows

Using the menu `Edit` -> `EOL Conversion`

---

If you are familiar with https://editorconfig.org/ you can also use an `.editorconfig` file in the directory but that's a bit more technical than most are willing to do.

**Comment by JohanChane** [comment]
`indent_style = space` works in .py file, but not in `.txt` or `.md` etc. files.

My .editorconfig file:

```
root = true

[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 4
charset = utf-8

[Makefile]
indent_style = tab
indent_size = 4

[*.py]
indent_style = space
indent_size = 4
```

**Comment by dail8859** [comment]
@JohanChane 

Thanks for trying that out! From the debug log it looks like it is reading in the correct settings. However, some of the editorconfig settings are getting overriden. I believe do to this being applied after the editor config settings are:

https://github.com/dail8859/NotepadNext/blob/e00e668e5d3f182e74388f3f96dd2a615d93cc95/src/NotepadNext/NotepadNextApplication.cpp#L265

The reason it appears to work for Python is that Python one of the few (maybe only?) languages that defaults to spaces:

https://github.com/dail8859/NotepadNext/blob/e00e668e5d3f182e74388f3f96dd2a615d93cc95/src/NotepadNext/languages/python.lua#L9

So definitely an issue with handling the `indent_style` option from the editor config file.

**Comment by JohanChane** [comment]
I don't want to build the project. Is there a config file like the config file of sublime or notepad3 in NotepadNext?

**Comment by dail8859** [comment]
I was more pointing to the code so that I can track this issue down later once I have some more time. I wasn't suggesting you had to modify the code yourself :)

There is a config file but this setting isn't exposed. Notepad Next is still missing alot of features and this kind of setting is definitely planned.

**Comment by JohanChane** [comment]
I will wait for the new features. Thanks.
