### ISSUE TITLE
Opening a file on NTFS volume: file doesn't exist

### ISSUE THREAD

**Issue by Spaceboy60** [dail8859/NotepadNext#278]
When opening files on an NTFS volume from Linux,  it says file doesn't exist and do I want to create it.

The same file/s opens without issues in other editors.

I'm running **fedora 37**.

**Comment by elcuco** [comment]
I cannot reproduce under  Debian, using Linux 6.0.0-4. Can you spare more details?

**Comment by Spaceboy60** [comment]
What specific details are you looking for?

**Comment by elcuco** [comment]
dunno... can you add some debug code ... add  a breakpoint.. or even do a `strace` on that?  Can you share the file here? (what happens if you copy it to an ext4 partition, and open there?)

**Comment by Spaceboy60** [comment]
It's all files, all text files on NTFS volumes.

If you copy it to an ext4 volume it opens and saves fine yes.

What's the command to open Notepad next ? Maybe opening a file using command line will spit out something useful

**Comment by dail8859** [comment]
> Maybe opening a file using command line will spit out something useful

There is debug information under `Help > Debug Log`. Still relevant to post it here but I'm assuming for some reason this section:

https://github.com/dail8859/NotepadNext/blob/e9b53959faabfa0d61cd8e0373bd4146c6b46dfb/src/NotepadNext/dialogs/MainWindow.cpp#L664-L667

is not working properly. According to the [documentation](https://doc.qt.io/qt-6/qfileinfo.html) NTFS only has special conditions when checking files permissions. It doesn't specifically mention it in regards to `isFile()` but maybe something deeper in the code is doing some sort of permissions checking.

**Comment by Spaceboy60** [comment]
[     0.277] I: =============================
[     0.277] I: Notepad Next v0.5.6 (Flatpak)
[     0.277] I: Build Date/Time: Nov 21 2022 18:58:03
[     0.277] I: Qt: 5.15.7
[     0.277] I: OS: KDE Flatpak runtime
[     0.277] I: Locale: en_GB
[     0.277] I: CPU: x86_64
[     0.277] I: File Path: /app/bin/NotepadNext
[     0.277] I: Arguments: NotepadNext /run/media/Spaceboy/New Volume/Linux/virt_manager.txt
[     0.277] I: =============================
[     0.277] I: bool NotepadNextApplication::init()
[     0.310] I: void NotepadNextApplication::loadTranslation(QLocale)
[     0.310] I: en_GB translation not found for Notepad Next
[     0.310] I: en_GB translation not found for Qt components
[     0.310] I: LuaState::LuaState()
[     0.346] I: MacroManager::MacroManager(QObject*)
[     0.347] I: void MacroManager::loadSettings()
[     0.347] I: MainWindow::MainWindow(NotepadNextApplication*)
[     0.384] I: setupUi Completed
[     0.419] I: void MainWindow::setupLanguageMenu()
[     0.444] I: void MainWindow::restoreSettings()
[     0.445] I: void NotepadNextApplication::openFiles(const QStringList&)
[     0.445] I: void MainWindow::openFileList(const QStringList&)
[     0.445] I: /run/media/Spaceboy/New Volume/Linux/virt_manager.txt
[     1.599] I: void MainWindow::newFile()
[     1.600] I: void EditorManager::setupEditor(ScintillaNext*)
[     1.602] I: void MainWindow::addEditor(ScintillaNext*)
[     1.602] I: void MainWindow::detectLanguage(ScintillaNext*)
[     1.602] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
[     1.602] I: Language Name: Text
[     1.603] I: void DockedEditor::addEditor(ScintillaNext*)
[     1.621] I: void MainWindow::activateEditor(ScintillaNext*)
[     1.621] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[     1.621] I: void MainWindow::updateGui(ScintillaNext*)
[     1.621] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
[     1.621] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[     1.621] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
[     1.621] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)
[     1.847] I: Scintilla::Internal::RegexSearchBase* Scintilla::Internal::CreateRegexSearch(CharClassify*)
[    46.341] I: void MainWindow::focusIn()
[    46.343] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[    46.344] W: Wayland does not support QWindow::requestActivate()
[    48.789] W: This plugin supports grabbing the mouse only for popup windows
[    50.030] W: This plugin supports grabbing the mouse only for popup windows

**Comment by dail8859** [comment]
Thanks for the info. Nothing immediately looks odd.

I guess just to make sure:

1. Are you able to open other files via command line that aren't hosted on an NTFS share?
2. Does the same thing happen when using the `File > Open...` menu?

**Comment by Spaceboy60** [comment]
> Thanks for the info. Nothing immediately looks odd.
> 
> I guess just to make sure:
> 
>     1. Are you able to open other files via command line that aren't hosted on an NTFS share?
> 
>     2. Does the same thing happen when using the `File > Open...` menu?

1.  No, I get same message
2.  No, it opens without issue that way

**Comment by dail8859** [comment]
> No, I get same message

So then what you are saying is this has nothing to do with NTFS?

**Comment by Spaceboy60** [comment]
> > No, I get same message
> 
> So then what you are saying is this has nothing to do with NTFS?

Yes, it appears that way

**Comment by dail8859** [comment]
> Yes, it appears that way

So let's start with the basic case to reproduce this. Try to open two files that are on the local file system. One that exists, and one that doesn't exist. What's the output for those two cases?

**Comment by dail8859** [comment]
I spun up a fresh Fedora 37 VM and installed it via the flatpak.

I don't have any NTFS shares but just trying to open files that either exist or don't exist in my home directory is working as expected.

**Comment by elcuco** [comment]
I wonder if Fedora uses a different NTFS module then the one I am.. .can you share the relevant output of `muont` and `lsmod`?

**Comment by Spaceboy60** [comment]
> I spun up a fresh Fedora 37 VM and installed it via the flatpak.
> 
> I don't have any NTFS shares but just trying to open files that either exist or don't exist in my home directory is working as expected.

I'm running Fedora KDE 37 (used everything ISO on fedora site to install) in case that makes a difference.

**Comment by Spaceboy60** [comment]
> I wonder if Fedora uses a different NTFS module then the one I am.. .can you share the relevant output of `muont` and `lsmod`?

**Mount:**
```
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime,seclabel)
devtmpfs on /dev type devtmpfs (rw,nosuid,seclabel,size=4096k,nr_inodes=1048576,mode=755,inode64)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,seclabel,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,seclabel,size=1408596k,nr_inodes=819200,mode=755,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,seclabel,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime,seclabel)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
/dev/sdd2 on / type btrfs (rw,relatime,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=257,subvol=/root)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,nosuid,noexec,relatime)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=16247)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime,seclabel)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,seclabel,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime,seclabel)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime,seclabel)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,seclabel,size=3521484k,nr_inodes=1048576,inode64)
/dev/sdd2 on /home type btrfs (rw,relatime,seclabel,compress=zstd:1,ssd,space_cache=v2,subvolid=256,subvol=/home)
/dev/sdd1 on /boot type ext4 (rw,relatime,seclabel)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=704296k,nr_inodes=176074,mode=700,uid=1000,gid=1000,inode64)
portal on /run/user/1000/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/sda2 on /run/timeshift/backup type ext4 (rw,relatime,seclabel)
portal on /root/.cache/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
/dev/sda1 on /run/media/Spaceboy/New Volume type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)
/dev/sda3 on /run/media/Spaceboy/Windows 7 type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)
/dev/sdc2 on /run/media/Spaceboy/967663DC7663BB9D type fuseblk `(rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)
````

**lsmod**
```
Module                  Size  Used by
vhost_net              36864  0
vhost                  57344  1 vhost_net
vhost_iotlb            16384  1 vhost
tap                    28672  1 vhost_net
tun                    61440  1 vhost_net
ntfs3                 274432  0
xt_CHECKSUM            16384  1
xt_MASQUERADE          20480  3
xt_conntrack           16384  1
ipt_REJECT             16384  2
nft_compat             20480  7
nf_nat_tftp            16384  0
nft_objref             16384  1
nf_conntrack_tftp      20480  3 nf_nat_tftp
bridge                360448  0
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
tls                   126976  2
uinput                 20480  0
snd_seq_dummy          16384  0
snd_hrtimer            16384  1
nft_fib_inet           16384  1
nft_fib_ipv4           16384  1 nft_fib_inet
nft_fib_ipv6           16384  1 nft_fib_inet
nft_fib                16384  3 nft_fib_ipv6,nft_fib_ipv4,nft_fib_inet
nft_reject_inet        16384  7
nf_reject_ipv4         16384  2 nft_reject_inet,ipt_REJECT
nf_reject_ipv6         20480  1 nft_reject_inet
nft_reject             16384  1 nft_reject_inet
nft_ct                 20480  20
nft_chain_nat          16384  5
nf_nat                 57344  3 nf_nat_tftp,nft_chain_nat,xt_MASQUERADE
nf_conntrack          167936  6 xt_conntrack,nf_nat,nf_conntrack_tftp,nft_ct,nf_nat_tftp,xt_MASQUERADE
nf_defrag_ipv6         24576  1 nf_conntrack
nf_defrag_ipv4         16384  1 nf_conntrack
ip_set                 61440  0
cfg80211             1097728  0
nf_tables             286720  462 nft_ct,nft_compat,nft_reject_inet,nft_fib_ipv6,nft_objref,nft_fib_ipv4,nft_chain_nat,nft_reject,nft_fib,nft_fib_inet
nfnetlink              20480  4 nft_compat,nf_tables,ip_set
qrtr                   53248  4
sunrpc                692224  1
edac_mce_amd           57344  0
kvm_amd               172032  0
ccp                   122880  1 kvm_amd
snd_hda_codec_realtek   172032  1
snd_hda_codec_generic    98304  1 snd_hda_codec_realtek
eeepc_wmi              16384  0
snd_hda_codec_hdmi     86016  1
asus_wmi               65536  1 eeepc_wmi
snd_hda_intel          61440  4
snd_intel_dspcfg       36864  1 snd_hda_intel
snd_intel_sdw_acpi     20480  1 snd_intel_dspcfg
snd_hda_codec         184320  4 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec_realtek
kvm                  1122304  1 kvm_amd
r8188eu               405504  0
snd_hda_core          114688  5 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek
ledtrig_audio          16384  2 snd_hda_codec_generic,asus_wmi
sparse_keymap          16384  1 asus_wmi
snd_hwdep              16384  1 snd_hda_codec
joydev                 28672  0
libarc4                16384  1 r8188eu
platform_profile       16384  1 asus_wmi
irqbypass              16384  1 kvm
rfkill                 36864  5 asus_wmi,cfg80211
snd_seq                94208  7 snd_seq_dummy
wmi_bmof               16384  0
pcspkr                 16384  0
snd_seq_device         16384  1 snd_seq
fam15h_power           16384  0
k10temp                16384  0
snd_pcm               151552  4 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_core
i2c_piix4              36864  0
snd_timer              49152  3 snd_seq,snd_hrtimer,snd_pcm
snd                   126976  20 snd_hda_codec_generic,snd_seq,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek,snd_timer,snd_pcm
soundcore              16384  1 snd
acpi_cpufreq           32768  0
zram                   36864  2
amdgpu              10162176  0
iommu_v2               24576  1 amdgpu
gpu_sched              49152  1 amdgpu
drm_buddy              20480  1 amdgpu
radeon               1851392  86
crct10dif_pclmul       16384  1
crc32_pclmul           16384  0
crc32c_intel           24576  5
polyval_clmulni        16384  0
polyval_generic        16384  1 polyval_clmulni
r8169                 102400  0
drm_ttm_helper         16384  2 amdgpu,radeon
ghash_clmulni_intel    16384  0
ttm                    94208  3 amdgpu,radeon,drm_ttm_helper
sp5100_tco             20480  0
uas                    32768  0
usb_storage            81920  1 uas
drm_display_helper    180224  2 amdgpu,radeon
cec                    81920  1 drm_display_helper
wmi                    45056  2 asus_wmi,wmi_bmof
video                  65536  1 asus_wmi
scsi_dh_rdac           16384  0
scsi_dh_emc            16384  0
scsi_dh_alua           20480  0
fuse                  176128  11
dm_multipath           45056  0
```

**Comment by dail8859** [comment]
> It's all files, all text files on NTFS volumes.

> If you copy it to an ext4 volume it opens and saves fine yes.

---

>>> No, I get same message

>> So then what you are saying is this has nothing to do with NTFS?

> Yes, it appears that way

---

I'm very confused at this point. At one point only NTFS doesn't work, and another it doesn't seem to relate to NTFS at all?

**Comment by Spaceboy60** [comment]
> > It's all files, all text files on NTFS volumes.
> 
> > If you copy it to an ext4 volume it opens and saves fine yes.
> 
> > > > No, I get same message
> 
> > > So then what you are saying is this has nothing to do with NTFS?
> 
> > Yes, it appears that way
> 
> I'm very confused at this point. At one point only NTFS doesn't work, and another it doesn't seem to relate to NTFS at all

NTFS  files will only open if you open for file via file open within the app

EXT4: opens fine unless you open it from a command line

**Comment by elcuco** [comment]
THIS IS **** WIERD.

I have this local build, which on my machine, can load files from NTFS (I use fuse as you do!) and I can load the same file form the UI. 

```
diego@debian:~/src/github/NotepadNext$ mount | grep /tmp/1
/dev/nvme0n1p3 on /tmp/1 type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
diego@debian:~/src/github/NotepadNext$ ./cbuild/src/NotepadNext/NotepadNext /tmp/1/Users/desktop.ini 
``` 
This works. I can open that manually (the cmake build is of the same quality of the normal builds, it makes no difference).

Can you can NotepadNext using `strace`? See an example bellow. Please attach `1.txt` or whatever you name the file here.   (adopt the path to NotepadNext, and the file to open as you need.. obviously).

```
strace -o1.txt  ./cbuild/src/NotepadNext/NotepadNext /tmp/1/Users/diego/.viminfo 
```

**Comment by elcuco** [comment]
.. @Spaceboy60 ... ping...?

**Comment by dail8859** [comment]
Due to the difficulty reproducing this, the issue will be closed for now. If there are more specific details, a small reproducible test case, or others that start to encounter it then it can be reopened.
