### ISSUE TITLE
Copy text to clipboard in RTF format (with syntax styling information) ，Can be added as soon as possible? 

### ISSUE THREAD

**Issue by HeliusHao** [dail8859/NotepadNext#283]
Copy text to clipboard in RTF format (with syntax styling information) ，Can be added as soon as possible?

**Comment by dail8859** [comment]
When you say RTF, are you meaning _true_ RTF? Because the RTF standard is quite old and poorly documented.

Where are you intending to paste the text into (email client, word processor, etc)?
