### ISSUE TITLE
Bad performance on large files

### ISSUE THREAD

**Issue by MichaelWU0726** [dail8859/NotepadNext#284]
In Windows11，frame freezing often occurred when running, especially for large file

**Comment by dail8859** [comment]
> especially for large file

What are you considering as 'large'?

Does the same thing happen for small (1KB) files?

**Comment by dail8859** [comment]
And more specifically, is it while you are doing certain actions such as scrolling? Typing? Searching?

**Comment by MichaelWU0726** [comment]
> And more specifically, is it while you are doing certain actions such as scrolling? Typing? Searching?

I opened an assembly file and the codes were colorful in the front section, but when scolled the codes, they weren't colorful and the software freezed

**Comment by dail8859** [comment]
> My file size is about 200M

To be honest the application has not been optimized that well to handle large files. For now I'd suggest only using the application for smaller files.

> but when scolled the codes, they weren't colorful

This is _kind_ of expected. There is a delay in the syntax highlighting on later parts of the file, but it should show up eventually.

**Comment by dail8859** [comment]
Another thought. Does the file have really long lines?

**Comment by nettnikl** [comment]
Thank you for the detailed answer!
I think i undestand the concept now, to *correctly* display everything we are used to, there is much more to it than i thought. So, i assume, that the only way could be shenanigans to *good enough* assume things, and do magic, e.g. with updating the scrollbar after asynchronously calculating the line length etc. That sound very involved, though.

**Comment by MichaelWU0726** [comment]
> Another thought. Does the file have really long lines?

All the lines in the assembly text are short，but there are too much lines in it. What's more, the problem didn't happen when using old version before.

**Comment by dail8859** [comment]
> What's more, the problem didn't happen when using old version if I didn't remember wrong.

That is very likely. There are features that continue to be added that could potentially cause poor performance. For now my suggestion is not using this app for "large" files.

I think at some point in the future, time will need to be dedicated to benchmarking and optimizing specific areas of the code. If certain features are still causing issues and cannot be optimized, then they may need to reduce functionality or get automatically disabled.

**Comment by dail8859** [comment]
Some notes to myself to look into:

Look into delaying some operations could potentially be called in a very rapid succession. This is normally the case when needing the `UpdateUI` notification. The URLFinder uses a timer to slightly delay text processing: 

https://github.com/dail8859/NotepadNext/blob/5c4bc23dc2d4916abff02cc1a8e3d195e8b7e87d/src/NotepadNext/decorators/URLFinder.cpp#L110-L123

The smart highlighter and highlighted scrollbar are likely sources of performance issues and may benefit from this kind of delayed processing

--- 

Autocompletion is quite slow last time I used a large file...maybe I was just in debug mode.

---

May also need to look into `SCI_SETMODEVENTMASK` to restrict unneeded notifications getting sent from the editors.

**Comment by zufuliu** [comment]
[AD 😉] You can use https://github.com/zufuliu/notepad2 for your large files, there may be performance improvement for large file in Scintilla when SIMD is standardized in C++, so I can backport my SIMD (currently SSS2, AVX2) codes into Scintilla.

@dail8859 I think you can add labels for issues related to Scintilla and Lexilla (e.g. Notepad++ has [scintilla dependent](https://github.com/notepad-plus-plus/notepad-plus-plus/labels/scintilla%20dependent) and [lexilla dependent](https://github.com/notepad-plus-plus/notepad-plus-plus/labels/lexilla%20dependent)).

**Comment by dail8859** [comment]
@zufuliu At this point I have no reason to blame Scintilla for any of the performance issues. There are several features that assume files are relatively small and don't put a limitation on things like smart highlighting, autocompletion, and I'm sure there are ways to optimize the Qt side of my implementations as well.

**Comment by YM14532** [comment]
hope this issue can be solved quikcly, big file review and search is import to me =_=

**Comment by cuixinye** [comment]
I encounter the same issue when I search in a log file with a size of 57M. 
When searching or scrolling , it would hang for a while. When clicking result list to locate to different line, it would hang for a while.
Hope to optimize for large files

**Comment by zhaokeli** [comment]
Open a 3m sql text file, it will freeze when scrolling the scroll wheel, but it will not freeze when the mouse is used to pull the scroll bar, the system is win11 22000.1516,

Compared with notepad++ notepad-- notepad3, the cpu usage is 10%-%20 when scrolling, and only the notepad next scrolls once, and the interface will freeze for a while

**Comment by czlitony** [comment]
@MichaelWU0726 can you please try this [PR](https://github.com/dail8859/NotepadNext/pull/378) to see if there is an improvement?

**Comment by dail8859** [comment]
#378 has been merged which helped improve performance. Closing this for now. As stated before, the application really hasn't been fine tuned for large files. If there (and there will be) issues in the future regarding large file performance it will be best to open another issue.
