### ISSUE TITLE
How to change background color

### ISSUE THREAD

**Issue by xfeng12** [dail8859/NotepadNext#288]
I don't find a menu to change background color, is that a expected kind? If yes, can you consider to add that to support to change background color?
Another one, the function of HEX Dump can just dump the hex of a file content, but can't change by hex. Can you consider to add to support hex editor?
Thanks!

**Comment by dail8859** [comment]
> I don't find a menu to change background color, is that a expected kind?

This functionality doesn't exist yet, but yes it is planned to be added in the future.

> can't change by hex. Can you consider to add to support hex editor?

Yeah I'll take a look and see.

**Comment by inkydragon** [comment]
> This functionality doesn't exist yet

Maybe we could allow users to load their own Qt Style Sheets (QSS), then users can use tools like [hustlei/QssStylesheetEditor](https://github.com/hustlei/QssStylesheetEditor) to customize the styles they want.

https://doc.qt.io/qt-6/stylesheet-examples.html
- read qss file
- `qApp->setStyleSheet(qss_str);`

**Comment by dail8859** [comment]
> Maybe we could allow users to load their own Qt Style Sheets (QSS)

At least for the Widget-based part of the application this does use an [internal qss sheet](https://github.com/dail8859/NotepadNext/blob/master/src/NotepadNext/stylesheets/npp.css) to style a bit of the application. (There's also a way to load a custom qss from command line.)

However, in regard to specifically changing syntax highlighting...this is something thought about a while ago. There would definitely be some benefit of the "cascading" functionality that could be utilized. The difficulty is mapping the lower-level Scintilla styles to actual QObject properties. The QObjects that would describe each language's properties (or contain some sort of mapping) just don't exist.

Scintilla just cares that style 1 has foreground AAA, background BBB, etc. style 2 is foreground CCC, and so on.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/dail8859/NotepadNext/pull/1040
- https://github.com/dail8859/NotepadNext/issues/1029
- https://github.com/dail8859/NotepadNext/issues/930
- https://github.com/dail8859/NotepadNext/issues/720
- https://github.com/dail8859/NotepadNext/issues/553
- https://github.com/dail8859/NotepadNext/pull/411
- https://github.com/dail8859/NotepadNext/issues/407
- https://github.com/dail8859/NotepadNext/issues/288
- https://github.com/dail8859/NotepadNext/issues/171
- ...

**Comment by wzt761106** [comment]
直到2026年还没实现暗黑模式，呵呵呵，不用看了。

**Comment by Leoncl2025** [comment]
> 直到2026年还没实现暗黑模式，呵呵呵，不用看了。

@wzt761106 Would you be interest at this project https://github.com/Leoncl2025/NotepadSharp, which has dark mode

<img width="1245" height="738" alt="Image" src="https://github.com/user-attachments/assets/ba1584e6-10b0-472a-b143-1781980c8c46" />

**Comment by Neustradamus** [comment]
@Leoncl2025: Thanks for your work, I have created a ticket to have binaries/installers of your fork.

Thanks in advance.

**Comment by Leoncl2025** [comment]
Hello, Windows x64 binaries are already available in the v0.15.1 pre-release:
https://github.com/Leoncl2025/NotepadSharp/releases/tag/v0.15.1
It includes both an installer and a portable ZIP.
