### ISSUE TITLE
I can't drag into a folder

### ISSUE THREAD

**Issue by yinjianan** [dail8859/NotepadNext#289]
I can't drag into a folder，When I drag in, I will be prompted to create a file

**Comment by yinjianan** [comment]
mac os , see more in the video

https://user-images.githubusercontent.com/15173467/206116418-1d13896b-cb2f-412c-a51e-5bfb2331c573.mp4

**Comment by dail8859** [comment]
What was the expected behavior? To open all the files in the folder?
