### ISSUE TITLE
Not support Kotlin And Chinese language

### ISSUE THREAD

**Issue by Apeplan** [dail8859/NotepadNext#290]
At present, version 0.5.6 does not support Kotlin language, the software does not support Chinese language, hope to increase

**Comment by dail8859** [comment]
> version 0.5.6 does not support Kotlin language

Implementing Kotin is dependent on the Lexilla project (this is what Notepad Next uses for the syntax highlighting). As far as I know, there is no support for it. Your best option might be to discuss it with the [Lexilla](https://github.com/ScintillaOrg/lexilla) project.

> the software does not support Chinese language

What OS and app format are you using? It may be the same as #155
