### ISSUE TITLE
Create release source code with full source

### ISSUE THREAD

**Issue by dmknght** [dail8859/NotepadNext#293]
Hello! I would like to create a Debian package of NotepadNext and add it to Parrot OS. After reading the Readme, Development instructions and downloaded release source code, I understood that I need to get submodules to build the application from source. However, Debian build standard requires full source code from release file. So it would be very nice if you can create the release source file with full source code of submodules in next release.

**Comment by dail8859** [comment]
> Debian build standard requires full source code from release file.

This sounds rather odd that it would not support git repositories that contain submodules. 

The entire source code can be downloaded with `git clone --recurse-submodules https://github.com/dail8859/NotepadNext.git` so I'm not sure why that isn't sufficient.

**Comment by dmknght** [comment]
> > Debian build standard requires full source code from release file.
> 
> This sounds rather odd that it would not support git repositories that contain submodules.
> 
> The entire source code can be downloaded with `git clone --recurse-submodules https://github.com/dail8859/NotepadNext.git` so I'm not sure why that isn't sufficient.

Hello! The Debian build doesn't clone the repository directly but download the release / tag files to build. I don't really know the full idea behind that, but from what I know, there are 2 major reasons:
1. Distros can have a different git repos that contains released versions and Debian's configurations of the application to build. That means it doesn't have git's configuration of original repository
2. When the builder does its job, the source code of submodule comes with the released source code. So It can avoid conflicts in the source code. Let say that the released version is 1.0, and the main branch is doing the 2.0. So the submodule must work with version 2.0 and it could have error with the old code.

And as i just checked, the release files don't have `.git` folder so it doesn't contain information about submodules.
![image](https://user-images.githubusercontent.com/29118926/210021900-1a9dfbf0-cfab-4aaf-b915-783fc30c76a9.png)

**Comment by dail8859** [comment]
The source code published on the release page is automated by Github and I don't have any control over that. I'm not sure how Debian is configured to point to the releases page or to a specific named artifact.

Manually publishing another artifact of the code seems a bit needless when it (and the submodules) can all be downloaded via `git`. For now I don't really see this of much value unless there's some other justification or need by other projects. If someone wants to submit a PR with a github action that does this and it is very minimal to maintain, I might accept it. But for now I'll close this.
