### ISSUE TITLE
[Feature Request] Revisit #221 - Identify file language by its content

### ISSUE THREAD

**Issue by noabody** [dail8859/NotepadNext#304]
#221 can be applied to other file types.  

Specifically, shell (bash, csh, bsh, sh), perl, and python.  Each of these have an identifiable header, on the first line, which consists of she-bang [#!] followed by the path to the executable e.g., `#!/usr/bin/bash, #!/usr/bin/perl, #!/usr/bin/python3`

With `bash` as an example, we could use this in `src/NotepadNext/languages/bash.lua` but it's problematic:
```bash
L.first_line = {
	"#!/bin/bash",
	"#!/bin/bsh",
	"#!/bin/csh",
	"#!/bin/sh",
}
```
The problem is that the path is variable so we don't really want to explicitly match, but rather, pattern match like so `src/NotepadNext/scripts/init.lua`:
```
if starts_with.find(contents, v) then
```
where v is pattern (respective to language):
```
"^#!.*/(ba|b|c|)sh"
"^#!.*/perl"
"^#!.*/python"
```

That's assuming Lua uses standard regex.  I don't think perl has a variation for `she-bang` but shell and python definitely do.  python is often written with versioning such as `#!.*/python2, #!.*/python3`

**Comment by dail8859** [comment]
#221 was just a start to get the functionality to detect files based on contents, so yes I fully agree there are numerous other languages that could be detected. And having pattern-type of matching would make things even more flexible.

> That's assuming Lua uses standard regex

It has a bit of its own flavor but just as powerful.

**Comment by noabody** [comment]
Thank you for your attention.  A project as excellent, and with as much promise, as this is going to be popular and, therefore, demanding.

As a Linux user, I've stopped using my go-to editor because Notepad-Next "sips" memory, in comparison.  With 4 tabs open, I'm seeing just over 100Mb in use, where it's 1 Gb for the other.  I won't name any names [qq] ;).

**Comment by dail8859** [comment]
Glad to hear it is useful. There's still a lot of functionality missing.

I added in the ability to match by patterns and added a few for languages as you suggested. There are certainly others but now it is easy to update the settings.
