### ISSUE TITLE
No %f in the .desktop file Exec

### ISSUE THREAD

**Issue by pranatahouse** [dail8859/NotepadNext#305]
I installed the AppImage version using AppImageLauncher to automate creating the desktop file on Ubuntu. The problem is that when i choose open with other application to a c++ file for example, NotepadNext is not listed there because it does not have %f to it. So for now i edit the desktop file like this to make it visible on open with dialog.

Exec="/appimage/location/NotepadNext-x86_64_08f43ec222d8caa1af2101d59f80a34f.AppImage" %f

**Comment by elcuco** [comment]
The desktop file used inside an app image, (IMHO) is auto-generated from AppImage builder:

https://github.com/dail8859/NotepadNext/blob/4ddddcbf31ab8d1d37f0719a0242d87496c9d4dc/.github/workflows/build.yml#L55-L65

We need to identify what generates that desktop file? It is our desktop file? Is such case, the fix is here:
https://github.com/dail8859/NotepadNext/blob/4ddddcbf31ab8d1d37f0719a0242d87496c9d4dc/deploy/linux/NotepadNext.desktop#L2

**Comment by dail8859** [comment]
@elcuco Thanks for the PR!

> We need to identify what generates that desktop file? It is our desktop file?

That was my thought as well. I took a look at a few different repos and they all have the `%f` in the exec command in the desktop file. So in the end I think the PR is appropriate, but would still be interested if it fixes the issue with the AppImage.

--- 

@pranatahouse Try this AppImage from the PR @elcuco created: https://github.com/dail8859/NotepadNext/suites/10529939256/artifacts/523291809

**Comment by pranatahouse** [comment]
> @elcuco Thanks for the PR!
> 
> > We need to identify what generates that desktop file? It is our desktop file?
> 
> That was my thought as well. I took a look at a few different repos and they all have the `%f` in the exec command in the desktop file. So in the end I think the PR is appropriate, but would still be interested if it fixes the issue with the AppImage.
> 
> @pranatahouse Try this AppImage from the PR @elcuco created: https://github.com/dail8859/NotepadNext/suites/10529939256/artifacts/523291809

ok i'll try it out.

**Comment by pranatahouse** [comment]
Thank you @dail8859 i've tested the appimage and now it's working fine installed using AppImageLauncher.

**Comment by dail8859** [comment]
@pranatahouse Thanks for testing it out!

@elcuco Thanks for the PR. Will get that merged now.
