### ISSUE TITLE
please add code format function

### ISSUE THREAD

**Issue by silentmissile** [dail8859/NotepadNext#307]
Usually a code file is format and easy to read.

But there are some unusual case. Compressed JSON file is used to save net transfer load. When we open that file, it's really difficult to read.

Could you please add code file format feature? We can read code easier.

Thanx

**Comment by inkydragon** [comment]
It may be better to write a plugin to do this.
Although the plugin system may not exist yet.

xref: https://stackoverflow.com/questions/3635460/formatting-code-in-notepad

**Comment by dail8859** [comment]
I understand the benefit but agree with @inkydragon that something external to the application would be better. Alot of time/effort can get put into implementing language-specific features that only benefit a small subset of users at a time. Currently no plugin capabilities exists.

Ideally there'd be some way to have Notepad Next call an external tool made for (formatting, cleaning, linting, etc) and that would be more flexible to allow users to use whatever tools they prefer.

I'll close this for now, but again I'm not against some sort of external tool integration in the future...it's just a very low priority currently unless someone is interested in implementing it.
