### ISSUE TITLE
2023希望能有的功能，特别想使用这款软件

### ISSUE THREAD

**Issue by hobbymai** [dail8859/NotepadNext#308]
希望可以增加扩展功能，也就是添加扩展插件等。 或者直接右键菜单能支持各种，编解码功能，例如： base64、 url、 等的、编码、解码。

**Comment by mobzila** [comment]
用英文，还有把需求说详细一点，不然开发者可能不会理

**Comment by mobzila** [comment]
用英文，还有把需求说详细一点，不然开发者可能不会理

**Comment by mobzila** [comment]
> 希望可以增加扩展功能，也就是添加扩展插件等。 或者直接右键菜单能支持各种，编解码功能，例如： base64、 url、 等的、编码、解码。

用英文，还有把需求说详细一点，不然开发者可能不会理

**Comment by inkydragon** [comment]
> > 希望可以增加扩展功能，也就是添加扩展插件等。
> > 或者直接右键菜单能支持各种，编解码功能，
> > 例如：base64、url 等的编码、解码。
> 
> I hope to add additional features, i.e. add extension plugins, etc. 
> Or make the right-click menu support various encoding conversion functions: 
> for example, base64 and url.

Open an issue always in English.
Be sure to include a translation when writing in Chinese.

The plugin system may need more time.
I agree that the encoding conversion function is suitable for a plugin.

打开一个 issue 还是要以英文为主。
用中文写务必附上翻译。

插件可能还需要一些时间。
我同意编码转换功能适合于做成插件.

**Comment by dail8859** [comment]
@hobbymai 

> Features that would like to have in 2023

You are welcome to submit pull requests this year :)

> I hope to add additional features, i.e. add extension plugins, etc.

This is a long ways away as there is more core functionality that is worth focusing on at this time.

> base64 and url.

@inkydragon 

> I agree that the encoding conversion function is suitable for a plugin.

At first I thought the same thing. But looking at Qt it supports [base64](https://doc.qt.io/qt-6/qbytearray.html#toBase64) and [url encoding](https://doc.qt.io/qt-6/qurl.html#toPercentEncoding) already. So adding this in may be a quick/easy implementation.

**Comment by msglog** [comment]
Hope "row" add "delete duplicate row"
