### ISSUE TITLE
scroll the page horizontally

### ISSUE THREAD

**Issue by hh-cat** [dail8859/NotepadNext#313]
It is suggested to add a function to scroll the page horizontally by pressing and holding the Shift key to scroll the mouse wheel.

**Comment by dail8859** [comment]
The scrolling behavior is implemented by Scintilla, which is a project that Notepad Next uses.

Your best option would be to either use Scintilla's [bug tracker](https://sourceforge.net/p/scintilla/bugs/) (on SourceForge unfortunately) or discuss it on their [mailing list](https://groups.google.com/g/scintilla-interest). If they implement a fix or option to adjust it then Notepad Next would be able to take advantage of it then.
