### ISSUE TITLE
mac M1 

### ISSUE THREAD

**Issue by GithubGey** [dail8859/NotepadNext#314]
<img width="618" alt="image" src="https://user-images.githubusercontent.com/86140803/215931833-c8cb3c73-b7dd-497b-91fc-11831bb54392.png">

在mac M1 上， 打字中文 英文 字的时候，下面会不停的闪烁白色的框
On the mac M1, when typing Chinese and English characters, the white box will flash continuously below

**Comment by dail8859** [comment]
I'm going to assume this is some sort of IME interaction. Scintilla (the actual text editing part of the app) has support for it I think but I don't know anything about it or how it works.

It is possible but far less likely that it could be the auto-completion, but the box looks oddly placed and a bit transparent for it to be that.

**Comment by czlitony** [comment]
Fix PR: https://github.com/dail8859/NotepadNext/pull/373
