### ISSUE TITLE
Suggestions for cursor behavior

### ISSUE THREAD

**Issue by NichtsHsu** [dail8859/NotepadNext#315]
![image](https://user-images.githubusercontent.com/35688135/215987962-af62704c-f769-4404-ab41-125905c5a934.png)

If I click the area behind the word "at", the cursor stays before the word "android" instead of after the word "at". I konw Notepad++ does the same but it's a little bit counter-intuitive. On the contrary, Windows Notepad and Kate/kwrite stay the cursor after the word "at".

**Comment by dail8859** [comment]
I agree the cursor placement is a bit unintuitive when lines are wrapped (not sure if there is a good reason it does it this way). The low-level text handling and cursor logic is part of the [Scintilla](https://www.scintilla.org/) project (which is what Notepad++ uses) and as far as I know Scintilla doesn't provide any kind of mechanism to control this specific scenario.

Your best option would be to either use Scintilla's [bug tracker](https://sourceforge.net/p/scintilla/bugs/) (on SourceForge unfortunately) or discuss it on their [mailing list](https://groups.google.com/g/scintilla-interest). If they implement a fix or option to adjust it then Notepad Next would be able to take advantage of it then.
