### ISSUE TITLE
如何删除空行 How to remove empty lines？

### ISSUE THREAD

**Issue by PandaFang** [dail8859/NotepadNext#319]
如何删除空行？

 How to remove empty lines？

**Comment by inkydragon** [comment]
- <kbd>Backspace</kbd> ? 😆
- Regex: replace `^\s*$\n` => nothing
- [ ] Add a new plugin, menu item for removing all empty lines

**Comment by PandaFang** [comment]
> * Backspace ? 😆
> * Regex: replace `^\s*$\n` => nothing
> * [ ]  Add a new plugin, menu item for removing all empty lines


删除一两三行我就不来问了
相比插件我还是建议内置，现在不是有个行操作的菜单吗，里面选项太少了。

<img width="362" alt="Snipaste_2023-02-03_20-42-26" src="https://user-images.githubusercontent.com/4337419/216606809-6143d6f2-0f91-4ae0-a668-5e18653e316f.png">


**notepad3 和  隔壁notepad-- 都内置了**
<img width="439" alt="Snipaste_2023-02-03_20-43-14" src="https://user-images.githubusercontent.com/4337419/216606873-e0d271ee-b535-4908-9b83-db0bb15fda45.png">

<img width="389" alt="Snipaste_2023-02-03_20-44-11" src="https://user-images.githubusercontent.com/4337419/216606904-f4f19a65-6d0e-4a9e-ad11-ad30ebad80f8.png">
