### ISSUE TITLE
Qt 6+

### ISSUE THREAD

**Issue by dail8859** [dail8859/NotepadNext#32]
Evaluate Qt 6+ since the open source channel is stuck on 5.15.2

I think most of the external dependencies are Qt 6 compatible but need to actually try it out and see what needs done.

Ideally support but Qt 5.15 _and_ 6+ if possible.

**Comment by hongnod** [comment]
Regex has some build issues

**Comment by dail8859** [comment]
Scintilla will have official Qt6 support in the next release:

https://sourceforge.net/p/scintilla/code/ci/1d7efaa790b28c68fdbc4708d92f9d939e3d454e/
