### ISSUE TITLE
安装后卸载导致我其他软件被删除 不能使用

### ISSUE THREAD

**Issue by zhang-chuanfeng** [dail8859/NotepadNext#320]
安装后卸载软件
我一般软件安装在这个目录下
D:\Software
在安装过程中选择目录是当前目录卸载软件导致其他软件不能使用  有些出现缺少库

你这个软件怎么安装后占用这么大空间  有差不多1.2G  我看notepad++ 才11MB

**Comment by dail8859** [comment]
What operating system are you using?

> The selected directory during the installation process is the current directory. Uninstalling the software causes other software to be unusable. Some libraries are missing.

What other software is affected? What libraries are missing?

> Why does your software take up so much space after installation? It’s almost 1.2G. I see notepad++ is only 11MB.

The installation of Notepad Next v0.6 takes up less than 30MB for me. Can you provide screenshots or details?

**Comment by zhang-chuanfeng** [comment]
windows11
安装过程就耗时很长时间
我已经卸载了  有写不能用软件我都重新装了一遍

**Comment by zhang-chuanfeng** [comment]
我用的有道云note6版本 缺少库 装导版本后升级，再升级到6版本才正常

**Comment by zhang-chuanfeng** [comment]
![image](https://user-images.githubusercontent.com/59160162/216353525-0292a9ab-5005-4600-a5a4-37e09eecf896.png)

**Comment by dail8859** [comment]
> 安装后卸载软件
我一般软件安装在这个目录下
D:\Software

After you install Notepad Next, what is the exact path of the `NotepadNext.exe` file? Are you sure you are installing it to its own directory such as `D:\Software\Notepad Next`?

**Comment by inkydragon** [comment]
我猜这是因为你把 npn 安装到了 `D:\Software` 下，卸载 npn 时就误删了其他程序的文件.
你说的 1.2G 的大小应该是 `D:\Software` 整个目录的大小.

I guess this is because you installed npn under `D:\Software` and deleted the other programs by mistake when you uninstalled npn.
The 1.2G size you mentioned should be the size of the entire `D:\Software` directory.

----

To be on the safe side, we should only delete the files written by our installation process.
ref: https://stackoverflow.com/questions/38207389/uninstall-only-installed-files-nsis

**Comment by zhang-chuanfeng** [comment]
但是安装过程是挺慢的

**Comment by inkydragon** [comment]
> > 但是安装过程是挺慢的
> 
> But the installation process is quite slow.

那我推荐下载 win64.zip 直接解压，这样是最快的。

I recommend downloading win64.zip and extracting it directly, which is the fastest

**Comment by dail8859** [comment]
> 但是安装过程是挺慢的

Please define slow. Do you mean 3 seconds? 3 minutes? 30 minutes?

**Comment by dail8859** [comment]
> To be on the safe side, we should only delete the files written by our installation process

I'm not sure this would solve the root issue. Notepad Next expects to have its own standalone directory. If you install it to a shared directory you still have issues of possibly removing files needed by other applications if the names are the same, e.g. common Qt dlls.

**Comment by inkydragon** [comment]
> I'm not sure this would solve the root issue.

Yes, It may not solve the problem completely, but at least it will reduce the impact of misuse.
Also during installation we can warn the user if the destination folder is not empty.
