### ISSUE TITLE
It version.at my computer doesn't support the latest version.

### ISSUE THREAD

**Issue by xiaotong6666** [dail8859/NotepadNext#322]
![image](https://user-images.githubusercontent.com/110387028/217363931-1107d056-e768-416b-ad31-d9070c93728e.png)
Hello author, when using the latest version of your software, I found that it doesn't work properly on my computer. It seems to be a problem with qt6. I'm not very clear. Switch to qt5 and it will work normally. My system Win8.1

**Comment by dail8859** [comment]
What version of Notepad Next are you using?

v0.6 was recently released and it is the first version to use Qt6. Prior to that Notepad Next used Qt5.

**Comment by xiaotong6666** [comment]
Hello, the screenshot above uses the latest version of v6 (qt6) and cannot be opened normally, but it can work normally with the version before this version (qt5)

**Comment by xiaotong6666** [comment]
the screenshot above uses the latest version of v6 (qt6) and cannot be opened normally, but it can work normally with the version before this version (qt5)

**Comment by elcuco** [comment]
https://www.qt.io/blog/qt6-development-hosts-and-targets  - Windows 10 (and Windows 11) are supported by Qt6. 
According to Wikipedia: https://en.wikipedia.org/wiki/Windows_8 - windows 8 is not supported my Microsoft since 2016.

**Comment by xiaotong6666** [comment]
> https://www.qt.io/blog/qt6-development-hosts-and-targets - Qt6 支持 Windows 10（和 Windows 11）。 根据维基百科：[https](https://en.wikipedia.org/wiki/Windows_8) ://en.wikipedia.org/wiki/Windows_8 - 自 2016 年以来我的 Microsoft 不支持 Win

**Comment by xiaotong6666** [comment]
Well, I understand. Thank you for your answer

**Comment by dail8859** [comment]
As described in the documentation, only Windows 10 and later is supported. Your best option is to use Notepad++.

To be honestly I wasn't considering this when moving to Qt6, however due to the age of Windows 7 and 8, and some of the fixes Qt6 provides, I'm ok with this.

For anyone interested you should still be able to build Notepad Next with Qt5 but it won't be officially supported.
