### ISSUE TITLE
[0.6][column mode] seems to be a mistake

### ISSUE THREAD

**Issue by cooltnt** [dail8859/NotepadNext#324]
![image](https://user-images.githubusercontent.com/41370387/218028884-89ea1ae9-d96a-47ea-8efb-0d156cc3f43f.png)

**Comment by inkydragon** [comment]
Can you give more specific steps for reproduction?
I was not able to reproduce the problem on win + npn v0.6

**Comment by cooltnt** [comment]
1.  add 16 blank row
2. columns edit mode(alt + shift)  to select all rows
3. alt +c

**Comment by inkydragon** [comment]
npp ignores the selection order for multi-line editing.
Depending on the order, npn can have two different fill directions.

In the second step, if you select all rows from top to bottom and the cursor ends up on the last row, then npn ends up with the same result as npp.
![image](https://user-images.githubusercontent.com/5158738/218056095-f2260f45-c149-4055-a25f-1a8923374ca7.png)

**Comment by cooltnt** [comment]
> npp ignores the selection order for multi-line editing. Depending on the order, npn can have two different fill directions.
> 
> In the second step, if you select all rows from top to bottom and the cursor ends up on the last row, then npn ends up with the same result as npp. ![image](https://user-images.githubusercontent.com/5158738/218056095-f2260f45-c149-4055-a25f-1a8923374ca7.png)

I get it . 
The cursor should be on the first line, so it will be in reverse order.
Thank you very much!

**Comment by dail8859** [comment]
> Depending on the order, npn can have two different fill directions.

Interesting. Not saying this is intentional but could be a more flexible way of using it. I'll leave the current behavior for now. If it starts to cause more confusion, then maybe enforcing a top-to-bottom ordering would give more expected results to users.

**Comment by cooltnt** [comment]
> > Depending on the order, npn can have two different fill directions.
> 
> Interesting. Not saying this is intentional but could be a more flexible way of using it. I'll leave the current behavior for now. If it starts to cause more confusion, then maybe enforcing a top-to-bottom ordering would give more expected results to users.

it's good, please keep it
