### ISSUE TITLE
Multi-screen with pop-up windows

### ISSUE THREAD

**Issue by inkydragon** [dail8859/NotepadNext#325]
When you have more than two screens, open npn in one of them, then drag npn to the other screens.
Press ctrl+f to find, and the find window will still appear on the screen where the npn is open.

**Comment by dail8859** [comment]
This is what I'm seeing, can you confirm?

1. Open Notepad Next
2. Open the Find dialog - Dialog appears in the middle of the application window
3. Close the Find dialog
4. Move the main application window
5. Open the Find dialog - Dialog appears in the _previous_ location, but should show up again in the middle of the application window.

**Comment by inkydragon** [comment]
> can you confirm?

Yes, that's it.
All popups should be as close to npn as possible.

**Comment by dail8859** [comment]
The more I think about this the more I'm not sure anything needs changed.

I agree the *first* time the dialog is shown it should be opened as close (i.e. in the center) of the main application window. However, if the user moves it then that is where they "want it" when should it be automatically moved for them? Every time it is opened? Only when the main window is moved to a different screen?

I recently noticed myself using NN on one half of my screen and keeping the find dialog on the other half (to not overlap). I could possibly forsee someone moving it to a different screen for a similar use case.

Notepad++ by default will keep it wherever the user placed it. The only thing I can tell that it has that Notepad Next does not, is if you press `Ctrl+F` again with the Find dialog open, then it will recenter it.

**Comment by informatorius** [comment]
Maybe it could be a config option for the user if dialogs should follow main app window when moved to other screen?
