### ISSUE TITLE
Hope to add Traditional Chinese

### ISSUE THREAD

**Issue by seq2193** [dail8859/NotepadNext#326]
Thanks!

**Comment by dail8859** [comment]
There is some form of Chinese available but I'm not sure if it is traditional or simplified. If there is a different translation that you'd like to see you are welcome to [contribute a new translation](https://github.com/dail8859/NotepadNext/blob/master/doc/Translation.md).

![image](https://user-images.githubusercontent.com/3694843/218278544-996ec91b-949a-4709-b29d-4e6e0744d7ba.png)

**Comment by bestbai** [comment]
Need fans to work together. who use traditional Chinese know traditional Chinese best .
