### ISSUE TITLE
性能如何提升？ how to improve speed of viewing 

### ISSUE THREAD

**Issue by lif1234567892** [dail8859/NotepadNext#333]
compared with Notpad++， on large text file Notepad Next offten be slow， appears on 100MB up Log File ，
click one line became slow ，scrolling view became slow

总体体验不如Notepad++ ，希望继续优化，加油~~

**Comment by dail8859** [comment]
For now, I would recommend staying with Notepad++ for large files. Notepad Next just has not been benchmarked, fine-tuned, or optimized to handle large files.

 Closing as a duplicate of #284
