### ISSUE TITLE
[Feature Request] Shift Mouse-Scroll for Horizontal Scroll

### ISSUE THREAD

**Issue by Areopagitics** [dail8859/NotepadNext#339]
Shift Mouse-Scroll for Horizontal Scroll at least doesn't work on Linux; so this would be a nice feature to have.

**Comment by dail8859** [comment]
See https://github.com/dail8859/NotepadNext/issues/313#issuecomment-1412628035

The underlying Scintilla library would have to implement this feature.

**Comment by Areopagitics** [comment]
Good to know! I've been using SciTe and have been looking for this feature as well.

**Comment by dail8859** [comment]
There's a specific spot in the Qt platform layer that handles scrolling. I took a look at it briefly at one time but didn't pursue changes, testing, etc. But still should be possible on the Scintilla side.

**Comment by Areopagitics** [comment]
The latest Scintilla has this feature Version 5.3.4, since last year. The Debian repo is still at 4.4.5-2...just a matter of updating.

See here https://groups.google.com/g/scintilla-interest/c/liR78w3UQLA
