### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by hongnod** [dail8859/NotepadNext#34]
Nice to see this editor, 
1、“Find in files” has a menu item, but can't open the operational panel
2、Encoding is not started
3、Golang  is not supported.

**Comment by dail8859** [comment]
Hi @hongnod,

Yes there is alot of missing functionality. This is really just a fun side project for me and my interest comes and goes. I have no 'roadmap' or plan. Just as something interests me I start hacking on it.

Ideally I'd like to duplicate alot of the functionality of Notepad++ however that doesn't always mean completely copy the behavior. I think there is alot of room for improvement if the code is clean and structured.

So yes I agree these are needed features...but as to when they will happen I do not know. I am of course always open to people willing to contribute :)

**Comment by dail8859** [comment]
For a bit easier tracking I'll close this issue and open 3 separate issues as the level of effort of each one varies greatly and would be easier for people to discuss.
