### ISSUE TITLE
有没有接管txt记事本的功能？

### ISSUE THREAD

**Issue by BrunuhVille** [dail8859/NotepadNext#340]
请教大佬

之前使用的notepad3，可以设置打开txt/打开记事本 会自动变成notepad。但是它没有多标签页的功能，所以放弃了

想问下NotepadNext有没有类似的功能，可以直接覆盖掉txt/记事本

**Comment by inkydragon** [comment]
> 有没有接管txt记事本的功能？
> Can NotepadNext directly replace notepad?
> 
> 之前使用的notepad3，可以设置打开txt/打开记事本 会自动变成notepad。
> I previously used notepad3, which can be set as the default software for opening txt files. (Replaced the default notepad)
> 但是它没有多标签页的功能，所以放弃了.
> But it doesn't support the multi-tab feature, so I gave up.

see #29.
You may need to import a regfile.

**Comment by dail8859** [comment]
@BrunuhVille

Depending what you need you might need to modify the regex as @inkydragon suggested.

If you are looking to just register file extensions then you should just use the built in "Open With..." menu and use the OS to register the application for that desired extension.

![image](https://user-images.githubusercontent.com/3694843/224568310-85254cf8-512c-4440-a0e7-a913609a2f9c.png)
