### ISSUE TITLE
可以选择字体吗

### ISSUE THREAD

**Issue by BrunuhVille** [dail8859/NotepadNext#341]
请教大佬

NotepadNext可以设置选择不同的字体吗  （比如微软雅黑）

我尝试找了一下，好像没有找到这个功能

**Comment by inkydragon** [comment]
> 可以选择字体吗
> (Does this software) allow you to choose fonts?
> 
> NotepadNext可以设置选择不同的字体吗 （比如微软雅黑）
> Can NotepadNext use different fonts (e.g. Microsoft YaHei)

Not yet.

If you really want to change it, you can use the lua script. (#331)

**Comment by dail8859** [comment]
Currently there's no way to set the font. Those kinds of features are planned but not currently implemented.
