### ISSUE TITLE
There are horizontal and vertical lines in the background

### ISSUE THREAD

**Issue by chguw** [dail8859/NotepadNext#344]
Notepad Next version: 0.6
System version: Windows 10 Pro 22H2

There are horizontal and vertical lines in the background, as shown in the picture:

![2023-03-17_090232](https://user-images.githubusercontent.com/6346659/225785860-895c3b2b-93f6-4947-a1ff-389a02a6821f.png)

**Comment by dail8859** [comment]
That is very odd. Do the lines change if you do something like zoom? Or possibly change your screen resolution or scaling factor?

The Scintilla library is used for the editing component (text rendering, drawing, etc) so most likely the bug is in that library. My guess would be due to some sort of sub pixel scaling calcuations, but that's just a guess..

**Comment by chguw** [comment]
Maybe your guess is correct, these lines disappear when I change the screen scaling factor from 125% to 100%.

**Comment by chguw** [comment]
When I use the version you provided, these horizontal and vertical lines disappear, regardless of the system scaling factor is 125% or 100%.

![2023-03-17_200823](https://user-images.githubusercontent.com/6346659/225900917-49293f51-663f-42cc-8c81-4934365b5e0e.png)

**Comment by nyamatongwe** [comment]
> Have you seen any reports with Qt6 and Scintilla (v5.3.2) with this kind of pixel scaling issues?

No previous reports.

Scintilla mostly treats the window as a set of non-overlapping whole-pixel lines. When the underlying GUI library or OS is scaling, this may be incorrect.

Say you have a window that is being scaled by the system by 1.25x (5/4) in a way that tells Scintilla that the window is 0.8x (4/5) its real size and every position in every graphics call Scintilla makes is multiplied by 1.25. Scintilla ask for the font height and receives 10 logical pixels (12.5 screen pixels) so it sets its line height to 10.

Then it draws document lines, o = (0, 0, 10, width) (top, left, bottom, right); 1=(10, 0, 20, width). These are drawn, after multiplication by 1.25 as physical screen pixels (0, 0, 12.5, width); (12.5, 0, 25, width). There is a screen pixel (y=12) shared between lines 0 and 1. When filling the lines with background, the fill call may anti-alias the edge between the lines which, in this case, will draw the background colour at half intensity over the current window contents for line 0, then again for line 1 leaving a quarter of the original pixel value intact.

It is better to use a different scaling mechanism where Scintilla is again dealing in physical pixels. On Windows, define the application (through API or manifest) to be DPI-aware. There may also need to be Qt calls to handle DPI-awareness.

Filling the window with background colour in the Qt platform layer before calling Editor::Paint may minimize visual effects in many cases but it will still show some edge effects when using various features. styles[Default(32)].back is likely the best colour to use.

**Comment by dail8859** [comment]
Closing as this appears to be a Qt6 or Scintilla issue and nothing obvious that Notepad Next can do to address it.
