### ISSUE TITLE
open with error

### ISSUE THREAD

**Issue by bwxz** [dail8859/NotepadNext#346]
@V0.6：
![image](https://user-images.githubusercontent.com/16777578/225857421-6a85b0f8-3746-4e06-bb14-4234e65aebcd.png)

@V0.5.4  and V0.5.6 is ok

**Comment by inkydragon** [comment]
Which system? win7?

**Comment by elcuco** [comment]
Windows 7 is not supported. V0.6 releases started using Qt6 which are more modern, and have better support for highDPI  systems. 

(Qt5 still compiles... I wonder how hard will it be to support both versions?)

**Comment by bwxz** [comment]
> Which system? win7?

yes,win7-64

**Comment by bwxz** [comment]
> Windows 7 is not supported. V0.6 releases started using Qt6 which are more modern, and have better support for highDPI systems.
> 
> (Qt5 still compiles... I wonder how hard will it be to support both versions?)

yeah,many company and labs has old pc for long test work，still use os-xp,win7. so,Personality，it‘s better to support  these  workspace

**Comment by dail8859** [comment]
> (Qt5 still compiles... I wonder how hard will it be to support both versions?)

The plan is for now to keep Qt5 support for anyone that wants to build it themselves, but if/when maintaining Qt5 support starts to be burdensome it will be dropped. Official releases will just be Qt6.

> yeah,many company and labs has old pc for long test work，still use os-xp,win7. so,Personality，it‘s better to support these workspace

When you are stuck with legacy operating systems you should expect to be stuck with legacy tools as well. You are welcome to build and/or distribute your own version of Notepad Next for these systems. Though I myself will not be addressing any Qt5 specific bugs...PRs are always welcome as long as things do not get messy or cumbersome.
