### ISSUE TITLE
Add CMakeLists.txt

### ISSUE THREAD

**Issue by hgntn** [dail8859/NotepadNext#349]
Other Qt based editors also switched to cmake based build system, e.g:

https://github.com/tsujan/FeatherPad

https://github.com/psemiletov/tea-qt

**Comment by inkydragon** [comment]
See #100

**Comment by dail8859** [comment]
@hgntn qmake was the build system of choice when I started this long ago. I know cmake is the preferred option for Qt now and would like to see it implemented at some point. I do not know how to use cmake myself, but as @inkydragon mentioned #100 is working being done by a contributor to add cmake support. Would love any help you can offer there!
