### ISSUE TITLE
Support building with CopperSpice?

### ISSUE THREAD

**Issue by ghost** [dail8859/NotepadNext#350]
CopperSpice is a Qt fork which removed the moc: https://www.copperspice.com/

**Comment by ZachBacon** [comment]
I don't really see this happening, there's been many changes since copperspice split off from qt. But then again I'm not the project developer here. But I'm saying this just from my own experiences in dealing with qt and copperspice.

**Comment by dail8859** [comment]
@hgntn I don't know anything about CopperSpice. Could you provide some background as to why you think it is a good idea? Are you implying Qt's moc is bad?

**Comment by ZachBacon** [comment]
> @hgntn I don't know anything about CopperSpice. Could you provide some background as to why you think it is a good idea? Are you implying Qt's moc is bad? Is it a drop in replacement to Qt?

If I recall, it's a fork of qt4 from when around qt5 was announced. A fork from when the copperspice team disagreed with a lot of the fundamentals of qt5

**Comment by dail8859** [comment]
After doing a bit of brief searching CopperSpice does not seem to bring any benefits. It also seems much less supported, lacking good documentation, and a much smaller user base.

It would also seem to require massive code changes for no gain.

**Comment by dail8859** [comment]
Gotta love people opening issues then deleting accounts.
