### ISSUE TITLE
请问哪个版本会增加json格式化功能、2个本文compare功能？

### ISSUE THREAD

**Issue by dpf371** [dail8859/NotepadNext#359]

**Comment by dail8859** [comment]
Google Translate:

> May I ask which version will add the json formatting function and the two article compare functions?

JSON formatting is not planned currently. For this kind of specific functionality, I think it would make more sense to rely on external tools.

Comparing files, although useful, is quite alot of work to get it functioning properly, so not something I'll be working on myself any time soon. If someone else was interested in contributing a clean implementation of it I'd be willing to consider it.
