### ISSUE TITLE
File with conf suffix cannot recognize the format

### ISSUE THREAD

**Issue by joyanhui** [dail8859/NotepadNext#365]
例如 ini格式的 conf  
nginx的conf 

都无法识别！

**Comment by dail8859** [comment]
Can you provide an example file?

What is the exact name of the files? Do they just have to be named with the `.conf` extension?

**Comment by joyanhui** [comment]
> Can you provide an example file?
> 
> What is the exact name of the files? Do they just have to be named with the `.conf` extension?


Notepad++ can recognize that the following three files are in ini format or other formats, and automatically highlight the code.
No need to manually select the file format type。

But notepadnext can't automatically recognize the file format。

ini
```shell

echo "[test]">example && echo "isok=ok">>example 
echo "[test]">example.conf && echo "isok=ok">>example.conf 
echo "[test]">example.ini && echo "isok=ok">>example.ini 
```

conf
```shell
cat > nginx-example.conf << EOF
user  nobody;
worker_processes  1;
events {
    worker_connections  1024;
}
EOF
```

**Comment by dail8859** [comment]
Files ending in `ini` will be styled in the INI format.

Files ending in `config` are not a recognized file type (currently at least). 

The example `nginx-example.conf` you showed is not in an INI format though...maybe I'm confusing something?

**Comment by joyanhui** [comment]
> Files ending in `ini` will be styled in the INI format.
> 
> Files ending in `config` are not a recognized file type (currently at least).
> 
> The example `nginx-example.conf` you showed is not in an INI format though...maybe I'm confusing something?

Many configuration files do not have a suffix, or the suffix is `.conf` or other suffixes.
Both notepad++ and notepad2/3 can highlight the content of these files.
Some conf files are in ini format, some are in json format, and some are in their own unique format. There are also configuration filenames that don't have a suffix.
Both notepad++ and notepad2/notepad3 can highlight the content of these files. They will work according to the content of the file when it encounters a file without a suffix or a `.conf` file. notepadnext can not.

This is what I expect notepadnext to change.

**Comment by dail8859** [comment]
> Some conf files are in ini format, some are in json format, and some are in their own unique format. There are also configuration filenames that don't have a suffix.

Oh gotcha. So the intent would be if it not a recognized file extension (or no extension) then it tries to guess at the file type. For example if the file starts with something like:

`[(\w)+]` it would be an INI file.

And if it just starts with `{` it might be JSON.

There's already built in support for some languages such as bash:

https://github.com/dail8859/NotepadNext/blob/5b5f819e7ec5c9c6235d634488a85910b7ed1a88/src/NotepadNext/languages/bash.lua#L7-L13

So should be pretty easy to add in some other checks for INI and JSON. As for the actual `nginx-example.conf` I'm not sure lexilla can handle this, but maybe it is some flavor of a language that can be used. Something I'll have to look into more.
