### ISSUE TITLE
keywords are not highlighted - collapse plus/minus sign missing

### ISSUE THREAD

**Issue by nikto1** [dail8859/NotepadNext#369]
1) For most programming languages the keywords are not highlighted, they stay in the same color.
e.g. for php:
![screen1](https://user-images.githubusercontent.com/9814101/235259864-891fe0eb-c82a-4e27-a07e-79a8280ab9d9.png)

2) For most programming languages the collapse function on the left side is missing. If you switch to C++ or JS it's there but for others not. See screenshot below:
![screen2](https://user-images.githubusercontent.com/9814101/235259891-e16180e9-ca2b-4742-b1c6-58838cc98b79.png)

Is it possible to implement the syntax highlighting + the collapse function for the most common programming languages in the next versions?

**Comment by dail8859** [comment]
Hi. Thanks for the report. PHP is a tough one because it's technically treated an embedded language of an HTML file. Most other languages work fine. I use C±± and Python heavily.

Still something that needs fixed for sure. Will take a look.
