### ISSUE TITLE
No response when scrolling up and down

### ISSUE THREAD

**Issue by czlitony** [dail8859/NotepadNext#374]
## Problem
Opening a 50MB text file with Notepad Next, scrolling down and up, Notepad Next will become no response. Mac behaves much worse than Windows in this scenario.

## Analysis
From Mac sample, this problem is caused by `URLFinder::findURLs`. The problem can't be reproduced when `URLFinder` is disabled, so it's sure the issue is caused by `URLFinder::findURLs`. 
Mac sample:
<img width="1792" alt="image" src="https://github.com/dail8859/NotepadNext/assets/20141496/9faef90b-030c-4d45-9023-bd4686d07fb6">
[Sample of Notepad Next.txt](https://github.com/dail8859/NotepadNext/files/11441853/Sample.of.Notepad.Next.txt)

In `URLFinder::findURLs` there is a while-loop that is heavy. if `URLFinder::findURLs` is called frequently, then it will cause the no repsonse issue.
<img width="791" alt="image" src="https://github.com/dail8859/NotepadNext/assets/20141496/3c88afd2-e815-4f43-8a15-9838d1e59ca0">

## Comment
This issue is easy to reproduce on my Mac and Windows machines. Since scrolling down/up is the basic function, it's worth spending time to fix it with high priority.

**Comment by czlitony** [comment]
Root cause is in 
```
    while(linesLeftToProcess >= 0 && currentLine < editor->lineCount()) {
        // Should only happen if the line is hidden
        if (!editor->lineVisible(currentLine)) {
            currentLine++;
            continue;
        }
```
When scrolling, many visible lines will become invisible, so the while loop will be executed many times.

**Comment by czlitony** [comment]
I have not found a way to fix this issue perfectly. I'd like to remove the logic:
https://github.com/dail8859/NotepadNext/blob/cedeff71cdf171e3f70041df181039ad369df43d/src/NotepadNext/decorators/URLFinder.cpp#L113

@dail8859 what do you think of this change?

**Comment by czlitony** [comment]
Disabling the Scintilla::Update::VScroll handling logic will make the URLFinder doesn't work normally for even small text files. I'll make a further investigation to fix this issue.

**Comment by dail8859** [comment]
The intent is to just look at the text that is visible on the screen. After scrolling it would then "reprocess" the text in the screen. Since scroll events can happen in rapid succession, that's why I tried out delaying it a bit with a timer.

A guess may be poor performance with regex searching.

**Comment by czlitony** [comment]
Seems Scintilla runs the regex search too slowly, I have found a way to avoid this issue, pr https://github.com/dail8859/NotepadNext/pull/377
