### ISSUE TITLE
Automatic recognition of more formats for content without file extensions

### ISSUE THREAD

**Issue by joyanhui** [dail8859/NotepadNext#375]
https://github.com/dail8859/NotepadNext/commit/f7062bfa88984e63f5b89f13a1688bda9f21cdad

I saw this commit, maybe more automatic recognition of formats is needed or  default code highlighting format

> Notepad++ does not automatically recognize all text formats, except notepad2/3

some examples

```base
cat > ~/.config/i3/config << \EOF
set $mod Mod4
font pango:JetBrains Mono NL Italic 8 
exec_always --no-startup-id compton
exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
#exec --no-startup-id nm-applet
exec --no-startup-id fcitx5 
EOF
```
.bashrc   .zshrc  .wget-hsts  .xinitrc  .zsh_history  
```
cat > ~/.bashrc<< \EOF
# If not running interactively, don't do anything
[[ $- != *i* ]] && return
alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '
zsh
EOF
```

or

```
cat > ~/..xorgxrdp.10.log<< \EOF
[153235.963] (**) |   |-->Device "Video Card (xrdpdev)"
[153235.963] (**) |-->Input Device "xrdpMouse"
[153235.963] (**) |-->Input Device "xrdpKeyboard"
[153235.963] (**) Option "DontVTSwitch" "on"
[153235.963] (**) Option "AutoAddDevices" "off"
[153235.963] (**) Not automatically adding devices
[153235.963] (==) Automatically enabling devices
[153235.963] (==) Automatically adding GPU devices
[153235.963] (==) Automatically binding GPU devices
EOF
```

**Comment by dail8859** [comment]
There's some very basic functionality to try to detect the file's language based on the first line of the file. For example bash checks for a few possible scenarios:

https://github.com/dail8859/NotepadNext/blob/cedeff71cdf171e3f70041df181039ad369df43d/src/NotepadNext/languages/bash.lua#L7-L13

There's also extensions that can be checked:

https://github.com/dail8859/NotepadNext/blob/cedeff71cdf171e3f70041df181039ad369df43d/src/NotepadNext/languages/bash.lua#L15-L23

If there is some widely used extensions, or non-generic first line syntax then I'm fine accepting a pull request.

> cat > ~/..xorgxrdp.10.log<< \EOF

That doesn't look like a language that Notepad Next would be able to handle.
