### ISSUE TITLE
Please include release number in Linux and MacOS binaries 

### ISSUE THREAD

**Issue by wayne-zhang** [dail8859/NotepadNext#376]
Notepad next binaries for Linux and MacOS has no release number, please add release number to the binary packages generated for Linux and MacOS, same as Window:

Linux:
NotepadNext-x86_64.AppImage  to  NotepadNext-vx.y.z-x86_64.AppImage 

MacOS
NotepadNext.dmg to NotepadNext-vx.y.z.dmg

**Comment by dail8859** [comment]
I'm perfectly fine adding in a version number into the file names. I'm assuming it wouldn't have any negative impact, such as the operating system or script looking for a specific file name so that it 'updates' it rather than replaces it.
