### ISSUE TITLE
How to build from source on MSYS2 MINGW64?

### ISSUE THREAD

**Issue by iahung** [dail8859/NotepadNext#383]
You switched to Qt6 and Qt6 dropped support for Windows 7 and Windows 8.1. I will have to build it from source to use it.

**Comment by dail8859** [comment]
I'm not sure how to build it using Mingw-w64. I'm assuming it is possible with some minor modifications. This repo doesn't (and probably won't ever) _officially_ support it but if someone wants to investigate and add it that's fine, but I won't be able to help out or maintain it at all.

Notepad Next with Qt5.15 is not officially released but they still are being built as an artifact and are usable as far as I know. Qt5.15 support will be kept as long as it does not become a maintenance burden.
