### ISSUE TITLE
mac 下载dmg 打开提示 无法打开“NotepadNext.app”，因为无法验证开发者。

### ISSUE THREAD

**Issue by zhangrlhaha** [dail8859/NotepadNext#384]
mac  m1 ，这种情况怎么办

**Comment by dail8859** [comment]
I won't be much help since I don't use Mac.

See #143 since it is a similar issue but was fixed by the user somehow. There may be some way on your system to disable verifying the developer.

**Comment by wayne-zhang** [comment]
@zhangrlhaha MacOS should be able to accept an exception (of without developer certificates), see Apple support document: https://support.apple.com/en-au/guide/mac-help/mh40616/mac

Basically, open Finder > select NotePadNext.app > right click mouse > select Open. (打开文件浏览器，选择执行文件，点击鼠标右键，选择打开）

**Comment by wayne-zhang** [comment]
But the best solution is apply an Apple development account and generate development certificate and include it in NotepadNext MacOS binary artifact. I am not sure if open Apple development account is free or have to pay, possible the latter.

**Comment by wayne-zhang** [comment]
It seems development account fee can be waived by Apple for nonprofit organizations, that's a good news:

https://developer.apple.com/support/membership-fee-waiver/

**Comment by dail8859** [comment]
I understand it's an annoyance but the issue doesn't seem wide spread. Not sure if it's an OS security setting or what.

I'm not sure what all it would involve or if it would require a Mac which I don't have. I'd also have no way to test or debug it. I'll close this for now and will reevaluate possibly at some later point.

**Comment by wayne-zhang** [comment]
> I understand it's an annoyance but the issue doesn't seem wide spread. Not sure if it's an OS security setting or what.
> 
> I'm not sure what all it would involve or if it would require a Mac which I don't have. I'd also have no way to test or debug it. I'll close this for now and will reevaluate possibly at some later point.

There is a workaround in MacOS to ignore this developer/issuer verification issue, it's not a show stopper. To fix it completely an Apple developer account should be created.
