### ISSUE TITLE
[Feature Request] Custom Indentation

### ISSUE THREAD

**Issue by 2000jedi** [dail8859/NotepadNext#392]
I would really appreciate if it could allow changing indentation with tab / spaces, and the # of spaces for one indentation level

**Comment by dail8859** [comment]
Currently there's no easy way to set it. Notepad Next does support [EditorConfig](https://editorconfig.org/), but I understand this is probably overkill for someone that just wants a simple way to adjust it.

**Comment by 2000jedi** [comment]
> Currently there's no easy way to set it. Notepad Next does support [EditorConfig](https://editorconfig.org/), but I understand this is probably overkill for someone that just wants a simple way to adjust it.

Where should I place this EditorConfig file? Is it under the user home directory? @dail8859

**Comment by dail8859** [comment]
@2000jedi In the same folder (or a parent folder) of the file being edited.

From the EditorConfig website:

> Where are these files stored?
> When opening a file, EditorConfig plugins look for a file named .editorconfig in the directory of the opened file and in every parent directory. A search for .editorconfig files will stop if the root filepath is reached or an EditorConfig file with root=true is found.

**Comment by 2000jedi** [comment]
> @2000jedi In the same folder (or a parent folder) of the file being edited.
> 
> From the EditorConfig website:
> 
> > Where are these files stored?
> > When opening a file, EditorConfig plugins look for a file named .editorconfig in the directory of the opened file and in every parent directory. A search for .editorconfig files will stop if the root filepath is reached or an EditorConfig file with root=true is found.

Thank you. I believe my question has been solved. It is working perfectly.
