### ISSUE TITLE
feature: customized font setting

### ISSUE THREAD

**Issue by creatxrgithub** [dail8859/NotepadNext#398]
I'd like to specify the default font for the editor.

thanks.

**Comment by ZhuangJiayu** [comment]
+1

**Comment by xenkuo** [comment]
This could be the second priority feature in my heart, the first is auto cache unsaved file, which has already been implemented.
Actually, to welcome this feature, I have prepared a private combo font: cascadia mono + dream han sans.

**Comment by ZhuangJiayu** [comment]
If the text is in English or American, the font will not be a problem. However, if it is a CJK font, the default font will have display problems, so I think this is an urgent and important feature.

**Comment by lededev** [comment]
The font is still hard-coded. If you need to set the font, you can modify the source code and compile it yourself. For example, I changed the font to a custom font that I compiled myself.
![image](https://github.com/dail8859/NotepadNext/assets/30518126/ebd26925-26cf-4f96-aa96-79e6a35c142a)
modify to above code, and I got this
![image](https://github.com/dail8859/NotepadNext/assets/30518126/14af6223-92a4-4d2e-b288-9cce44c422f0)

**Comment by fishnet37222** [comment]
If this is implemented, it should respect the default monospaced font specified by the desktop environment.

**Comment by mikae1** [comment]
> The font is still hard-coded. If you need to set the font, you can modify the source code and compile it yourself.

May I ask if what’s the reason for this? Is it a design decision or a matter of time constraints?
