### ISSUE TITLE
Preserve file permission set

### ISSUE THREAD

**Issue by 2000jedi** [dail8859/NotepadNext#399]
When I modify a file in the WSL directory, the permission bits are overwritten. For example, the execution bit will be cleared.

**Comment by dail8859** [comment]
Does any other Qt-based application have this problem? Not sure if it is a Notepad Next issue or a Qt issue.

**Comment by dail8859** [comment]
Can you try this? It _may_ fix your issue. You'll probably have to double unzip it. It is completely stand alone so it will not interfere with your current install:

https://github.com/dail8859/NotepadNext/suites/16557523872/artifacts/945800427

**Comment by dail8859** [comment]
No response.
