### ISSUE TITLE
support hongkong simpile font

### ISSUE THREAD

**Issue by newyorkthink** [dail8859/NotepadNext#413]

**Comment by dail8859** [comment]
Can you provide more details?

I am not familiar with that font. Are you just wanting to use it in the application or is there other additional support needed?

**Comment by newyorkthink** [comment]
i suggest like win10
![image](https://github.com/dail8859/NotepadNext/assets/87791643/a7a2eebb-b6a3-468b-8a7f-27ec3dbbccd0)

not select china landload
use hongkong

hongkong have two china language

HONGKONG simplified Chinese AND HONGKONG Traditional Chinese

**Comment by newyorkthink** [comment]
> Can you provide more details? 你能提供更多细节吗？
> 
> I am not familiar with that font. Are you just wanting to use it in the application or is there other additional support needed?我不熟悉这种字体。您只是想在应用程序中使用它还是需要其他其他支持？

i mean is the notepadnext gui (apparence) use chinese

**Comment by ZachBacon** [comment]
So you want a translation then?
