### ISSUE TITLE
Tab's text/title should not be elided when lots of tabs/files opened

### ISSUE THREAD

**Issue by wayne-zhang** [dail8859/NotepadNext#417]
Icon on the editor tabs should be small. When lots of files opened, file name shown in the tab has been truncated, current icon is too big and let the text to shown is even fewer.

Suggest use smaller icons to let more room to show text/file name.

![image](https://github.com/dail8859/NotepadNext/assets/3071035/7a32761d-7fff-4315-bf5e-9d1230b14717)

**Comment by wayne-zhang** [comment]
To compare, the following is Notepad++ icon on editor tabs:
![image](https://github.com/dail8859/NotepadNext/assets/3071035/9bde8d7d-93ed-4d41-b5c8-183874deac4d)

**Comment by dail8859** [comment]
Smaller might help a bit...but ultimately it will run into some limit and saving a few pixels on each tab might allow for maybe another tab or two to be shown. Not a huge benefit.

The icons also appear to have some padding/margins as part of the [Advanced Docking System](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System) that Notepad Next uses. There may be some opportunity there to tweak it as well.

**Comment by wayne-zhang** [comment]
Another option is let tab support/show more chars (change width?). I know file can have very long name (and long path names possibly included too), understand a chars/px limit is required; but show full file name that short than the limit is a good option. Notepad++ done well, should do the same/similar in NotepadNext I think.

File names (on the tab) is quite important information (for switch files/tabs for example), it has to use the tabs/files drop down now (instead of click tab bar).

**Comment by wayne-zhang** [comment]
Similar usability issue for Notepad++ https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8068

Seems tweak of npp.css can resolve this issue, by change tabCloseButton and Icon margin/border.

**Comment by dail8859** [comment]
Totally agree it can be improved, I just haven't looked into the ADS library to see if there is some easy option exposed or if it requires changes in the library itself.

**Comment by wayne-zhang** [comment]
I have check ads release notes and code (DockWidgetTab.cpp), it's possible to make icons small (both file and close icon) but it couldn't show more text/title as the space between them ([file icon] SPACE [title]SAPACE [close icon]) are hard coded and couldn't be changed by CSS.

This CSS can set icon size to 8x8 px:

ads--CDockWidgetTab {
    qproperty-iconSize: 8px 8px;
}

I haven't found which code/configuration make editor tab title/filename be truncated when lots of files/tabs opened; If can turn off it (and show fewer tabs) and let full file names to be displayed, it would be better than current.

**Comment by wayne-zhang** [comment]
I did some test to make tab fixed size (don't elide text automatically) and it seems improves usability. See the screenshot:
![image](https://github.com/dail8859/NotepadNext/assets/3071035/ad3655b5-c914-4504-b9e6-1f68c5d7783a)

Do you think it can be implemented? I think an option/configuration "Don't elide text on tabs" should be added to make this behaviour configurable.

**Comment by wayne-zhang** [comment]
Also, if I commit this change, do you think a new branch/pull request should be created or added it to the dark mode PR?

**Comment by dail8859** [comment]
> I think an option/configuration "Don't elide text on tabs"

I don't think currently there needs to be an option. It would be _very_ rare for someone to want it to behave like that. An option can always be added later if there are more users wanting it.

> Also, if I commit this change, do you think a new branch/pull request should be created or added it to the dark mode PR?

A new PR would be best.

**Comment by wayne-zhang** [comment]
OK, will do it on a separate PR/branch, it's a small change.

**Comment by wayne-zhang** [comment]
Pushed and PR #419 created.

Fix tab's title/text elided when lots of files/tabs opened #419
