### ISSUE TITLE
error OS2

### ISSUE THREAD

**Issue by TeLLie** [dail8859/NotepadNext#42]
Hello
I tried to build it for OS/2
Using Qt 5.15.2 and gcc 9.2.0

I get a error running make

g++ -c -Zomf -march=i686 -O2 -mno-avx -std=gnu++1z -Wall -Wextra -DQT_NO_IPV6 -DAPP_VERSION="\"0.4.2\"" -DAPP_COPYRIGHT="\"Copyright 2019-2021 Justin Dailey\"" -DSCI_OWNREGEX -DADS_STATIC -DQAPPLICATION_CLASS=QApplication -DSCINTILLA_QT=1 -DMAKING_LIBRARY=1 -DSCI_LEXER=1 -D_CRT_SECURE_NO_DEPRECATE=1 -DNDEBUG=1 -DLUA_PATH_DEFAULT=\"\" -DLUA_CPATH_DEFAULT=\"\" -DQSU_INCLUDE_MOC=1 -DLUA_VERSION_NUM=503 -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../NotepadNext -I. -I../../singleapplication -I../../scintilla/qt/ScintillaEditBase -I../../scintilla/qt/ScintillaEdit -I../../scintilla/include -I../../scintilla/src -I../../lexilla/access -I../../lexilla/lexlib -I../../lexilla/include -I../../uchardet/src -I../../lua/src -I../../ads/src -I../../editorconfig-core-qt -I../../QSimpleUpdater/include -I../../NotepadNext/decorators -I../../NotepadNext/dialogs -I../../NotepadNext/widgets -I../../LuaBridge -I../../../src -I../../lexilla/include -I/@unixroot/usr/include/qt5 -I/@unixroot/usr/include/qt5/QtPrintSupport -I/@unixroot/usr/include/qt5/QtWidgets -I/@unixroot/usr/include/qt5/QtGui -I/@unixroot/usr/include/qt5/QtNetwork -I/@unixroot/usr/include/qt5/QtCore -Ibuild/moc -Ibuild/ui -I/@unixroot/usr/lib/qt5/mkspecs/os2-g++ -o build/obj/LuaExtension.obj ../../NotepadNext/LuaExtension.cpp
../../NotepadNext/IFaceTable.cpp:28:7: error: need 'typename' before 'std::iterator_traits<_Iterator>::value_type' because 'std::iterator_traits<_Iterator>' is a dependent scope
   28 | const std::iterator_traits<Iter>::value_type *binary_find(Iter begin, Iter end, const char *name) {
      |       ^~~
      |       typename 
../../NotepadNext/IFaceTable.cpp: In member function 'virtual const IFaceConstant* IFaceTable::FindConstant(const char*) const':
../../NotepadNext/IFaceTable.cpp:42:12: error: 'binary_find' was not declared in this scope
   42 |     return binary_find(constants.cbegin(), constants.cend(), name);
      |            ^~~~~~~~~~~
../../NotepadNext/IFaceTable.cpp: In member function 'virtual const IFaceFunction* IFaceTable::FindFunction(const char*) const':
../../NotepadNext/IFaceTable.cpp:46:12: error: 'binary_find' was not declared in this scope
   46 |     return binary_find(functions.cbegin(), functions.cend(), name);
      |            ^~~~~~~~~~~
../../NotepadNext/IFaceTable.cpp: In member function 'virtual const IFaceProperty* IFaceTable::FindProperty(const char*) const':
../../NotepadNext/IFaceTable.cpp:79:12: error: 'binary_find' was not declared in this scope
   79 |     return binary_find(properties.cbegin(), properties.cend(), name);
      |            ^~~~~~~~~~~
make[1]: *** [build/obj/IFaceTable.obj] Error 1

Any idea about this??

**Comment by dail8859** [comment]
> ../../NotepadNext/IFaceTable.cpp:28:7: error: need 'typename' before 'std::iterator_traits<_Iterator>::value_type' because 'std::iterator_traits<_Iterator>' is a dependent scope

Would seem to suggest it doesn't like this section of code for some reason.

https://github.com/dail8859/NotepadNext/blob/46cf4d9273490662c7c0fa630af833d89ac48173/src/NotepadNext/IFaceTable.cpp#L26-L38

I'm sure I grabbed this code from somewhere else. Since it works with my complier and doesn't give any warnings I'm not sure as to exactly how to fix this.

My only suggestion might be to change where the `const` is placed on line 27 from:

```cpp
typename const std::iterator_traits<Iter>::value_type *binary_find(Iter begin, Iter end, const char *name) {
```

To this:

```cpp
typename std::iterator_traits<Iter>::value_type const *binary_find(Iter begin, Iter end, const char *name) {
```

I won't be able to try this change with MSVC complier till later today, but might be worth a quick try to see if gcc accepts it or not.

**Comment by TeLLie** [comment]
Hi,
Thankz for the fast answer :)
Yes this helps about this errror...
Now i face some other errors....

g++ -c -Zomf -march=i686 -O2 -mno-avx -std=gnu++1z -Wall -Wextra -DQT_NO_IPV6 -DAPP_VERSION="\"0.4.2\"" -DAPP_COPYRIGHT="\"Copyright 2019-2021 Justin Dailey\"" -DSCI_OWNREGEX -DADS_STATIC -DQAPPLICATION_CLASS=QApplication -DSCINTILLA_QT=1 -DMAKING_LIBRARY=1 -DSCI_LEXER=1 -D_CRT_SECURE_NO_DEPRECATE=1 -DNDEBUG=1 -DLUA_PATH_DEFAULT=\"\" -DLUA_CPATH_DEFAULT=\"\" -DQSU_INCLUDE_MOC=1 -DLUA_VERSION_NUM=503 -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../NotepadNext -I. -I../../singleapplication -I../../scintilla/qt/ScintillaEditBase -I../../scintilla/qt/ScintillaEdit -I../../scintilla/include -I../../scintilla/src -I../../lexilla/access -I../../lexilla/lexlib -I../../lexilla/include -I../../uchardet/src -I../../lua/src -I../../ads/src -I../../editorconfig-core-qt -I../../QSimpleUpdater/include -I../../NotepadNext/decorators -I../../NotepadNext/dialogs -I../../NotepadNext/widgets -I../../LuaBridge -I../../../src -I../../lexilla/include -I/@unixroot/usr/include/qt5 -I/@unixroot/usr/include/qt5/QtPrintSupport -I/@unixroot/usr/include/qt5/QtWidgets -I/@unixroot/usr/include/qt5/QtGui -I/@unixroot/usr/include/qt5/QtNetwork -I/@unixroot/usr/include/qt5/QtCore -Ibuild/moc -Ibuild/ui -I/@unixroot/usr/lib/qt5/mkspecs/os2-g++ -o build/obj/moc_LanguagePropertiesModel.obj build/moc/moc_LanguagePropertiesModel.cpp
In file included from C:/usr/include/c++/9/bits/move.h:55,
                 from C:/usr/include/c++/9/bits/stl_pair.h:59,
                 from C:/usr/include/c++/9/bits/stl_algobase.h:64,
                 from C:/usr/include/c++/9/memory:62,
                 from build/moc/moc_EditorManager.cpp:9:
C:/usr/include/c++/9/type_traits: In instantiation of 'struct std::is_trivial<QPointer<ScintillaNext> >':
C:/usr/include/qt5/QtCore/qtypeinfo.h:66:32:   required from 'constexpr bool qIsTrivial() [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qtypeinfo.h:84:35:   required from 'class QTypeInfo<QPointer<ScintillaNext> >'
C:/usr/include/qt5/QtCore/qlist.h:523:31:   required from 'void QList<T>::node_destruct(QList<T>::Node*, QList<T>::Node*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:921:5:   required from 'void QList<T>::dealloc(QListData::Data*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:874:9:   required from 'QList<T>::~QList() [with T = QPointer<ScintillaNext>]'
build/moc/../../../../NotepadNext/EditorManager.h:28:7:   required from here
C:/usr/include/c++/9/type_traits:672:12: error: invalid use of incomplete type 'class QPointer<ScintillaNext>'
  672 |     struct is_trivial
      |            ^~~~~~~~~~
In file included from C:/usr/include/qt5/QtCore/qobject.h:54,
                 from C:/usr/include/qt5/QtCore/QObject:1,
                 from build/moc/../../../../NotepadNext/EditorManager.h:23,
                 from build/moc/moc_EditorManager.cpp:10:
C:/usr/include/qt5/QtCore/qmetatype.h:237:7: note: declaration of 'class QPointer<ScintillaNext>'
  237 |     F(QPointer)
      |       ^~~~~~~~
C:/usr/include/qt5/QtCore/qmetatype.h:1489:30: note: in definition of macro 'QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER'
 1489 |     template <class T> class Name; \
      |                              ^~~~
C:/usr/include/qt5/QtCore/qmetatype.h:1491:1: note: in expansion of macro 'QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER'
 1491 | QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER(QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/usr/include/qt5/QtCore/qglobal.h:1300,
                 from C:/usr/include/qt5/QtCore/qnamespace.h:43,
                 from C:/usr/include/qt5/QtCore/qobjectdefs.h:48,
                 from C:/usr/include/qt5/QtCore/qobject.h:46,
                 from C:/usr/include/qt5/QtCore/QObject:1,
                 from build/moc/../../../../NotepadNext/EditorManager.h:23,
                 from build/moc/moc_EditorManager.cpp:10:
C:/usr/include/qt5/QtCore/qtypeinfo.h: In instantiation of 'constexpr bool qIsTrivial() [with T = QPointer<ScintillaNext>]':
C:/usr/include/qt5/QtCore/qtypeinfo.h:84:35:   required from 'class QTypeInfo<QPointer<ScintillaNext> >'
C:/usr/include/qt5/QtCore/qlist.h:523:31:   required from 'void QList<T>::node_destruct(QList<T>::Node*, QList<T>::Node*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:921:5:   required from 'void QList<T>::dealloc(QListData::Data*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:874:9:   required from 'QList<T>::~QList() [with T = QPointer<ScintillaNext>]'
build/moc/../../../../NotepadNext/EditorManager.h:28:7:   required from here
C:/usr/include/qt5/QtCore/qtypeinfo.h:66:32: error: 'value' is not a member of 'std::is_trivial<QPointer<ScintillaNext> >'
   66 |     return std::is_trivial<T>::value;
      |                                ^~~~~
C:/usr/include/qt5/QtCore/qtypeinfo.h: In instantiation of 'class QTypeInfo<QPointer<ScintillaNext> >':
C:/usr/include/qt5/QtCore/qlist.h:523:31:   required from 'void QList<T>::node_destruct(QList<T>::Node*, QList<T>::Node*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:921:5:   required from 'void QList<T>::dealloc(QListData::Data*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:874:9:   required from 'QList<T>::~QList() [with T = QPointer<ScintillaNext>]'
build/moc/../../../../NotepadNext/EditorManager.h:28:7:   required from here
C:/usr/include/qt5/QtCore/qtypeinfo.h:84:35:   in 'constexpr' expansion of 'qIsTrivial<QPointer<ScintillaNext> >()'
C:/usr/include/qt5/QtCore/qtypeinfo.h:80:10: error: 'constexpr' call flows off the end of the function
   80 |     enum {
      |          ^
C:/usr/include/qt5/QtCore/qtypeinfo.h:80:10: error: enumerator value for 'isComplex' is not an integer constant
In file included from C:/usr/include/c++/9/bits/move.h:55,
                 from C:/usr/include/c++/9/bits/stl_pair.h:59,
                 from C:/usr/include/c++/9/bits/stl_algobase.h:64,
                 from C:/usr/include/c++/9/memory:62,
                 from build/moc/moc_EditorManager.cpp:9:
C:/usr/include/c++/9/type_traits: In instantiation of 'struct std::is_trivially_copyable<QPointer<ScintillaNext> >':
C:/usr/include/qt5/QtCore/qtypeinfo.h:56:49:   required from 'constexpr bool qIsRelocatable() [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qtypeinfo.h:86:42:   required from 'class QTypeInfo<QPointer<ScintillaNext> >'
C:/usr/include/qt5/QtCore/qlist.h:523:31:   required from 'void QList<T>::node_destruct(QList<T>::Node*, QList<T>::Node*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:921:5:   required from 'void QList<T>::dealloc(QListData::Data*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:874:9:   required from 'QList<T>::~QList() [with T = QPointer<ScintillaNext>]'
build/moc/../../../../NotepadNext/EditorManager.h:28:7:   required from here
C:/usr/include/c++/9/type_traits:678:12: error: invalid use of incomplete type 'class QPointer<ScintillaNext>'
  678 |     struct is_trivially_copyable
      |            ^~~~~~~~~~~~~~~~~~~~~
In file included from C:/usr/include/qt5/QtCore/qobject.h:54,
                 from C:/usr/include/qt5/QtCore/QObject:1,
                 from build/moc/../../../../NotepadNext/EditorManager.h:23,
                 from build/moc/moc_EditorManager.cpp:10:
C:/usr/include/qt5/QtCore/qmetatype.h:237:7: note: declaration of 'class QPointer<ScintillaNext>'
  237 |     F(QPointer)
      |       ^~~~~~~~
C:/usr/include/qt5/QtCore/qmetatype.h:1489:30: note: in definition of macro 'QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER'
 1489 |     template <class T> class Name; \
      |                              ^~~~
C:/usr/include/qt5/QtCore/qmetatype.h:1491:1: note: in expansion of macro 'QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER'
 1491 | QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER(QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/usr/include/qt5/QtCore/qglobal.h:1300,
                 from C:/usr/include/qt5/QtCore/qnamespace.h:43,
                 from C:/usr/include/qt5/QtCore/qobjectdefs.h:48,
                 from C:/usr/include/qt5/QtCore/qobject.h:46,
                 from C:/usr/include/qt5/QtCore/QObject:1,
                 from build/moc/../../../../NotepadNext/EditorManager.h:23,
                 from build/moc/moc_EditorManager.cpp:10:
C:/usr/include/qt5/QtCore/qtypeinfo.h: In instantiation of 'constexpr bool qIsRelocatable() [with T = QPointer<ScintillaNext>]':
C:/usr/include/qt5/QtCore/qtypeinfo.h:86:42:   required from 'class QTypeInfo<QPointer<ScintillaNext> >'
C:/usr/include/qt5/QtCore/qlist.h:523:31:   required from 'void QList<T>::node_destruct(QList<T>::Node*, QList<T>::Node*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:921:5:   required from 'void QList<T>::dealloc(QListData::Data*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:874:9:   required from 'QList<T>::~QList() [with T = QPointer<ScintillaNext>]'
build/moc/../../../../NotepadNext/EditorManager.h:28:7:   required from here
C:/usr/include/qt5/QtCore/qtypeinfo.h:56:49: error: 'value' is not a member of 'std::is_trivially_copyable<QPointer<ScintillaNext> >'
   56 |     return std::is_trivially_copyable<T>::value && std::is_trivially_destructible<T>::value;
      |                                           ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/usr/include/c++/9/bits/move.h:55,
                 from C:/usr/include/c++/9/bits/stl_pair.h:59,
                 from C:/usr/include/c++/9/bits/stl_algobase.h:64,
                 from C:/usr/include/c++/9/memory:62,
                 from build/moc/moc_EditorManager.cpp:9:
C:/usr/include/c++/9/type_traits: In instantiation of 'struct std::is_trivially_destructible<QPointer<ScintillaNext> >':
C:/usr/include/qt5/QtCore/qtypeinfo.h:56:49:   required from 'constexpr bool qIsRelocatable() [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qtypeinfo.h:86:42:   required from 'class QTypeInfo<QPointer<ScintillaNext> >'
C:/usr/include/qt5/QtCore/qlist.h:523:31:   required from 'void QList<T>::node_destruct(QList<T>::Node*, QList<T>::Node*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:921:5:   required from 'void QList<T>::dealloc(QListData::Data*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:874:9:   required from 'QList<T>::~QList() [with T = QPointer<ScintillaNext>]'
build/moc/../../../../NotepadNext/EditorManager.h:28:7:   required from here
C:/usr/include/c++/9/type_traits:1235:12: error: invalid use of incomplete type 'class QPointer<ScintillaNext>'
 1235 |     struct is_trivially_destructible
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/usr/include/qt5/QtCore/qobject.h:54,
                 from C:/usr/include/qt5/QtCore/QObject:1,
                 from build/moc/../../../../NotepadNext/EditorManager.h:23,
                 from build/moc/moc_EditorManager.cpp:10:
C:/usr/include/qt5/QtCore/qmetatype.h:237:7: note: declaration of 'class QPointer<ScintillaNext>'
  237 |     F(QPointer)
      |       ^~~~~~~~
C:/usr/include/qt5/QtCore/qmetatype.h:1489:30: note: in definition of macro 'QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER'
 1489 |     template <class T> class Name; \
      |                              ^~~~
C:/usr/include/qt5/QtCore/qmetatype.h:1491:1: note: in expansion of macro 'QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER'
 1491 | QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER(QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/usr/include/qt5/QtCore/qglobal.h:1300,
                 from C:/usr/include/qt5/QtCore/qnamespace.h:43,
                 from C:/usr/include/qt5/QtCore/qobjectdefs.h:48,
                 from C:/usr/include/qt5/QtCore/qobject.h:46,
                 from C:/usr/include/qt5/QtCore/QObject:1,
                 from build/moc/../../../../NotepadNext/EditorManager.h:23,
                 from build/moc/moc_EditorManager.cpp:10:
C:/usr/include/qt5/QtCore/qtypeinfo.h: In instantiation of 'constexpr bool qIsRelocatable() [with T = QPointer<ScintillaNext>]':
C:/usr/include/qt5/QtCore/qtypeinfo.h:86:42:   required from 'class QTypeInfo<QPointer<ScintillaNext> >'
C:/usr/include/qt5/QtCore/qlist.h:523:31:   required from 'void QList<T>::node_destruct(QList<T>::Node*, QList<T>::Node*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:921:5:   required from 'void QList<T>::dealloc(QListData::Data*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:874:9:   required from 'QList<T>::~QList() [with T = QPointer<ScintillaNext>]'
build/moc/../../../../NotepadNext/EditorManager.h:28:7:   required from here
C:/usr/include/qt5/QtCore/qtypeinfo.h:56:49: error: 'value' is not a member of 'std::is_trivially_destructible<QPointer<ScintillaNext> >'
   56 |     return std::is_trivially_copyable<T>::value && std::is_trivially_destructible<T>::value;
      |                                           ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/usr/include/qt5/QtCore/qtypeinfo.h: In instantiation of 'class QTypeInfo<QPointer<ScintillaNext> >':
C:/usr/include/qt5/QtCore/qlist.h:523:31:   required from 'void QList<T>::node_destruct(QList<T>::Node*, QList<T>::Node*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:921:5:   required from 'void QList<T>::dealloc(QListData::Data*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:874:9:   required from 'QList<T>::~QList() [with T = QPointer<ScintillaNext>]'
build/moc/../../../../NotepadNext/EditorManager.h:28:7:   required from here
C:/usr/include/qt5/QtCore/qtypeinfo.h:86:42:   in 'constexpr' expansion of 'qIsRelocatable<QPointer<ScintillaNext> >()'
C:/usr/include/qt5/QtCore/qtypeinfo.h:80:10: error: 'constexpr' call flows off the end of the function
   80 |     enum {
      |          ^
C:/usr/include/qt5/QtCore/qtypeinfo.h:80:10: error: enumerator value for 'isRelocatable' is not an integer constant
C:/usr/include/qt5/QtCore/qtypeinfo.h:87:20: error: invalid application of 'sizeof' to incomplete type 'QPointer<ScintillaNext>'
   87 |         isLarge = (sizeof(T)>sizeof(void*)),
      |                    ^~~~~~~~~
C:/usr/include/qt5/QtCore/qtypeinfo.h:89:18: error: invalid application of 'sizeof' to incomplete type 'QPointer<ScintillaNext>'
   89 |         sizeOf = sizeof(T)
      |                  ^~~~~~~~~
In file included from C:/usr/include/qt5/QtCore/qobject.h:49,
                 from C:/usr/include/qt5/QtCore/QObject:1,
                 from build/moc/../../../../NotepadNext/EditorManager.h:23,
                 from build/moc/moc_EditorManager.cpp:10:
C:/usr/include/qt5/QtCore/qlist.h: In instantiation of 'void QList<T>::node_destruct(QList<T>::Node*, QList<T>::Node*) [with T = QPointer<ScintillaNext>]':
C:/usr/include/qt5/QtCore/qlist.h:921:5:   required from 'void QList<T>::dealloc(QListData::Data*) [with T = QPointer<ScintillaNext>]'
C:/usr/include/qt5/QtCore/qlist.h:874:9:   required from 'QList<T>::~QList() [with T = QPointer<ScintillaNext>]'
build/moc/../../../../NotepadNext/EditorManager.h:28:7:   required from here
C:/usr/include/qt5/QtCore/qlist.h:523:31: warning: enum constant in boolean context [-Wint-in-bool-context]
  523 |     if (QTypeInfo<T>::isLarge || QTypeInfo<T>::isStatic)
      |                       ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
C:/usr/include/qt5/QtCore/qlist.h:524:31: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
  524 |         while(from != to) --to, delete reinterpret_cast<T*>(to->v);
C:/usr/include/qt5/QtCore/qlist.h:524:65: warning: invalid use of incomplete type 'class QPointer<ScintillaNext>'
  524 |         while(from != to) --to, delete reinterpret_cast<T*>(to->v);
      |                                                             ~~~~^
In file included from C:/usr/include/qt5/QtCore/qobject.h:54,
                 from C:/usr/include/qt5/QtCore/QObject:1,
                 from build/moc/../../../../NotepadNext/EditorManager.h:23,
                 from build/moc/moc_EditorManager.cpp:10:
C:/usr/include/qt5/QtCore/qmetatype.h:237:7: note: declaration of 'class QPointer<ScintillaNext>'
  237 |     F(QPointer)
      |       ^~~~~~~~
C:/usr/include/qt5/QtCore/qmetatype.h:1489:30: note: in definition of macro 'QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER'
 1489 |     template <class T> class Name; \
      |                              ^~~~
C:/usr/include/qt5/QtCore/qmetatype.h:1491:1: note: in expansion of macro 'QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER'
 1491 | QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER(QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/usr/include/qt5/QtCore/qobject.h:49,
                 from C:/usr/include/qt5/QtCore/QObject:1,
                 from build/moc/../../../../NotepadNext/EditorManager.h:23,
                 from build/moc/moc_EditorManager.cpp:10:
C:/usr/include/qt5/QtCore/qlist.h:524:31: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
  524 |         while(from != to) --to, delete reinterpret_cast<T*>(to->v);
C:/usr/include/qt5/QtCore/qlist.h:526:61: error: invalid use of incomplete type 'class QPointer<ScintillaNext>'
  526 |         while (from != to) --to, reinterpret_cast<T*>(to)->~T();
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
In file included from C:/usr/include/qt5/QtCore/qobject.h:54,
                 from C:/usr/include/qt5/QtCore/QObject:1,
                 from build/moc/../../../../NotepadNext/EditorManager.h:23,
                 from build/moc/moc_EditorManager.cpp:10:
C:/usr/include/qt5/QtCore/qmetatype.h:237:7: note: declaration of 'class QPointer<ScintillaNext>'
  237 |     F(QPointer)
      |       ^~~~~~~~
C:/usr/include/qt5/QtCore/qmetatype.h:1489:30: note: in definition of macro 'QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER'
 1489 |     template <class T> class Name; \
      |                              ^~~~
C:/usr/include/qt5/QtCore/qmetatype.h:1491:1: note: in expansion of macro 'QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER'
 1491 | QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER(QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [build/obj/moc_EditorManager.obj] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `D:/Test/NotepadNext/src/515/NotepadNext'
make: *** [sub-NotepadNext-make_first] Error 2

**Comment by dail8859** [comment]
It doesn't like that QPointer isn't defined. Try adding this include to the top of `EditorManger.h` and see if it helps.

```cpp
#include <QPointer>
```

**Comment by TeLLie** [comment]
Yes, now its compiling till the end :)
Then i start the program i get .....

D:\Test\NotepadNext\src\515\NotepadNext>NotepadNext.exe 2>&1 |tee run.out

Killed by SIGSEGV
pid=0x0aae ppid=0x001d tid=0x0001 slot=0x00a8 pri=0x0200 mc=0x0001 ps=0x0010
D:\TEST\NOTEPADNEXT\SRC\515\NOTEPADNEXT\NOTEPADNEXT.EXE
cs:eip=00d1ff74:00000000      ss:esp=2005225a:00000000      ebp=00000053
 ds=0000      es=0000      fs=0001      gs=0000     efl=00000000
eax=00d1fbbc ebx=1ffc9d7c ecx=00d1fbd0 edx=00d1fbf4 edi=00000000 esi=00d1ff6c

**Comment by TeLLie** [comment]
Hi,
I will make a debug build, as we don't have a decent debugger like gdb

Op ma 29 nov. 2021 18:31 schreef dail8859 ***@***.***>:

**Comment by dail8859** [comment]
I've pushed a commit to the `dev` brach to fix the compilation errors now.

**Comment by TeLLie** [comment]
Hi
Just got  it compiled now, had to add some defined to the singleapplication_p
Now all seems to work :)

**Comment by dail8859** [comment]
This project uses the `SingleApplication` code from https://github.com/itay-grudev/SingleApplication

So if there are some changes needing to be made that would be the repository to get that change put in permanently.

**Comment by TeLLie** [comment]
Hi
Ok, thankz

Op vr 3 dec. 2021 21:49 schreef dail8859 ***@***.***>:

**Comment by dail8859** [comment]
@TeLLie Closing this issue for now. If there are other changes/help needed let me know or feel free to open a pull request.
