### ISSUE TITLE
File location changes when saving file

### ISSUE THREAD

**Issue by fanhua1550** [dail8859/NotepadNext#421]
现有文件保存后，文件位置会改动。感觉就是直接旧文件 copy成新文件一样，然后删除原文件。

**Comment by dail8859** [comment]
> When an existing file is saved, the file location changes. It feels like copying the old file directly into a new file, and then deleting the original file.

Yes this is what it is doing. This is an option Qt provides and is made to be safer in case there are any issues an prevent data loss. This can be changed and to just do a normal overwrite.

Are you just referring to files on the Desktop? Or are there any other situations where this is causing problems?
