### ISSUE TITLE
可以出一个详细一点的编译说明吗？

### ISSUE THREAD

**Issue by zdhsoft** [dail8859/NotepadNext#426]
可以出一个详细一点的编译说明吗？QT环境一直没有成功。

**Comment by dail8859** [comment]
See /doc/Building.md

**Comment by dail8859** [comment]
> Look, it's too simple, configuring qt has not been successful

There's plenty of tutorials online on how to set up Qt. If there is something specific about the application code you are having issues with let me know. Unfortunately there's nothing else I can do since I'm not sure what issues you are having since you have not given any specifics.
