### ISSUE TITLE
Feature request: quitly autosave unsaved work, and restore after a crash / shutdown

### ISSUE THREAD

**Issue by cdwijs** [dail8859/NotepadNext#429]
When there's unsaved work, NotepadNext asks the user to save it, instead of retaining the unsaved work in a temp file somewhere.

Also, when NotepadNext is killed, any unsaved work is lost.

To reproduce:
1) Start NotepadNext from the console
2) Type something
3) Press the X in the top-left. Now the popup "Save file New 1" comes up. I would like NotepadNext to silently exit.
4) Choose cancel. Now NotepadNext does not exit.
5) Simulate a crash of NotepadNext (by pressing ctrl-c in the console where it was started from). NotepadNext disapears.
6) Start NotepadNext again from the console. Now the text from step 2 is gone. I would like NotepadNext to restore this text from an autosave location somewhere

My versions:
Qt: 6.5.2
Notepad Next v0.6.3 made from this aur script:
https://aur.archlinux.org/packages/notepadnext
$ uname -a
Linux cedric 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux

**Comment by cdwijs** [comment]
Ah, this is a duplicate of https://github.com/dail8859/NotepadNext/issues/400
This can be enabled in the settings, but it's at your own risk for now.

**Comment by dail8859** [comment]
I've been using it without any issues and haven't had anything else major reported from users regarding the feature. But due to the potential loss of data, yes I consider it experimental for now and suggest using it with caution.
