### ISSUE TITLE
how to edit or open a file by shell or cmd

### ISSUE THREAD

**Issue by aohanhongzhi** [dail8859/NotepadNext#438]
for example:

vscode can open a file by `code fileName`

![image](https://github.com/dail8859/NotepadNext/assets/37319319/b11042f9-23bd-441b-9cbe-d7ec05efd390)

I can open it by shell

![image](https://github.com/dail8859/NotepadNext/assets/37319319/a9e0744b-8047-4599-961c-e4a8248a4be8)
```shell
alias np="/opt/eric/NotepadNext-v0.6.3-x86_64.AppImage"
```

but I  cant open it again, I hope do it . maybe you make the app  just single instance, but I just want to open the file in notepad next, I dont care the single instance.

![image](https://github.com/dail8859/NotepadNext/assets/37319319/e0372dc2-955d-4425-9e36-7edd8e804a4a)

**Comment by dail8859** [comment]
> maybe you make the app just single instance, but I just want to open the file in notepad next, I dont care the single instance.

The secondary instance should send the requested file path to the primary instance. This is how it works on Windows and should be the same on Linux, though I don't use Linux so I can't be any direct help.

Try the following:
1. `np file1.txt`
2. In the application open `Help > Debug Log`
3. In the terminal open another file `np file2.txt`
4. Check the debug log in the application, it should print out some information that it received from the secondary instance. Something like:

> [     9.576] I: void __cdecl MainWindow::openFileList(const class QList<class QString> &)
[     9.576] I: C:\Users\user\Desktop\file1.txt

Looking at it now I probably need to add some more debugging that may help.

**Comment by dail8859** [comment]
The other thing that you might be referring to is it not forcing the application to the foreground. This is much more difficult than it should be since the OS does not like an application forcing itself to the front.

The Windows implementation is a bit hacky and I never found a good way to do it in Linux. Maybe someone else has some ideas to try.

**Comment by dail8859** [comment]
I tested with Ubuntu 22.04 and Notepad Next v0.6.4 and cannot reproduce this. The secondary instance correctly causes the application to open the desired file. The application is not pushed to the foreground but that is an entirely separate issue.

**Comment by aohanhongzhi** [comment]
I want to open it by shell on macbook, so how should I solve the problem?

**Comment by dail8859** [comment]
No clue. I've never used Mac at all.
