### ISSUE TITLE
无法定位程序输入点SystemParametersInfoForDpi

### ISSUE THREAD

**Issue by zhuozhengsoft** [dail8859/NotepadNext#439]
安装后，首次运行就报错。完全无法使用。
无法定位程序输入点SystemParametersInfoForDpi于动态链接库 C:\Program Files\Notepad Next\Qt6Gui.dll.上。

**Comment by dail8859** [comment]
What OS version are you using?
How did you install it? (installer, winget, etc)?
Did all of the dll files get installed? I've sometimes seen anti-virus software block files.

You should have these installed in `C:\Program Files\Notepad Next`:
![image](https://github.com/dail8859/NotepadNext/assets/3694843/42a67af0-0544-48b5-a11a-25f9c392d19b)

**Comment by leohan1992** [comment]
I have the same question. I tried it on windows server 2012. Everything explored in folder.Any way to solve it?

**Comment by dail8859** [comment]
Notepad Next is built with Qtv6.5, which requires Windows 10 (or an equivalent server version) or later to run.

**Comment by dail8859** [comment]
Notepad Next is technically still built with Qt5.15 which _should_ run fine on Windows Server 2012.

These builds are not released or officially supported on Windows. **Use at your own risk**.

Here is a nightly build of the installer for Notepad Next using Qt5.15 (you might have to unzip it first):

https://github.com/dail8859/NotepadNext/suites/16163233488/artifacts/922914194

**Comment by dail8859** [comment]
Closing as I am assuming the original issue is related to a non supported OS
