### ISSUE TITLE
The dependent library uchardet is gone

### ISSUE THREAD

**Issue by GuangBin-L** [dail8859/NotepadNext#440]
The dependent library uchardet is gone, and it cannot be compiled by itself

**Comment by dail8859** [comment]
Looks like you are correct. Probably best to find good copy of it and keep it in the repo rather than relying on a submodule.

**Comment by dail8859** [comment]
I just checked and I was able to clone the repository correctly along with pulling down the uchardet library. Are you still having issues? If so what are they exactly?

**Comment by GuangBin-L** [comment]
No problem, thank you
