### ISSUE TITLE
[Q] macOS: which version (still) supports older OS?

### ISSUE THREAD

**Issue by bsdooby** [dail8859/NotepadNext#443]
Hi,

Really appreciate your reimpl. efforts of Notepad++ (it is a daily driver for me). 
As I use a lot of older systems (macOS High Sierra, 10.13, etc.), I wonder what version(s) 
of NotepadNext still support such setups...Is it Qt dependent?

Cheers

**Comment by dail8859** [comment]
Yes, it is Qt dependent. According to https://doc.qt.io/qt-6/macos.html macOS 11, 12, 13 are supported. Notepad Next only _officially_ supports Qt v6.5 currently. However, it is still being built with Qt 5.15 and Qt 6.2. Compatibility with older Qt versions will be kept for as long as reasonably possible (e.g. for the case of users wanting to run it on older systems, etc) **but only at their own risk**.

You can download the nightly build of the application with Qt5.15 here (you probably need to unzip it first): https://github.com/dail8859/NotepadNext/suites/16163233488/artifacts/922914190

Again, this is **not officially supported, and you are using this at your own risk**.

**Comment by bsdooby** [comment]
Dear dail8859,

Thank you very much for this! I understand and agree these user terms ;)
Keep up the good work.

Cheers
Peter

**Comment by dail8859** [comment]
There is no permalink available...GitHub has no way of setting that up. You can download the latest macOS version built with Qt5.15 here: https://github.com/dail8859/NotepadNext/suites/17372089695/artifacts/992791769

**Comment by bsdooby** [comment]
Hi,

Thank you. So each time a new version of NotepadNext is made available
(built w/ Qt5), I have to ask you?
Maybe you could provide a link on your GitHub page? If this does not bother
you, OFC ;)

Cheers

**Comment by bsdooby** [comment]
Hi,

Could you provide me with the current link for the Qt5 based (current)
version for macOS?

Thank you very much

Cheers

**Comment by bsdooby** [comment]
Hi, what is the current Qt5 build link (you know, for older macOS version ;)). Thank you

**Comment by dail8859** [comment]
For future reference you can find the Qt5 build of it in the Github Actions tab:

1. Go [here](https://github.com/dail8859/NotepadNext/actions/workflows/build.yml?query=event%3Apush)
2. Find the tagged version or you can use the latest build.
3. Under the "Artifacts" section
4. Find the artifact named `NotepadNext-macOS-Qt5.15`
5. Download and unzip

0.7 is here [NotepadNext-macOS-Qt5.15](https://github.com/dail8859/NotepadNext/actions/runs/8009956505/artifacts/1267636695)

**Comment by bsdooby** [comment]
Now how cool is that! Thank you so much

**Comment by dail8859** [comment]
> You no longer build/support Qt5 for (older) macOS versions?

Qt5 for MacOS is not automatically built any more. GitHub updated their macOS version and Qt5.15 started failing. I'm not sure the root cause and do not have any macOS to test on to try to get it working again. And instead of continuously fighting with debugging the build through GitHub actions, I removed it.

It should in theory be possible, but I don't know how. If someone figures it out and creates a PR to get Qt5 working again for macOS I'd gladly accept it.

**Comment by bsdooby** [comment]
It's a shame :( But thank you for your update...

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
Would it be any trouble to request a link to a version compatible with MacOS 10.13.6 High Sierra?
