### ISSUE TITLE
[RFE] request for documentation on feature matrix parity with notepad++

### ISSUE THREAD

**Issue by hgkamath** [dail8859/NotepadNext#444]
Firstly thank-you to the developers.  
The linux world has many advanced editors. Despite that, herein, I note two reasons why a need/niche for notepad++ exists. 
- For sake of lightweight use. Heavy-use use-cases of editing require their own advanced editor. Apart from these heavy-use use cases, lightweight-usecase for quick use also exists. A lightweight editor such as windows ```notepad.exe``` starts up very quickly and is useful for scrap writing and and quick editing. Though one would think a cross-platform basic notepad would exist, I don't think there is any serious project maintaining a cross-platform basic notepad, because almost always it makes sense to add a few more features that the basic notepad. Lightweight editors include lite-xl, notepad-next etc. IMHO, Lightweight editors should be less than 3Mb and load quickly.
- For sake of same muscle-memory. Though each desktop environment provides its own lightweight editor, such as notepad, gedit, textedit, kwrite, etc The feel of each is different. In particular, notepad++ exists only for windows as it use C# and windows-only native api. It helps when an editor is cross-platform, such as like notepad-next. With a cross-platform lightweight editor, one always used the same editor by reflex, and all the menus key bindngs will all be the same. Especially when one switches between environments like Dualboot/VMs/multiple-machines.

As it is true that notepad-next is supposed to be a re-implementation of notepad++ in C++ in order to be cross-platform, it is hence fair to expect their features to be compared. 

This issue is to request a documentation file, ```doc/feature_matrix.md``` a checkbox-listing, which details features in notepad-next and notepad++ and their status.   Such file will probably also double up as a developer todo list.
The list could be ordered to have 3 top-level sections
1. Features that notepad++ does not have (or does not make sense to have) but notepad-next has or will have 
2. Features that notepad++ has and notepad-next has already caught up to or will eventually catch up to. This section could be broken into a long term, mid-term, short-term, and done
3. Features present in notepad++ that notepad-next will never do (as maybe it does not make sense to have)

The documentation file will need to be updated periodically whenever there is a version update to either notepad++/notepad-next. ie when features are added/deprecated in notepad++ as well as added/deprecated in notepad-next.

**Comment by dail8859** [comment]
> IMHO, Lightweight editors should be less than 3Mb

3MB is quite tiny compared to today's standards. Possible, yes; but would require removing most features. If you then want to have a cross platform application...it would only increase the size due to all the OS abstraction.

As for the request, I have no desire to document this. Mostly because I can't answer a lot of it. I don't know what will be implemented or what won't be. There's already features I've implemented I thought at one time I never would. There's also other things that might turn out to be too complicated or require too much maintenance. I also don't know when something might get implemented. It is mostly just what interests me at the time.

If someone is interested in contributing non-trivial features to the project I'd encourage them to start a discussion to talk about it. There is certainly lots of room for improvement.

**Comment by hgkamath** [comment]
no pressure.  Do as you see fit. Its also true that sometimes comparing a software or v 0.67 against one that is at 8.5.7 is unfair. 
Nevertheless, I'll just attempt a list here. Give me a day to populate this, after that I will stop. You can use it like a stub, or reorg it, if u ever choose to do it. 

| Feature✅/❌  | notepad++ | notepad-next |notes|
| ------------- | ------------- | ------------- | ------------- |
| Menu | ✅  | ✅ | - |
| Toolbar | ✅  | ✅ | - |
| Toolbar/new | ✅  | ✅ | - |
| Toolbar/open | ✅  | ✅ | - |
| Toolbar/save | ✅  | ✅ | - |
| Toolbar/saveall | ✅  | ✅ | - |
| Toolbar/close| ✅  | ✅ | - |
| Toolbar/closeall| ✅  | ✅ | - |
| Toolbar/print| ✅  | ❌ | - |
| Toolbar/cut| ✅  | ✅ | - |
| Toolbar/copy| ✅  | ✅ | - |
| Toolbar/paste| ✅  | ✅ | - |
| Toolbar/undo| ✅  | ✅ | - |
| Toolbar/redo| ✅  | ✅ | - |
| Toolbar/findDLG| ✅  | ✅ | - |
| Toolbar/replaceDLG| ✅  | ✅ | - |
| Toolbar/zoom-in| ✅  | ✅ | - |
| Toolbar/zoom-out| ✅  | ✅ | - |
| Toolbar/synchronize horz scrolling| ✅  | ❌ | - |
| Toolbar/synchronize vert scrolling| ✅  | ❌ | - |
| Toolbar/wordwrap| ✅  | ✅ | - |
| Toolbar/show-all-char| ✅  | ✅ | - |
| Toolbar/show-indent-guide| ✅  | ✅ | - |
| Toolbar/Define your language| ✅  | ❌ | - |
| Toolbar/Document map| ✅  | ❌ | - |
| Toolbar/Document List| ✅  | ❌ | - |
| Toolbar/Function List| ✅  | ❌ | - |
| Toolbar/Folder as Workspace| ✅  | ❌ | - |
| Toolbar/tail-f monitoring| ✅  | ❌ | - |
| Toolbar/macro/record macro| ✅  | ✅ | - |
| Toolbar/macro/stop record macro| ✅  | ✅ | notepad++ has dedicated stop button |
| Toolbar/macro/run macro| ✅  | ✅ | - |
| Toolbar/macro/stop play macro| ✅  | ✅ | notepad++ has dedicated stop button  |
| Toolbar/macro/run macro multiple times| ✅  | ✅ | - |
| Toolbar/macro/save macro| ✅  | ✅ | - |
| Toolbar/tab/standalone-new-tab-button  | ✅  | ❌ | - |
| Toolbar/standalone-tab-list  | ✅  | ❌ | - |
| Toolbar/standalone-close-current-tab  | ✅  | ❌ | - |
| Multitabs  | ✅  | ✅ | - |
| Multitabs/tab/icon  | ✅  | ✅ | - |
| Multitabs/tab/close-current  | ✅  | ✅ | - |
| Multitabs/tab/close-all-but-this  | ✅  | ✅ | - |
| Multitabs/tab/close-all-to-the-left  | ✅  | ✅ | - |
| Multitabs/tab/close-all-to-the-right  | ✅  | ✅ | - |
| Multitabs/tab/close-all-unchanged  | ✅  | ❌ | - |
| Multitabs/tab/save  | ✅  | ✅ | - |
| Multitabs/tab/save-as  | ✅  | ✅ | - |
| Multitabs/tab/rename | ✅  | ✅ | - |
| Multitabs/tab/reload  | ✅  | ✅ | - |
| Multitabs/tab/move-to-recycling-bin| ✅  | ❌ | - |
| Multitabs/tab/print | ✅  | ✅ | - |
| Multitabs/tab/set-readonly | ✅  | ❌ | - |
| Multitabs/tab/clear-readonly | ✅  | ❌ | - |
| Multitabs/tab/ | ✅  | ✅ | - |
| Multitabs/tab/ | ✅  | ✅ | - |
| Multitabs/tab/copy-to-clipboard full-filepath | ✅  | ✅ | - |
| Multitabs/tab/copy-to-clipboard filename | ✅  | ✅ | - |
| Multitabs/tab/copy-to-clipboard dirpath | ✅  | ✅ | - |
| Multitabs/tab/apply color to tab | ✅  | ❌ | - |
| Status bar | ✅  | ✅ | - |
| Status bar/filetype | ✅  | ✅ | - |
| Status bar/size| ✅  | ✅ | - |
| Status bar/length| ✅  | ✅ | - |
| Status bar/line no| ✅  | ✅ | - |
| Status bar/col no| ✅  | ✅ | - |
| Status bar/pos no| ✅  | ❌ | - |
| Status bar/sel length| ✅  | ✅ | - |
| Status bar/sel no| ✅  | ✅ | - |
| Status bar/line-terminator| ✅  | ✅ | - |
| Status bar/encoding| ✅  | ✅ | - |
| Status bar/INS-OVR-indicator| ✅  | ❌ | - |
| window resize| ✅  | ✅ | - |

**Comment by hgkamath** [comment]
Firstly, I am happy to say notepad-next is very good for my lightweight editor purposes.
I'll stop now. 
I'll be uninstalling notepad++

Note this comparison is a surface GUI comparison. I am not an hardcore user of notepad++ either. I mostly use neovim. 

> Part of the problem is how granular do you get?

I would have liked to get down to every configurable setting in every dialog that matters in the usage of a feature.  
Due to laziness, I stopped enumerating subfeatures of a feature, when the feature itself did not exist, and felt like there was nothing to compare to. But this seems good enough for now. 
But the list could be expanded the moment a developer knows what they are going to do, and as I mentioned it is a bit like a todo list. 
The feature enumeration needs to be from the perspective as seen by the users, not going into the design internals. 

Another way to have done this comparison, it to first enumerate the features/operations that the editor-engine/lua-engine and then compare both. Then also separately enumerate the shortcuts/menus/toolbars and other GUI elements exposing those features and again compare both. But this can only by done by a developer who knows what each engine can do. 

> not intended to be a true 'source of truth' 

I understand. 
Again, thank-you for notepad-next
