### ISSUE TITLE
Run with visual studio

### ISSUE THREAD

**Issue by Flyingbeanss** [dail8859/NotepadNext#446]
May I know how to run with vs2022? When I open the .pro file with QTVSTOOLs,there is something wrong.
<img width="212" alt="image" src="https://github.com/dail8859/NotepadNext/assets/53996591/ec32d7fe-6acf-45c6-88c1-fd5e3875b9f1">
<img width="553" alt="image" src="https://github.com/dail8859/NotepadNext/assets/53996591/be664a93-325e-4ec6-96e2-b6527c87f31a">

**Comment by dail8859** [comment]
I've never tried building it with Visual Studio. I've always used QtCreator, so wouldn't even be able to guess what is causing it.

Not sure if anyone else has used VS for Notepad Next, maybe they'd be able to offer some suggestions.

**Comment by dail8859** [comment]
There does not seem to be any issues with Notepad Next, so closing.
