### ISSUE TITLE
Add support for MacOS 10.15

### ISSUE THREAD

**Issue by AzagraMac** [dail8859/NotepadNext#454]
Would it be possible to add support for MacOS 10.15 Catalina?

NotepadNext version: 0.6.3
MacOS Catalina version: 10.15.7

![image](https://github.com/dail8859/NotepadNext/assets/571796/c7a38fdc-3042-411e-b632-8065387dd249)

Regards

**Comment by dail8859** [comment]
The application is dependent on the Qt v6.5 library. According to https://doc.qt.io/qt-6/macos.html macOS 11, 12, 13 are supported. Notepad Next only officially supports Qt v6.5 currently. However, it is still being built with Qt 5.15 and Qt 6.2, which should both run on MacOS 10.15. Compatibility with older Qt versions will be kept for as long as reasonably possible (e.g. for the case of users wanting to run it on older systems, etc) **but only at their own risk**.

You can download the nightly build of the application with Qt5.15 here (you probably need to unzip it first): https://github.com/dail8859/NotepadNext/suites/16163233488/artifacts/922914190

Again, this is not officially supported, and **you are using this at your own risk**.
