### ISSUE TITLE
mac 13.4.1  查找页面展示的页面不合理

### ISSUE THREAD

**Issue by Gxiaoqiang** [dail8859/NotepadNext#481]
替换的弹出框，在mac上面展示的比较小。
![image](https://github.com/dail8859/NotepadNext/assets/4338412/5b875c11-9b1d-48f9-9252-6e43ca9e1db4)

**Comment by dail8859** [comment]
> The pop-up box for replacement is smaller on Mac.

There was a similar issue https://github.com/dail8859/NotepadNext/issues/216 that was reported. Are you on the latest v0.6.4 version?

I don't have a mac myself so I'm not able to attempt any fixes to the issue myself.
