### ISSUE TITLE
Column mode shourtcut conflict with polish keyboard layout

### ISSUE THREAD

**Issue by maciej-laskowski** [dail8859/NotepadNext#495]
Column mode shourtcut `option + C` conflicts with polish keyboard layout where `option + C` is used to type `ć` letter.

Weird languages and their problems ;) Perhaps this shourcut could be disabled from preferences.

**Comment by dail8859** [comment]
Thanks for bringing this up.

Honestly it is a bit of an odd shortcut anyways. I just set it to that to match Notepad++ but in reality, it probably isn't so heavily used it needs a shortcut by default.

Easiest solution will just be to remove it completely when I find a bit of free time.

**Comment by maciej-laskowski** [comment]
Thanks! Such shortcuts can be tricky for those using more exotic keyboard layout. Not a big deal in most apps except for text editors :)
