### ISSUE TITLE
Feture Request: Ability to change GUI language

### ISSUE THREAD

**Issue by omeringen** [dail8859/NotepadNext#499]
I request implementing language selection because i want my app running different language than system. On both Windows and GNU/Linux i am not able to change language.

I know there is https://github.com/dail8859/NotepadNext/issues/370 but looks like it's about something different.

**Comment by elcuco** [comment]
I did this (back then...) for Aurora. The changelog says 15 years ago. Its lying, it was last week. I am pretty sure...

Anyway, feel free to rip code from that project :)

https://github.com/Arora/arora/blob/master/src/utils/languagemanager.cpp

**Comment by dail8859** [comment]
I've started refactoring out the translation related code...which was needed.

@elcuco thanks! That will be a good reference.

**Comment by dail8859** [comment]
I also ended up refactoring pretty much all of the settings/preferences related code as it was becoming burdensome to add new settings. Which made it much easier to implement this feature :)

As soon as I get some free time, I'll push what I have.
