### ISSUE TITLE
Add golang

### ISSUE THREAD

**Issue by dail8859** [dail8859/NotepadNext#50]
Though there is not a dedicated lexer, SciTE has some sort of Golang support by using the C++ lexer already implemented.

https://sourceforge.net/p/scintilla/scite/ci/default/tree/src/cpp.properties#l18

CC: @hongnod

**Comment by dail8859** [comment]
I don't know Go at all but here's a quick snippet of code I grabbed from online.

![image](https://user-images.githubusercontent.com/3694843/144721860-3f400945-19be-471b-b54b-50c050a776aa.png)

**Comment by dail8859** [comment]
@hongnod Do you see anything obviously wrong with the screenshot attached above?

**Comment by hongnod** [comment]
> @hongnod Do you see anything obviously wrong with the screenshot attached above?
good.thanks for supporting go
