### ISSUE TITLE
Unable to locate dark mode options in Flatpak

### ISSUE THREAD

**Issue by Exist2Resist** [dail8859/NotepadNext#508]
Running NotepadPlus on Fedora 39, my default theme is dark in the OS and this is reflected in NotepadNext in the menu bar, but I can not find the option for dark mode for the file tabs. 

Is there not an option for this?

**Comment by dail8859** [comment]
> Is there not an option for this?

No.

**Comment by Exist2Resist** [comment]
> > Is there not an option for this?
> 
> No.

Is there a plan for this?

**Comment by dail8859** [comment]
See #407 as there has been some interest/work done on a dark mode. I need to find time to review the PR for this and see what I can do.

Closing in favor of #407
