### ISSUE TITLE
Scroll to currently selected tab on app open

### ISSUE THREAD

**Issue by dzek69** [dail8859/NotepadNext#509]
When i have way too many tabs open and I start Notepad Next - the current (in my example - last) tab is opened but the tab bar is scrolled to the left.

It looks like this:
![image](https://github.com/dail8859/NotepadNext/assets/4936805/22a30f88-7b8d-4c8a-ab16-27d58590b9fe)

When I use the dropdown to select one of the hidden tabs Notepad Next scrolls the tab bar correctly:
![image](https://github.com/dail8859/NotepadNext/assets/4936805/5aaa2b38-05ad-4fa9-9457-2763bff0384e)
(this however does not happen if I select a tab that's already opened)

NN should take care of scrolling the tab bar on app start

**Comment by dail8859** [comment]
I've noticed this as well but never took the time to investigate. My assumption is this is something the [githubuser0xFFFF/Qt-Advanced-Docking-System](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System) would have to fix since that's currently what I'm using for tab management. I guess there's a slight possibility this can be fixed on the application side but not sure.

**Comment by dail8859** [comment]
What version of Notepad Next are you using? And is this the flatpack or appimage?

I know I've seen this behavior before but I've tried quite a bit and can't replicate it now.

**Comment by dzek69** [comment]
Flatpak, 0.6.4

So it works fine for you, I mean it scrolls to the correct/last tab on app start?

**Comment by dail8859** [comment]
It does. I'm on Windows and using latest master branch which has some updates from the advanced docking system library.

**Comment by dail8859** [comment]
You might try installing the soon-to-be released 0.7 version.

> flatpak install --user https://dl.flathub.org/build-repo/84906/com.github.dail8859.NotepadNext.flatpakref

**Comment by dzek69** [comment]
New version solves this issue, nice!

**Comment by dail8859** [comment]
Awesome!
