### ISSUE TITLE
Tab bar should be scrollable with horizontal scroll gesture on touchpad/mouse

### ISSUE THREAD

**Issue by dzek69** [dail8859/NotepadNext#510]
When I hover the tab bar like that:
![image](https://github.com/dail8859/NotepadNext/assets/4936805/7ab0df40-ddcd-4a56-a683-0c8c8e4b9a3a)

I'd be great to be able to scroll it using touchpad gesture of horizontal scroll or using mouse that has horizontal scroll feature.

Personally I think it'd allow me to find the right tab much faster than the dropdown arrow on the right of the tabs.

Thanks in advance!

**Comment by dail8859** [comment]
Again probably something the [githubuser0xFFFF/Qt-Advanced-Docking-System](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System) that would need implemented.

**Comment by dail8859** [comment]
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/607

**Comment by dail8859** [comment]
Looks like the maintainer of the library is not willing to address it even though it looks like it was implemented at one time.

There are hooks in the library to override some of the controls so if I have some time, I might try custom controls and implement it that way.

**Comment by dzek69** [comment]
It is sad that maintainer does not want this feature.
I'd be cool if you could still implement it, but I understand it might be not possible.

**Comment by dail8859** [comment]
I took a shot at it yesterday and still no luck. It's odd because `CDockAreaTabBar` is a `QScrollArea` which by default should be scrollable. As noted in the issue something else seems to be handling the `QWheelEvent`s and not letting them propagate to the `CDockAreaTabBar`. There's also a `CDockAreaTitleBar` in the mix. I'm no Qt expert so I can't really guess as to any good solutions. 🤷

**Comment by dail8859** [comment]
Looks like this might have been fixed in https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/654 but I need to pull in latest changes from there and test.
