### ISSUE TITLE
Add Polish translation template

### ISSUE THREAD

**Issue by kocio-pl** [dail8859/NotepadNext#517]
Hi, I'd like to make Polish translation, please add the template to make it possible.

**Comment by dail8859** [comment]
Sure! Could you post the first 10 lines or so under Help > Debug Log

That will show me exactly what country/territory it is trying to load.

**Comment by kocio-pl** [comment]
[     0.233] I: =============================
[     0.233] I: Notepad Next v0.7 (Flatpak)
[     0.233] I: Build Date/Time: Feb 26 2024 15:42:27
[     0.233] I: Qt: 5.15.10
[     0.233] I: OS: KDE Flatpak runtime
[     0.233] I: Locale: pl_PL
[     0.233] I: CPU: x86_64
[     0.233] I: File Path: /app/bin/NotepadNext
[     0.233] I: Arguments: NotepadNext
[     0.233] I: =============================
