### ISSUE TITLE
Supporting Arabic lang

### ISSUE THREAD

**Issue by shawkynasr** [dail8859/NotepadNext#518]
@dail8859 thanks for great tool.

I found app doesn't support Arabic yet.

I can't read or write Arabic with it.

**Comment by dail8859** [comment]
I'm not an Arabic user at all so don't know the first thing about supporting various languages such as Arabic so hopefully someone else will be able to offer some help.

**Comment by dail8859** [comment]
Thanks for your valuable input @diegoiast 

Since that is definitively the case that Scintilla would need modifications then I agree that it is best to close this.
