### ISSUE TITLE
Add command-line argument to open to a line number in a file like notepad++

### ISSUE THREAD

**Issue by erg** [dail8859/NotepadNext#528]
Notepad++ and many editors have a command-line argument that opens to a line number,  e.g. this command opens `README.md` to line 20:

``
notepad++ README.md -n 20
``

This is useful for editor integration into programming languages like [Factor's notepad++ integration](https://github.com/factor/factor/blob/master/basis/editors/notepad%2B%2B/notepad%2B%2B.factor#L16)

**Comment by japanoise** [comment]
Most unix text editors (including [vim(1)](https://manpages.org/vim), [emacs(1)](https://manpages.org/emacs), and [nano(1)](https://manpages.org/nano)) accept line numbers from a command line argument with a `+`, so that they can be invoked from [less(1)](https://manpages.org/less):

```
       The  prompt expansion features are also used for another purpose: if an
       environment variable LESSEDIT is defined, it is used as the command  to
       be  executed when the v command is invoked.  The LESSEDIT string is ex‐
       panded in the same way as the prompt strings.  The  default  value  for
       LESSEDIT is:

            %E ?lm+%lm. %g

       Note that this expands to the editor name, followed by a + and the line
       number,  followed  by the shell-escaped file name.  If your editor does
       not accept the "+linenumber" syntax, or has other differences in  invo‐
       cation  syntax, the LESSEDIT variable can be changed to modify this de‐
       fault.
```

## vim

```
+[num]
    For the first file the cursor will be positioned on line "num". If "num" is 
    missing, the cursor will be positioned on the last line.
```

## emacs

```
              +number 
                      Go to the line specified by  number  (do  not  insert  a
                      space  between  the  "+" sign and the number).  This ap‐
                      plies only to the next file specified.

              +line:column
                      Go to the specified line and column.
```

## nano

```
+line,column
    Places the cursor on line number line and at column number column (at least 
    one of which must be specified) on startup, instead of the default line 1, column 1. 
```

**Comment by dail8859** [comment]
I agree both the `-n` and the `+n` are useful. However, a quick glance shows the [`QCommandLineParser`](https://doc.qt.io/qt-6/qcommandlineparser.html) does not have any way to support something like a `+n` feature I'm aware of.

**Comment by dail8859** [comment]
`-n` has been added. As mentioned, the QCommandLineParser doesn't seem to support the ability for `+n`. I still think it would be nice but not worth trying to implement a custom parser.

**Comment by dail8859** [comment]
@erg 

Just FYI I saw in: https://github.com/factor/factor/blob/master/basis/editors/notepadnext/notepadnext.factor

That it references the bundle ID. It recently just changed to `io.github.dail8859.NotepadNext` in https://github.com/dail8859/NotepadNext/commit/082a1c29f0327ac7e76d2ec9418d8d4e077f7d2a

**Comment by erg** [comment]
Thanks! We now support both bundle ids and use `-n` in the newer one.

https://github.com/factor/factor/commit/fc37964b77c1ac58eab8d18dc7ec17fcd635a054
