### ISSUE TITLE
Error: CreateDXGIFactory2 at dxgi.dll

### ISSUE THREAD

**Issue by sonichy** [dail8859/NotepadNext#530]
WIN7

**Comment by dail8859** [comment]
Notepad Next by default uses Qt 6.5 which does not support Windows 7.

Notepad Next however can still be built with Qt 5.15 which should support Windows 7. You can download one of the artifacts from the GitHub action. Here is the latest Windows installer using Qt 5.15 which _should_ work for you: https://github.com/dail8859/NotepadNext/actions/runs/8472970611/artifacts/1368002658

But please keep in mind. This is not officially supported, and I cannot ensure it will work as expected. I won't be addressing any issues specifically related to Windows 7 and PRs to fix these issues will only be accepted if they are minimal changes.

**Comment by sonichy** [comment]
The link above is still build with Qt 6.5.

**Comment by dail8859** [comment]
Oops! My bad.

Try this link :)

https://github.com/dail8859/NotepadNext/actions/runs/8487606195/artifacts/1370952153

**Comment by sonichy** [comment]
Good news !
https://github.com/vxiiduu/VxKex support run WIN10 applications on WIN7 !
I tested NotepadNext work fine.
