### ISSUE TITLE
Can't open large txt files (~100GiB)

### ISSUE THREAD

**Issue by phant** [dail8859/NotepadNext#532]
After opening nothing happened.
NotepadNext-v0.7-win64
Debug log:
![npn](https://github.com/dail8859/NotepadNext/assets/805222/e8097371-dd1c-4c21-9575-e0140fdf4466)

**Comment by dail8859** [comment]
For now something like this just won't be supported. Maybe someday, but even if it could open a file that large there are numerous other parts of the application that would need optimized.
