### ISSUE TITLE
fetch-pack: unexpected disconnect while reading sideband packet

### ISSUE THREAD

**Issue by PRFinklemeister** [dail8859/NotepadNext#533]
Honestly I don't know if this is on my side or GitHub or something else but it is repeating.
```
git clone https://github.com/dail8859/NotepadNext.git
Cloning into 'NotepadNext'...
remote: Enumerating objects: 9553, done.
remote: Counting objects: 100% (1904/1904), done.
remote: Compressing objects: 100% (733/733), done.
error: RPC failed; curl 16 Error in the HTTP2 framing layer
error: 7462 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

Ubuntu 22.04.4 LTS \n \l

**Comment by dail8859** [comment]
I've never seen errors like that. I'm not able to clone it myself right now but I'd assume it is not something I can control. It may be a temporary issue, or some type of proxy, etc.

One suggestion I found is to force it to use HTTP1.1: https://stackoverflow.com/a/72987945

I'll leave this open for now incase someone else runs into this issue or there is something I'm able to control. If I don't hear anything back after a few days I'll close it.
