### ISSUE TITLE
Find/Replace dialog UI arrangement issues for Mac Version

### ISSUE THREAD

**Issue by ErickWei** [dail8859/NotepadNext#535]
Wish that the dialog box could be updated to be as perfectly arranged as the one in Windows

The main problem is that the widths of the textboxes/combobox are not consistent and they are not left-aligned

MAC OS:
<img width="600" alt="image" src="https://github.com/dail8859/NotepadNext/assets/62826892/51f54865-50a7-4aa1-abbb-b5c47d374bcd">
<img width="600" alt="image" src="https://github.com/dail8859/NotepadNext/assets/62826892/39c80e49-10d1-48a2-aa2f-170737728985">

Windows:
<img width="603" alt="image" src="https://github.com/dail8859/NotepadNext/assets/62826892/cc3fb92c-df49-4096-a533-caee2e707dc2">

**Comment by dail8859** [comment]
I don't have a Mac to develop/test on so hopefully somebody can submit a PR. My guess is something with the layouts just need tweaked.

**Comment by ErickWei** [comment]
Debug on macos,but get an error,Do you have any suggestions on how to solve this issue?

<img width="944" alt="image" src="https://github.com/dail8859/NotepadNext/assets/62826892/72cc34f5-ef74-4725-bae2-bc44fd8217ba">

**Comment by dail8859** [comment]
I'm assuming you also checked out the submodules?

> git clone --recurse-submodules https://github.com/dail8859/NotepadNext.git

I know it is possible to build with mac but beyond that I'm not sure.

**Comment by ErickWei** [comment]
Just update 4 property of formLayout.
**- layoutLableAlignment-Horizontal:AlignLeft
- layoutFormAlignment-Horizontal:AlignJustify
- layoutSizeConstraint:SetNoConstraint
- layoutFieldGrowthPolicy:First change to ExpandingFieldGrow then change back to AllNonFixedFieldsGrow, and **AllNonFixedFieldsGrow** is the final value.
**

I have tested both on Windows and Mac, and there is no problem.

<img width="656" alt="image" src="https://github.com/dail8859/NotepadNext/assets/62826892/71fb5aa6-0d75-4ed6-ae8e-41155ce301ea">

<img width="600" alt="image" src="https://github.com/dail8859/NotepadNext/assets/62826892/9415e09b-2734-4b9d-90d2-8c3613d0a2fb">


But there is one thing to note, when I clone the repository to mac and windows, and open the project with qt, the values of the two property below are different:
MAC:
- layoutLableAlignment-Horizontal:AlignRight
- layoutFormAlignment-Horizontal:AlignHCenter
WINDOWS:
- layoutLableAlignment-Horizontal:AlignLeft
- layoutFormAlignment-Horizontal:AlignLeft

**Comment by dail8859** [comment]
Can you create a PR for whatever works on Mac and I can review it on Windows and make sure it still looks ok?

**Comment by ErickWei** [comment]
> Can you create a PR for whatever works on Mac and I can review it on Windows and make sure it still looks ok?

Okay,wait for me

**Comment by dail8859** [comment]
Closed by #538
