### ISSUE TITLE
[Bug] When show status bar is set to false, does not take effect after application restart

### ISSUE THREAD

**Issue by ErickWei** [dail8859/NotepadNext#536]
When "show status bar" is set to false, then I close the app and reopen it, status bar still shows, and then I open Setting window, "show stats bar" is shown as false.
So the current program logic may not be able to remember this setting and needs to be fixed.
I have tried in both windows and mac, and both systems have this problem.

MAC OS:
<img width="855" alt="image" src="https://github.com/dail8859/NotepadNext/assets/62826892/7d1aee78-8e0f-4ffd-a42a-04f20224f77e">

Windows:
<img width="865" alt="image" src="https://github.com/dail8859/NotepadNext/assets/62826892/412bf21c-579c-4f01-a40f-8b57cbacd2b9">

**Comment by dail8859** [comment]
Can confirm that the setting `Gui/ShowStatusBar` is getting set correctly in the config file, so on launch it is not respecting it for some reason.

The status bar is a custom implementation...not sure if that has something to do with it or not. Will take a look when I get some free time.
