### ISSUE TITLE
Exit the Application when the last tab closed

### ISSUE THREAD

**Issue by ErickWei** [dail8859/NotepadNext#539]
Add an option[Exit on close the last tab], when this option checked, quit the entire app after closes the last tab

**Comment by dail8859** [comment]
The preference dialog with obviously need a good overhaul at some point soon once there's enough settings on there.

**Comment by ErickWei** [comment]
Yes, I originally wanted to do some optimization adjustments, but there are relatively few settings, so it is not necessary at present

> The preference dialog with obviously need a good overhaul at some point soon once there's enough settings on there.
