### ISSUE TITLE
Better Linux Screenshot

### ISSUE THREAD

**Issue by dail8859** [dail8859/NotepadNext#545]
It would be great if some kind soul could update the Linux screenshot to something more polished than what is currently there.

[doc/screenshot_linux.png](https://github.com/dail8859/NotepadNext/blob/master/doc/screenshot_linux.png)

If it was similar to the Windows one, that would be even better :)

[doc/screenshot.png](https://github.com/dail8859/NotepadNext/blob/master/doc/screenshot.png)

**Comment by japanoise** [comment]
Hi there - here's a screenshot similar to the windows one. I don't have access to the exact right files, but I think this is similar enough:

![linux-notepad](https://github.com/dail8859/NotepadNext/assets/14792164/df0d36fd-ceb2-48ef-b737-8692d3f49a8a)

**Comment by japanoise** [comment]
Hi there - would this work? I tried to get it looking close to the Windows screenshot.

![linux-notepad](https://github.com/dail8859/NotepadNext/assets/14792164/77338bd8-81d7-4caa-9476-9f0ae61fd698)

**Comment by japanoise** [comment]
ICYMI - I updated my PR with the requested changes to the screenshot a few days ago.
