### ISSUE TITLE
[feature request] temporarily store files when close 'x' button for window is pressed

### ISSUE THREAD

**Issue by a-sajjad72** [dail8859/NotepadNext#547]
I had used notepad++ in windows. but now I'm on Linux. Notepad Next is a great cross-platform implementation of Notepad++. In Notepad++ we have a feature when the close button 'x' for window is pressed the window closes without any dialogs and when reopening the notepad++ the files wouldn't vanish. When the close 'x' button for a specific file is pressed then it shows the dialog to save.
We need a feature just like that. It is a great feature.

**Comment by dail8859** [comment]
This has been available since v0.6

Settings -> Preferences:
- [x] Restore previous session
- [x] Unsaved changes
- [x] Temporary files
