### ISSUE TITLE
Remove Overtype functionality

### ISSUE THREAD

**Issue by dail8859** [dail8859/NotepadNext#55]
I honestly can't think of any valid use-case that overtype adds to a text editor. Users of Notepad++ seem to find it more confusing than anything.

**Comment by MAPJe71** [comment]
@dail8859 
I use the 'overwrite' functionality a lot in other editors.
Is there a different/alternative way to overwrite existing text with NotepadNext?

**Comment by dail8859** [comment]
Currently there's no other way.

I know I've rarely (maybe never?) had a need for this so didn't find it of any value _to me_. I know I've seen more than a couple forum posts people getting confused about why they can no longer insert text.

That being said if there is value to other users then that's fine. I'm not opposed to adding the functionality back in if there is a valid use case.
