### ISSUE TITLE
Flatpak depends on EOL version of KDE 6.5 

### ISSUE THREAD

**Issue by yaumeister** [dail8859/NotepadNext#565]
### Operating System and Version

Ubuntu 22.04

### Distribution

flathub

### Description

When performing an update from flathub, error appears about NotepadNext dependency on EOL KDE 6.5

### Steps to Reproduce

1. Run "flatpak update" from console

### Additional Details

Looking for updates…
Info: org.kde.Platform//6.5 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Applications using this runtime:
   com.github.dail8859.NotepadNext

**Comment by dail8859** [comment]
See the discussion on #550

In short there are 3rd party libraries that do not work on Qt6.6+ yet, so we are stuck with 6.5 for now. Other than getting the strongly worded warning, there's really no concern to stay with 6.5 currently.
