### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by rendgineer** [dail8859/NotepadNext#566]
### Operating System and Version

Fedora 40

### Distribution

Flathub

### Description

Russian translation doesn't work.

**Comment by dail8859** [comment]
Can you open the Help > Debug Log window and paste the first 10 lines or so. That will help with initial troubleshooting.

**Comment by rendgineer** [comment]
[     0.344] I: =============================
[     0.344] I: Notepad Next v0.7 (Flatpak)
[     0.344] I: Build Date/Time: Apr 12 2024 18:32:13
[     0.344] I: Qt: 6.5.3
[     0.344] I: OS: KDE Flatpak runtime
[     0.344] I: Locale: ru_RU
[     0.344] I: CPU: x86_64
[     0.344] I: File Path: /app/bin/NotepadNext
[     0.344] I: Arguments: NotepadNext
[     0.344] I: =============================
[     0.344] I: bool NotepadNextApplication::init()
[     0.359] I: void TranslationManager::loadTranslation(QLocale)
[     0.359] I: ru_RU translation not found for Notepad Next
[     0.359] I: ru_RU translation not found for Qt components
[     0.359] I: LuaState::LuaState()
[     0.367] I: MacroManager::MacroManager(QObject*)
[     0.367] I: void MacroManager::loadSettings()
[     0.367] I: MainWindow::MainWindow(NotepadNextApplication*)
[     0.398] I: setupUi Completed
[     0.413] I: FileListDock::FileListDock(MainWindow*)
[     0.413] I: void MainWindow::setupLanguageMenu()
[     0.420] I: void MainWindow::restoreSettings()
[     0.420] I: void NotepadNextApplication::openFiles(const QStringList&)
[     0.420] I: void MainWindow::newFile()
[     0.421] I: void EditorManager::setupEditor(ScintillaNext*)
[     0.421] I: void MainWindow::addEditor(ScintillaNext*)
[     0.421] I: void MainWindow::detectLanguage(ScintillaNext*)
[     0.421] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
[     0.421] I: Language Name: Text
[     0.421] I: void DockedEditor::addEditor(ScintillaNext*)
[     0.436] I: void MainWindow::activateEditor(ScintillaNext*)
[     0.436] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[     0.436] I: void MainWindow::updateGui(ScintillaNext*)
[     0.436] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
[     0.436] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[     0.436] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
[     0.436] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)
[     0.770] I: Scintilla::Internal::RegexSearchBase* Scintilla::Internal::CreateRegexSearch(CharClassify*)
[     0.816] I: void MainWindow::focusIn()
[     0.816] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[    14.686] I: void MainWindow::focusIn()
[    14.687] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[    35.428] I: void MainWindow::focusIn()
[    35.428] I: bool MainWindow::checkFileForModification(ScintillaNext*)

**Comment by dail8859** [comment]
The Russian translation is not in Notepad Next v0.7. It will be available in the next release.
