### ISSUE TITLE
Does Not Start On 'Open with...' ... With Session Resume On

### ISSUE THREAD

**Issue by influential-eliot** [dail8859/NotepadNext#567]
### Operating System and Version

Debian 12 Wayland Gnome

### Distribution

flathub

### Description

_You can close this immediately but keep it as an instance of the issue, perhaps? (see 'work around' section)_

# **Incident** - NotepadNext Does Not Open A File Directly With Session Resumption
I noticed that when I tried to start NotepadNext from by using 'open with' in Debian it was not starting.

# **Work Around** - Set Resume Session To `FALSE`
I found the settings .ini file and edited the option to resume session to `FALSE` and this allowed me back into the program again.

### Steps to Reproduce

1. Ensure that you have the session resumption option turned on in the NotepadNext options
2. Try to right click a file and open with NotepadNext
3. Watch it not open

### Additional Details

# **Investigation**
I initially tried starting it straight from the shortcut, instead. But this also didn't work.

So, I ensured that all instances of the process were closed, and that the flatpak helper was closed, too. Then tried the shortcut again. Still no joy.

This left me trying to run the flatpak from terminal. 

There I noticed that there was something (_sorry, lost it now_) about the session resumption going on.

# **Future Incidents**
If I see this happening again in the future, I'll try to capture more information for you. 👍

**Comment by dail8859** [comment]
> edited the option to resume session to FALSE

Are you specificalyl talking about `RestorePreviousSession`?

Something within the `[CurrentSession]` section may have gotten corrupted and the application is not properly handling that case.

The application does generate an active debug log within the application while running. There's also ways to get the log to print to the console but not sure how exactly to do it with flatpak on linux.

If you do happen to get any additional info, that would be appreciated. Thanks for bringing this up.

**Comment by Leihousuo** [comment]
Ensure that you have the session resumption option turned on in the NotepadNext options
👆 ty for let me know that "session resumption option",great help<
