### ISSUE TITLE
Key Rebindings / Shortcuts Remappings ?

### ISSUE THREAD

**Issue by crimsonduelist** [dail8859/NotepadNext#569]
### Description

Would be nice to have the ability to bind some shortcuts like ctrl+y to ctrl+shift+z
Sry if this is possible through config file and I missed it (if so that s more than enough - do not need gui/menu options so long as it can be set)

### Describe the solution you'd like

Simply the ability to remap shortcuts through a config file like ~/.config/NotepadNext/NotepadNext.ini

**Comment by dail8859** [comment]
I've  merged in changes that will allow the ini file to be manually edited (probably best to use some other editor).

Adding a `[Shortcuts]` section in the ini file will override the default shortcuts. https://doc.qt.io/qt-6/qkeysequence.html#QKeySequence-1 is used to parse out the shortcut string. E.g.

```ini
[Shortcuts]
New=Ctrl+F1
```

The best place to get the list of actions available is probably here: https://github.com/dail8859/NotepadNext/blob/d43e033743f603e5fb1bcc3ae7abf77e8682d1a9/src/NotepadNext/dialogs/MainWindow.ui

So if you find something like "actionSaveAll" you can use the string "SaveAll" in the ini file.

---

**Please note**: This is all subject to change in the future but for now this will give people a way to override shortcuts.
