### ISSUE TITLE
realloc(): invalid pointer

### ISSUE THREAD

**Issue by lv913** [dail8859/NotepadNext#570]
### Operating System and Version

Ubuntu 24.04

### Distribution

App Center

### Description

I have installed Notepad Next latest/stable v0.7 using GUI interface from Ubuntu's App Center.
After installation, I have tried to open the application via menu icon but it does nothing.
Launching it from a terminal, I receive the following output:

> $ notepadnext 
> [     0.000] I: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
> [     0.020] I: =============================
> [     0.020] I: Notepad Next v0.7 (Snap)
> [     0.020] I: Build Date/Time: Apr 11 2024 09:47:38
> [     0.020] I: Qt: 5.15.3
> [     0.020] I: OS: Ubuntu 24.04 LTS
> [     0.020] I: Locale: it_IT
> [     0.020] I: CPU: x86_64
> [     0.020] I: File Path: /snap/notepadnext/13/usr/bin/NotepadNext
> [     0.020] I: Arguments: /snap/notepadnext/13/usr/bin/NotepadNext
> [     0.020] I: =============================
> [     0.020] I: bool NotepadNextApplication::init()
> [     0.028] I: void TranslationManager::loadTranslation(QLocale)
> [     0.028] I: LuaState::LuaState()
> [     0.042] I: MacroManager::MacroManager(QObject*)
> [     0.042] I: void MacroManager::loadSettings()
> [     0.042] I: MainWindow::MainWindow(NotepadNextApplication*)
> [     0.060] I: setupUi Completed
> [     0.074] I: FileListDock::FileListDock(MainWindow*)
> [     0.074] I: void MainWindow::setupLanguageMenu()
> [     0.079] I: void MainWindow::restoreSettings()
> [     0.079] I: void NotepadNextApplication::openFiles(const QStringList&)
> [     0.079] I: void MainWindow::newFile()
> [     0.079] I: void EditorManager::setupEditor(ScintillaNext*)
> [     0.080] I: void MainWindow::addEditor(ScintillaNext*)
> [     0.080] I: void MainWindow::detectLanguage(ScintillaNext*)
> [     0.080] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
> [     0.080] I: Language Name: Text
> [     0.080] I: void DockedEditor::addEditor(ScintillaNext*)
> realloc(): invalid pointer
> Annullato (core dump creato)
> 

### Steps to Reproduce

1. Install Notepad Next from App Center in Ubuntu 24.04
2. Open a terminal
3. Launch command `notepadnext` and check the output

### Additional Details

e.g. screenshots, logs, etc

**Comment by dail8859** [comment]
The snap pack is not officially supported by this repo but I do know it's one way to install it. I've not heard of any other Linux users with this issue so it might be snap related. @popey might have some insight

**Comment by dail8859** [comment]
I'll close this for now. Nobody else has reported any issues or offered help, so it sounds like it is an isolated problem.

**Comment by popey** [comment]
Apologies for missing your ping. 

I have reproduced this issue and am trying a build with an additional library to fix it.
