### ISSUE TITLE
Unable to upgrade from v0.7 -> v0.8

### ISSUE THREAD

**Issue by Brishakar** [dail8859/NotepadNext#583]
### Operating System and Version

Nobara 40

### Distribution

flathub

### Description

When trying to install update v0.7 -> v0.8 in Discover, I get the below error message.
 
![Screenshot_20240629_070109](https://github.com/dail8859/NotepadNext/assets/110136494/0e1df69c-9f2d-4257-a62e-ed331bb85411)

Clicking cancel shows this second box.
![Screenshot_20240629_070547](https://github.com/dail8859/NotepadNext/assets/110136494/d0554614-7957-489c-9b47-25fd0c0ccd78)

If i click proceed Discover crashes.

Happy to provide any details you need.
![Screenshot_20240629_070738](https://github.com/dail8859/NotepadNext/assets/110136494/a1383d41-72bd-43e7-bf2d-53893515b989)

### Steps to Reproduce

1. Open Discover
2. Click Update All.
3. Messages thrown as listed in the description.

### Additional Details

e.g. screenshots, logs, etc

**Comment by dail8859** [comment]
Qt 6.5 is still the version being used despite the warning.

@zocker-160 Thoughts on this particular situation?

**Comment by Brishakar** [comment]
I should also add that if I you click continue, it crashes Discover.  I dont think that it's related, but worth mentioning.

**Comment by zocker-160** [comment]
@dail8859 I don't see anything actionable here. 
This is a bug in Discover, the package is perfectly valid and updating / installing via command line does work fine.

**Comment by dail8859** [comment]
@zocker-160 Thank you for your input as always!

@Brishakar I'll close this for now as it does not appear there's any way to fix it from the app/flatpak end. If the Discover devs have any input or suggestions then please let us know.

**Comment by Brishakar** [comment]
No worries.  Thanks for the quick action.
