### ISSUE TITLE
flatpak uses eol org.kde.Platform branch 6.5

### ISSUE THREAD

**Issue by ericjs** [dail8859/NotepadNext#584]
### Operating System and Version

openSUSE Tumbleweed, snapshot 20240629

### Distribution

flatpak

### Description

the flatpak uses an end-of-life runtime, org.kde.Platform branch 6.5

### Steps to Reproduce

See https://flathub.org/apps/com.github.dail8859.NotepadNext

**Comment by dail8859** [comment]
See #550 and #565

Necessary upstream libraries do not support Qt6.6 and above yet.
