### ISSUE TITLE
Cannot switch input method

### ISSUE THREAD

**Issue by xingyankai** [dail8859/NotepadNext#585]
### Operating System and Version

deepin v23 rc2

### Distribution

AppImage

### Description

Cannot switch input method, I Using Chinese Input Method, input method engine is fcitx5

### Steps to Reproduce

1. 
2. 
3. 

### Additional Details

e.g. screenshots, logs, etc

**Comment by dail8859** [comment]
Thanks for reporting this.

According to #218, it looks like it is possible to compile it and support fcitx5 but I don't use Linux or any type of different input methods, so I am not able to fix this myself. Someone else would have to contribute any changes.

If there's any relevant information or additional questions I would suggest posting on #218.

Closing as a duplicate.
