### ISSUE TITLE
Enable CFG in VS2019 project

### ISSUE THREAD

**Issue by asvc** [dail8859/NotepadNext#6]
Checking the latest artefact from AppVeyor, v0.3.0.68:

```powershell
> Get-PESecurity -File .\NotepadNext.exe

ARCH             : AMD64
DotNET           : False
ASLR             : True
DEP              : True
Authenticode     : False
StrongNaming     : N/A
SafeSEH          : N/A
ControlFlowGuard : False  <-- CFG
HighentropyVA    : True
```

Could you please try building with the [`/guard:cf`](https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=vs-2019)?

**Comment by dail8859** [comment]
You can try this build: https://ci.appveyor.com/project/dail8859/notepadnext/builds/34049116/artifacts

**Comment by asvc** [comment]
Checked, works!

![image](https://user-images.githubusercontent.com/300146/87248084-9ad4d780-c496-11ea-95c7-86d627f3b9b3.png)
