### ISSUE TITLE
flatpak message org.kde.Platform//6.5 is end-of-life

### ISSUE THREAD

**Issue by victor03303** [dail8859/NotepadNext#605]
### Operating System and Version

Lubuntu 22.04

### Distribution

flatpak

### Description

# When updating my flatpaks, flatpak returns this message:

```
Info: org.kde.Platform//6.5 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Applications using this runtime:
   com.github.dail8859.NotepadNext
```

### Steps to Reproduce

1. flatpak update

### Additional Details

e.g. screenshots, logs, etc

**Comment by dail8859** [comment]
See #584, https://github.com/dail8859/NotepadNext/issues/550 and https://github.com/dail8859/NotepadNext/issues/565
