### ISSUE TITLE
rename cmd name NotepadNext to notepad-next

### ISSUE THREAD

**Issue by zoujiaqing** [dail8859/NotepadNext#614]
### Description

rename cmd name NotepadNext to notepad-next or notepadnext.

On unix systems the command specification is all lowercase. Includes macOS/FreeBSD/Linux and other systems.

**Comment by dail8859** [comment]
How did you install the application? Flathub? AppImage? etc?

**Comment by zoujiaqing** [comment]
brew install

**Comment by dail8859** [comment]
@woj-tek Thoughts on this?

**Comment by dail8859** [comment]
Is there a preference of `notepad-next` vs `notepadnext`?

The only reason I ask is on Windows you can run `start notepadnext` and figured if there's no real reason to keep the `-` then we can keep things consistent. But if for Mac/unix/etc users if `notepad-next` is more natural that's fine too.

**Comment by dail8859** [comment]
@woj-tek Thanks for looking into this!

Closed by https://github.com/dail8859/homebrew-notepadnext/pull/1
