### ISSUE TITLE
Please add the option to edit the word character list

### ISSUE THREAD

**Issue by rafal-1990** [dail8859/NotepadNext#619]
### Description

Hi, I am a system administrator and workig much with FQDNs.

The main reason I used Notepad++under Windows was that it allows you to customize the word character list and add a dot to it. This way, when you double-click on a server name with a fully quallified domain name, the whole name (including domain) is marked. I would really love it if this feature was available in NotepadNext!

Could you please implement this as soon as possible? 
If this function were available, I would finally have a usable and fantastic editor under Linux.
Many thanks in advance!

### Describe the solution you'd like

In Notepad++ you can configure this in the following place: "_Settings/Preferences.../Delimiter -> Add your character as part of a word_". In the config.xml it looks like this:
`<GUIConfig name="wordCharList" useDefault="no" charsAdded="." />`

### Describe alternatives you've considered

It does not necessarily have to be in the GUI. If I could set the option in the config file, I would be happy.

**Comment by dail8859** [comment]
I've added in the option to specify it in the config file for now. You can open your ini file with a different text editor and add it in the `Editor` tag, something like this:

```ini
[Editor]
AdditionalWordChars=.
```

**Comment by rafal-1990** [comment]
Many thanks for the quick implementation of this for me essential feature.

Are there any other ways (e.g. PayPal) to donate money to you, apart from sponsoring via github (as I don't want to share so much personal data with github)?

**Comment by dail8859** [comment]
> Are there any other ways (e.g. PayPal) to donate money to you

There's not. I totally understand and appreciate the offer though.
