### ISSUE TITLE
Cannot open the 2nd files with the same name but in different folders

### ISSUE THREAD

**Issue by hzh-hzh** [dail8859/NotepadNext#621]
### Description

Cannot open the 2nd file with the same name but in different folders. I can open the 1st file with name as "xxx.txt" for example, but cannot open the 2nd file with the same name in another folder.

**Comment by dail8859** [comment]
Can you provide your exact steps and more deatils? E.g. errors, etc? Also paste the information under `Help > Debug Log`

It works for me:
![image](https://github.com/user-attachments/assets/766c2e4d-256c-4bd7-b861-7f9bc26e1fee)
