### ISSUE TITLE
Backward direction not work in Find 

### ISSUE THREAD

**Issue by accessv** [dail8859/NotepadNext#628]
### Operating System and Version

macOs

### Distribution

brew

### Description

With and without the selection of the "Backward direction" in the Find dialog window, the search will be only in the forward direction.

### Steps to Reproduce

1. open the Find window (command + F) 
2. set finding pattern
3. set check on Backward direction 
4. the search will be in a forward direction 

### Additional Details

e.g. screenshots, logs, etc

**Comment by dail8859** [comment]
@accessv Could you open a PR with these changes? I'd be happy to review/test!

**Comment by dail8859** [comment]
Closed by #635
