### ISSUE TITLE
org.kde.Platform branch 6.5 is end-of-life

### ISSUE THREAD

**Issue by burtadjoodani** [dail8859/NotepadNext#629]
### Description

Info: runtime org.kde.Platform branch 6.5 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   com.github.dail8859.NotepadNext

### Describe the solution you'd like

Make org.kde.Platform branch 6.6 the version NotepadNext Uses in Linux, install that version and not the old 6.5 version.

### Describe alternatives you've considered

Put newer version as allowed instead of installing the old version 6.5.

**Comment by dail8859** [comment]
See pinned issue https://github.com/dail8859/NotepadNext/issues/584

6.5 is going to be used for now.
