### ISSUE TITLE
A bug when I use the debug mode.

### ISSUE THREAD

**Issue by zdmdz** [dail8859/NotepadNext#63]
Windows 10
QtCreator-qt5.15.2
msvc2019
debug mode
When I try to run the application:
![屏幕截图 2022-01-24 210338](https://user-images.githubusercontent.com/85682840/150797416-6bfe4746-e72d-411e-8eed-73996e45981f.png)

**Comment by zdmdz** [comment]
Oh I forgot the log.

[     0.091] I: =============================

[     0.091] I: NotepadNext v0.4.6.0

[     0.092] I: Qt: 5.15.2

[     0.092] I: OS: Windows 10 Version 2009

[     0.093] I: CPU: x86_64

[     0.093] I: File Path: D:/code/NotepadNext/build-NotepadNext-msvc2019-Debug/NotepadNext

/NotepadNext.exe

[     0.093] I: Arguments: D:\code\NotepadNext\build-NotepadNext-msvc2019-Debug\NotepadNext

\NotepadNext.exe

[     0.093] I: =============================

[     0.093] I: bool __cdecl NotepadNextApplication::initGui(void)

[     0.093] I: __cdecl LuaState::LuaState(void)

[     0.165] I: __cdecl MainWindow::MainWindow(class NotepadNextApplication *)

[     0.334] I: setupUi Completed

[     0.482] I: void __cdecl MainWindow::setupLanguageMenu(void)

[     1.636] I: void __cdecl MainWindow::restoreSettings(void)

[     1.807] I: void __cdecl NotepadNextApplication::applyArguments(const class QStringList &)

[     1.807] I: void __cdecl MainWindow::newFile(void)

[     1.811] I: void __cdecl EditorManager::setupEditor(class ScintillaNext *)

[     1.820] I: void __cdecl MainWindow::addEditor(class ScintillaNext *)

[     1.821] I: void __cdecl MainWindow::detectLanguage(class ScintillaNext *)

[     1.821] I: void __cdecl MainWindow::setLanguage(class ScintillaNext *,const class QString &)

[     1.821] I: Language Name: Text

[     1.822] W: Scintilla: Assertion [start + len <= lengthDoc] failed at ..\..\src\scintilla\src\Document.cxx 77

**Comment by dail8859** [comment]
Closing since changes would have to be made the Lexilla project and they do not seem concerned with the issue.
