### ISSUE TITLE
macOS cannot verify that this app is free from malware.

### ISSUE THREAD

**Issue by cjsvaxlp** [dail8859/NotepadNext#630]
### Operating System and Version

mac os m3 pro

### Distribution

dmg

### Description

![image](https://github.com/user-attachments/assets/a338e7ad-5c20-430d-a1db-0747ec687508)

### Steps to Reproduce

1. macOS cannot verify that this app is free from malware.
2. macOS cannot verify that this app is free from malware.
3. macOS cannot verify that this app is free from malware.

### Additional Details

e.g. screenshots, logs, etc

**Comment by ZachBacon** [comment]
Well looks like from my perspective that one, you tried to open it from the DMG, don't. Move it to your applications folder, second. You'll have to allow it in gate keeper, using the settings panel and navigate to security and privacy. There should be setting to allow it.

**Comment by dail8859** [comment]
You can see more specifics here: https://github.com/dail8859/NotepadNext/issues/515#issuecomment-2270759163

What it comes down to is Apple wants money to "trust" a developer. Not saying I never will do this but the time/effort is not worth it to maintain this given the number of users currently.
