### ISSUE TITLE
Startup crash on Ubuntu Snap

### ISSUE THREAD

**Issue by dogbear** [dail8859/NotepadNext#633]
### Operating System and Version

Ubuntu 24.04 LTS

### Distribution

SNAP

### Description

HI.
Installed Notepadnext via the Ubuntu App Center and started it up from there but nothing happened.
Then from command prompt, ran it and got this output:
[     0.001] I: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[     0.057] I: =============================
[     0.057] I: Notepad Next v0.7 (Snap)
[     0.057] I: Build Date/Time: Apr 11 2024 09:47:38
[     0.057] I: Qt: 5.15.3
[     0.057] I: OS: Ubuntu 24.04 LTS
[     0.057] I: Locale: en_US
[     0.057] I: CPU: x86_64
[     0.057] I: File Path: /snap/notepadnext/13/usr/bin/NotepadNext
[     0.057] I: Arguments: /snap/notepadnext/13/usr/bin/NotepadNext
[     0.057] I: =============================
[     0.057] I: bool NotepadNextApplication::init()
[     0.068] I: void TranslationManager::loadTranslation(QLocale)
[     0.068] I: LuaState::LuaState()
[     0.082] I: MacroManager::MacroManager(QObject*)
[     0.082] I: void MacroManager::loadSettings()
[     0.082] I: MainWindow::MainWindow(NotepadNextApplication*)
[     0.143] I: setupUi Completed
[     0.187] I: FileListDock::FileListDock(MainWindow*)
[     0.188] I: void MainWindow::setupLanguageMenu()
[     0.206] I: void MainWindow::restoreSettings()
[     0.206] I: void NotepadNextApplication::openFiles(const QStringList&)
[     0.206] I: void MainWindow::newFile()
[     0.206] I: void EditorManager::setupEditor(ScintillaNext*)
[     0.210] I: void MainWindow::addEditor(ScintillaNext*)
[     0.210] I: void MainWindow::detectLanguage(ScintillaNext*)
[     0.210] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
[     0.210] I: Language Name: Text
[     0.210] I: void DockedEditor::addEditor(ScintillaNext*)
realloc(): invalid pointer
Aborted (core dumped)

Any possible fixes?

### Steps to Reproduce

1. Install NotepadNext
2. Run NotepadNext
3. Be disappointed with NotepadNext

### Additional Details

I'm running this on a Lenovo Ideapad laptop with an AMD chip.

I had uninstalled NotepadNext to try installing it via flatpak but got this message:
> sudo flatpak install flathub com.github.dail8859.NotepadNext
Looking for matches…
error: No remote refs found for ‘flathub’

Then I tried installing the snap version again, but this time via command line and got this:
> sudo snap install notepadnext
error: This revision of snap "notepadnext" was published using classic
       confinement and thus may perform arbitrary system changes outside of the
       security sandbox that snaps are usually confined to, which may put your
       system at risk.

       If you understand and want to proceed repeat the command including
       --classic.

I didn't like the sound of that so I went back to the App Center and installed NotepadNext again (which is of course the classic confinement version anyway) and same problem.

Fun!

**Comment by dail8859** [comment]
The snap package is not officially supported by this library. @popey may be able to help

> [ 0.057] I: Notepad Next v0.7 (Snap)

v0.8 is the latest version so not sure why v0.7 is installed.

> I had uninstalled NotepadNext to try installing it via flatpak

That appears to be the right command so flatpak doesn't seem to be set up correctly somehow. I don't use Linux at all so maybe someone else can offer some help.

**Comment by dail8859** [comment]
I will close this for now since snap is not officially supported.

You might try opening this issue over at the notepadnext-snap package project: https://github.com/popey/notepadnext-snap
