### ISSUE TITLE
Add option to turn ON/OFF faded Horizontal Lines in the editing area

### ISSUE THREAD

**Issue by umar-afzaal** [dail8859/NotepadNext#634]
### Description

Since, underline implementation is half-baked at the moment. The lines scale inconsistently/disappear when decreasing/increasing the font size or changing the font type.

### Describe the solution you'd like

Requires an option to turn the underlines OFF completely.

**Comment by dail8859** [comment]
> Since, underline implementation is half-baked at the moment.

You mean underlining URLs? If it is "half-baked" why not describe the issue rather than just wanting to turn it off.

**Comment by umar-afzaal** [comment]
> > Since, underline implementation is half-baked at the moment.
> 
> You mean underlining URLs? If it is "half-baked" why not describe the issue rather than just wanting to turn it off.

Its those faded horizontal lines that appear on the background. I don't know what are they called in the npnext implementation.
They disappear or appear at varying width with font size or font type.

<img width="349" alt="image" src="https://github.com/user-attachments/assets/1e88db1f-9e7d-4496-9bec-3d812b140ce3">

**Comment by dail8859** [comment]
There's no way to control those. They are graphical artifacts either caused by Scintilla or Qt. The most we've determined is probably due to some sort of DPI scaling causing subpixel drawing to get incorrectly calculated.
