### ISSUE TITLE
Windows10 安装了最新版本(0.8）打开闪退

### ISSUE THREAD

**Issue by evesky** [dail8859/NotepadNext#641]
### Operating System and Version

Windows 10 21H2

### Distribution

installer

### Description

Windows10 安装了最新版本(0.8）软件打开闪退

### Steps to Reproduce

1. 
2. 
3. 

### Additional Details

e.g. screenshots, logs, etc

**Comment by dail8859** [comment]
Translation:
> Windows 10 has the latest version (0.8) installed, and the flashback is turned on
> Windows 10 has the latest version (0.8) installed and the software is turned on

I need more details as this does not tell me what problem you are having.

**Comment by Joslyn-Chen** [comment]
我遇到了差不多的问题，只要一输入不管什么都会闪退
