### ISSUE TITLE
Colors for JSON gives bad contrast on white, hard to read.

### ISSUE THREAD

**Issue by Sweeper5** [dail8859/NotepadNext#648]
### Operating System and Version

Linux

### Distribution

Arch Linux

### Description

Color choices for JSON is horrible to use, bright yellow on white for typed / added text is really hard to see.
A good fix for this would be to let us easily set the color for it ourselves, if we are at some point to use dark mode, I am certain that will be appreciated by those as well, as they may encounter similar issues with dark colors on dark backgrounds.

### Steps to Reproduce

1. Open a file already in JSON format
2.Type into said text file with a white background 
3. Notice that it is hard to see the text you are typing

### Additional Details

e.g. screenshots, logs, et

**Comment by dail8859** [comment]
Agreed there are some colors that can be adjusted to make it more readable. Can you post a small snippet of JSON code so I can make sure I'm addressing the exact issue you are seeing?

**Comment by CBx86** [comment]
Hey guys, where/how i set darkmode? My eyes are bleeding. (LOL!)

Many Thanks!!
