### ISSUE TITLE
Backward direction Find doesn't work in MacOS.

### ISSUE THREAD

**Issue by Kevin-yj** [dail8859/NotepadNext#655]
### Operating System and Version

macOS sonoma 14.6.1

### Distribution

dmg

### Description

Backward direction find doesn't work.

### Steps to Reproduce

1. open Find box
2. check the Backward direction option
3. click Find button
4. the Backward direction option has no effect

### Additional Details

e.g. screenshots, logs, etc

**Comment by dail8859** [comment]
This has been fixed in https://github.com/dail8859/NotepadNext/pull/635 and will be available in the next release.
