### ISSUE TITLE
After installation, opening a project with subfolders and many files inside will crash directly Opening it again still crashes

### ISSUE THREAD

**Issue by hotday1987** [dail8859/NotepadNext#657]
### Operating System and Version

win11

### Distribution

installer

### Description

After installation, opening a project with subfolders and many files inside will crash directly Opening it again still crashes

### Steps to Reproduce

1. install
2. it will crashed when running

### Additional Details

![bbbbbbbbbb](https://github.com/user-attachments/assets/54ba2081-21fa-4cfd-82a5-b7c75bd79db2)

**Comment by dail8859** [comment]
These are not sufficient steps to reproduce it.

> Opening a project with subfolders and many files inside will crash directly

I'm assuming you mean the "Folder as Workspace"? How many subfolders? How many files? Are the files in the root of the folder? Or nested deeper? Have you tried smaller folders?
