### ISSUE TITLE
Program Won't Start

### ISSUE THREAD

**Issue by influential-eliot** [dail8859/NotepadNext#660]
### Operating System and Version

Debian 12 Wayland

### Distribution

flathub

### Description

When I tap the icon nothing happens.
Sometimes if I move the cursor over the taskbar it says it's doing something ... but nothing appears.

### Steps to Reproduce

1. Tap icon
2. Nothing opens

### Additional Details

Apologies, but it's hard to screenshot nothing happening.

Is there anything I can do ... is there maybe a safe-mode or something?

**Comment by dail8859** [comment]
I'm not too familiar on the Linux side of things but you may try running the flatpak from command line. 

> flatpak run com.github.dail8859.NotepadNext

Normally it does spit out a good bit of logging, if you get any output from that may point to the issue, or paste it here and I'll see if there's anything obvious.

**Comment by influential-eliot** [comment]
Cheers, @dail8859 ... I'm not sure I'd look for any logging when it's at home ... but I'll see if there's a logs folder or something in my home folder.
 
I'm new-ish to Linux myself, but I'm loving the stability so far, and (_thus far_) my operating system not deciding for me what it is that I want. 😅 
 
It's *definitely* better for work, though ... so much less 'bumf' around and abouts the place.

**Comment by dail8859** [comment]
The application uses the standard output to log it to the console, so I'm assuming the flatpak will work the same way. Doesn't save it to file or anything.

**Comment by influential-eliot** [comment]
Oh ... OK ... in which case I really don't know what that all is, then ... sorry! :sweat_smile: 

I assume that it's not just going to magically appear in the console if I have it open ... is there a command to get these logs?

**Comment by dail8859** [comment]
> I assume that it's not just going to magically appear in the console

The normal exe will log it to the console. I'm assuming the flatpak is the same but I'm not sure since I don't use linux.

**Comment by influential-eliot** [comment]
Oh! My mistake entirely. Apologies! :slightly_smiling_face: 

I only followed the link to this support forum from the '_Software_' app in Debian.

Who should I report this issue to if this was not the place that made the linux flatpak?

**Comment by dail8859** [comment]
The flatpak is still "part" of this project. I personally don't use Linux nor can I really provide any Linux specific support, but there have been plenty of things that I can fix if I can determine it is an application issue (e.g. from the logs) rather than a flatpak/Linux/Wayland issue.

If there's something specific to flatpak you can open an issue here: https://github.com/flathub/com.github.dail8859.NotepadNext/issues

**Comment by influential-eliot** [comment]
Ah, OK, thanks, @dail8859 ... that's good to know.

I just found the menu editor, and copied the string for the link to NotepadNext and pasted it into a console window. It gave the below ... do you think that's one for the flatpak link above, or for here?

Is it the 'BOM' thing that's the issue? If so, I say reform 2NE1!!!!
```[     0.078] W: Could not find color scheme  ""
[     0.097] I: =============================
[     0.097] I: Notepad Next v0.8 (Flatpak)
[     0.097] I: Build Date/Time: Jun 25 2024 13:43:02
[     0.097] I: Qt: 6.5.3
[     0.097] I: OS: KDE Flatpak runtime
[     0.097] I: Locale: en_GB
[     0.097] I: CPU: x86_64
[     0.097] I: File Path: /app/bin/NotepadNext
[     0.097] I: Arguments: NotepadNext %f
[     0.097] I: =============================
[     0.097] I: bool NotepadNextApplication::init()
[     0.121] I: void TranslationManager::loadTranslation(QLocale)
[     0.121] I: LuaState::LuaState()
[     0.134] I: MacroManager::MacroManager(QObject*)
[     0.134] I: void MacroManager::loadSettings()
[     0.134] I: MainWindow::MainWindow(NotepadNextApplication*)
[     0.184] I: setupUi Completed
[     0.216] I: FileListDock::FileListDock(MainWindow*)
[     0.216] I: void MainWindow::setupLanguageMenu()
[     0.232] I: void MainWindow::restoreSettings()
[     0.232] I: Restoring previous session
[     0.232] I: void SessionManager::loadSession(MainWindow*)
[     0.232] I: ScintillaNext* SessionManager::loadUnsavedFileDetails(QSettings&)
[     0.232] D: Session file: "/home/OBFUSCATED_USER_NAME/Downloads/RuddyProjectSiteCreator_20240215171032/Microsoft.Flow/flows/acac1ab3-58b5-4352-9dd5-d36e27b8e71d/definition.json"
[     0.232] D:   temp loc: "/home/OBFUSCATED_USER_NAME/.var/app/com.github.dail8859.NotepadNext/data/NotepadNext/NotepadNext/session/46062e06-104d-442d-97c6-c9de73b40759"
[     0.232] D: Read 239461 bytes
[     0.232] D: BOM mark not found, using uchardet
[     0.232] D: uchardet detected encoding as: 'ASCII'
[     0.232] D: Using codec: 'US-ASCII'
[     0.233] I: 46062e06-104d-442d-97c6-c9de73b40759 last modified Fri Nov 15 23:50:25 2024
[     0.233] I: definition.json last modified Thu Feb 15 17:10:32 2024
[     0.233] I: void EditorManager::setupEditor(ScintillaNext*)
[     0.236] D: EditorConfig settings for: "/home/OBFUSCATED_USER_NAME/Downloads/RuddyProjectSiteCreator_20240215171032/Microsoft.Flow/flows/acac1ab3-58b5-4352-9dd5-d36e27b8e71d/definition.json"
[     0.236] I: void MainWindow::addEditor(ScintillaNext*)
[     0.236] I: void MainWindow::detectLanguage(ScintillaNext*)
[     0.236] I: QString NotepadNextApplication::detectLanguage(ScintillaNext*) const
[     0.236] I: QString NotepadNextApplication::detectLanguageFromExtension(const QString&) const
[     0.236] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
[     0.236] I: Language Name: JSON
[     0.236] I: void DockedEditor::addEditor(ScintillaNext*)
[     0.240] I: ScintillaNext* SessionManager::loadUnsavedFileDetails(QSettings&)
[     0.240] D: Session file: "/home/OBFUSCATED_USER_NAME/Downloads/NewSiteScript-ProjectTemplate_20240301055401/Microsoft.Flow/flows/380ee093-270e-44f1-97f2-5c44a176b82c/definition.json"
[     0.240] D:   temp loc: "/home/OBFUSCATED_USER_NAME/.var/app/com.github.dail8859.NotepadNext/data/NotepadNext/NotepadNext/session/b5d1d902-5c16-4686-a607-8002c025714b"
[     0.240] D: Read 74794 bytes
[     0.240] D: BOM mark not found, using uchardet
[     0.240] D: uchardet detected encoding as: 'ASCII'
[     0.240] D: Using codec: 'US-ASCII'
[     0.240] I: b5d1d902-5c16-4686-a607-8002c025714b last modified Fri Nov 15 23:50:25 2024
[     0.240] I: definition.json last modified Fri Mar 1 05:54:00 2024```

**Comment by influential-eliot** [comment]
Cheers!

I gave it a go with `--reset-settings`, and it loaded up OK. Albeit, obviously, without the files in there that were there previously.

I will add that as an option in the right-click menu for the app. :+1: 

I will close this as we found a Work Around, if not a Fix. :)

Thanks!

**Comment by dail8859** [comment]
Glad it is working now! I'm assuming something got messed up in the config file but cannot say for sure. If you do run into this problem again I'd be interested to see what is inside the `NotepadNext.ini` to see if I could prevent it from crashing...though I'm not even sure where on Linux that would be stored :)

**Comment by influential-eliot** [comment]
This happened again, FWIW, and it just **will not** start ... it's taking a LOT of memory, too! 😅 

<img width="1091" height="529" alt="Image" src="https://github.com/user-attachments/assets/4a848647-514b-4f56-99ba-e7b87856039e" />

It started, again, after the `--reset-settings` took ahold ... but I have no way to get useful information on this, nor can I find my previous session information or preferences, so I cannot edit them into this session. 😩

**Comment by dail8859** [comment]
Hmmm well thats not good.

If you did use that flag there should (hopefully) be a backup.ini file in the same folder as the NotepadNext.ini.

I did a good bit of testing to see if a corrupt ini file could lead to crashes etc but didn't have any luck yet. If you do have that backup.ini file in there it would be good to try to troubleshoot this.

**Comment by influential-eliot** [comment]
Cheers, mate ... as before, not expecting anything from yer, here ... just thought you'd like to know ... I'll try to find that!
