### ISSUE TITLE
When I save a new file, if I have already entered the extension (known), when I save it to a specific file, the extension should not be added to me

### ISSUE THREAD

**Issue by qiuliaogit** [dail8859/NotepadNext#672]
### Description

新建文件保存的时候，如果我已经输入了扩展名（已知的, 例如a.sql），保存到具体文件的时候，不应该再给我增加扩展名。

### Describe the solution you'd like

例如：我保存的时候输入了   a.sql, 实际的文件是a.sql.txt, 我希望对于已知场景的扩展名， 可以自动识别

**Comment by dail8859** [comment]
Please provide your Operating system and version, application version, and an **exact** set of steps to reproduce this issue.

**Comment by qiuliaogit** [comment]
> Please provide your Operating system and version, application version, and an **exact** set of steps to reproduce this issue.

macos

**Comment by dail8859** [comment]
Please provide your Operating system and version, application version, and an **exact** set of steps to reproduce this issue.
