### ISSUE TITLE
🪲 "Temporary Files" Lost when quitting and re-opening Notepadnext with a text file

### ISSUE THREAD

**Issue by ADTC** [dail8859/NotepadNext#674]
### Operating System and Version

macOS Sonoma 14.7.1 (23H222)

### Distribution

brew (Homebrew)

### Description

As it says on the title.

### Steps to Reproduce

1. Enable "Restore previous session" and ~"Unsaved changes"~ "Temporary Files"
2. Make a new tab, put some text in it, and quit Notepadnext. (If you open Notepadnext again, it will restore the temporary file. Quit again.)
3. Open a file in Notepadnext while it's not running. You can do in Terminal: `open -a Notepadnext /path/to/a/text/file`.

**Result:** ONLY the given permanent file is opened. The tab with temporary file is not restored. If I close the text file or quit again, then open again, the temporary file cannot be restored, so we can conclude it is permanently lost.

**Expectation:** Restore previous session including temporary files, then open the given permanent file in a new tab in addition to previous session. (If the previous session already contains the permanent file in a tab, then switch to it.)

### Additional Details

It looks like this bug only happens when there are ONLY "temporary files" in the previous session. If the previous session contains permanent files open as tabs, then the previous session (including temporary files) is restored correctly in addition to opening the given text file.

**Comment by dail8859** [comment]
> Enable "Restore previous session" and "Unsaved changes"

I'm assuming you mean "Temporary Files" instead of "Unsaved changes"?

If so I've been able to replicate the issue and will see about fixing it.

**Comment by ADTC** [comment]
> I'm assuming you mean "Temporary Files" instead of "Unsaved changes"?

Hmm.... yeah I think so. I just changed the title.

**Comment by ADTC** [comment]
I have also updated the issue description. Thank you for fixing this.

**Comment by dail8859** [comment]
Appreciate the detailed info. Makes it much easier to debug things :)

Apologies for any data loss but now that this is fixed it will help make sure other user's don't encounter it!

**Comment by ADTC** [comment]
It's okay, I was only testing the ability to save the temporary files. There was no important data. Anyway you have warned that saving session is experimental and bugs like this are expected. Thank you for fixing this one.
