### ISSUE TITLE
invalid pointer, snap package Ubuntu

### ISSUE THREAD

**Issue by chtomek** [dail8859/NotepadNext#688]
### Operating System and Version

Ubuntu 24.04.1 LTS

### Distribution

snap

### Description

[     0.000] I: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[     0.037] I: =============================
[     0.037] I: Notepad Next v0.8 (Snap)
[     0.037] I: Build Date/Time: Oct  2 2024 19:22:26
[     0.037] I: Qt: 5.15.3
[     0.037] I: OS: Ubuntu 24.04.1 LTS
[     0.037] I: Locale: en_US
[     0.037] I: CPU: x86_64
[     0.037] I: File Path: /snap/notepadnext/28/usr/bin/NotepadNext
[     0.037] I: Arguments: /snap/notepadnext/28/usr/bin/NotepadNext
[     0.037] I: =============================
[     0.037] I: bool NotepadNextApplication::init()
[     0.043] I: void TranslationManager::loadTranslation(QLocale)
[     0.043] I: LuaState::LuaState()
[     0.048] I: MacroManager::MacroManager(QObject*)
[     0.048] I: void MacroManager::loadSettings()
[     0.048] I: MainWindow::MainWindow(NotepadNextApplication*)
[     0.076] I: setupUi Completed
[     0.107] I: FileListDock::FileListDock(MainWindow*)
[     0.108] I: void MainWindow::setupLanguageMenu()
[     0.108] I: void MainWindow::applyStyleSheet()
[     0.108] I: Loading stylesheet:  ":/stylesheets/npp.css"
[     0.115] I: void MainWindow::restoreSettings()
[     0.115] I: void NotepadNextApplication::openFiles(const QStringList&)
[     0.115] I: void MainWindow::newFile()
[     0.116] I: void EditorManager::setupEditor(ScintillaNext*)
[     0.117] I: void MainWindow::addEditor(ScintillaNext*)
[     0.117] I: void MainWindow::detectLanguage(ScintillaNext*)
[     0.117] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
[     0.117] I: Language Name: Text
[     0.117] I: void DockedEditor::addEditor(ScintillaNext*)
realloc(): invalid pointer
Aborted (core dumped)

### Steps to Reproduce

1. 
2. 
3. 

### Additional Details

e.g. screenshots, logs, etc

**Comment by dail8859** [comment]
The snap package is not officially supported so I can't really offer any help. v0.9 has been released so not sure if this is available yet via snap.

@popey might have some suggestions or you might try opening this issue over at the notepadnext-snap package project: https://github.com/popey/notepadnext-snap

**Comment by chtomek** [comment]
@dail8859 thanks, wasn't aware the snap project exists in github. Will move it over there there.

**Comment by chtomek** [comment]
The AppImage runs successfuly on the system mentioned earlier.
