### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by mcandre** [dail8859/NotepadNext#76]
plz

**Comment by dail8859** [comment]
I'd be very interested if someone could contribute and test building this on macOS. I'm definitely _not_ a mac person myself so I won't be able to help directly in anyway.

**Comment by cschlosser** [comment]
I'm working on this: https://github.com/cschlosser/NotepadNext/pull/1

**Comment by dail8859** [comment]
@cschlosser

Awesome!
