### ISSUE TITLE
AppImage is built on a too-new system

### ISSUE THREAD

**Issue by pgarciaq** [dail8859/NotepadNext#77]
Running the AppImage on RHEL8 fails because the AppImage is built on a system with glibc 2.29, while RHEL8 contains glibc 2.28:

$ ./NotepadNext-x86_64.AppImage 
/tmp/.mount_NotepajreKDD/AppRun.wrapped: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_NotepajreKDD/AppRun.wrapped)

$ rpm -qi glibc
Name        : glibc
Version     : 2.28
Release     : 164.el8_5.3
Architecture: x86_64

Please rebuild on an older Linux.

**Comment by dail8859** [comment]
Thanks for opening this issue.

I made a quick attempt in #78 to see if just using an older Ubuntu version would work but no immediate luck.

I'd like to move to Qt 6.2 at some point in the near future. I'll have to invest further if there is some way to support Qt 6.2 with glibc 2.28

**Comment by dail8859** [comment]
[Qt6.2 is linked against glibc 2.28](https://doc.qt.io/qt-6/supported-platforms.html#availability-of-packages)

> Note: Linux binary packages are linked against glibc 2.28. If you are using a glibc version older than that you need to build Qt from sources or upgrade glibc to 2.28 or newer.

And it looks like Ubuntu 18.04 uses glibc 2.27

Since Qt5 and Qt6 are currently supported for the time being, I might have to try building Qt5 on an older version of Linux and Qt6 on a newer version.

**Comment by dail8859** [comment]
@pgarciaq 

Try downloading the Qt5 AppImage from this run (you'll probably have to unzip it first): https://github.com/dail8859/NotepadNext/actions/runs/2141001190

It is built with Ubuntu 18.04 and should be compatible

**Comment by lxtwin** [comment]
QT5 works on RHEL 8.4, QT6 does not.

QT5_NotepadNext-x86_64.AppImage
[     0.037] I: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[     0.204] I: =============================
[     0.204] I: NotepadNext v
[     0.204] I: Qt: 5.15.2
[     0.204] I: OS: Red Hat Enterprise Linux 8.4 (Ootpa)
[     0.204] I: CPU: x86_64
[     0.204] I: File Path: /tmp/.mount_QT5_NoVU3CRq/usr/bin/NotepadNext
[     0.204] I: Arguments: /tmp/.mount_QT5_NoVU3CRq/AppRun.wrapped
[     0.204] I: =============================
[     0.204] I: bool NotepadNextApplication::init()
[     0.204] I: LuaState::LuaState()
[     0.227] I: MainWindow::MainWindow(NotepadNextApplication*)
[     0.274] I: setupUi Completed
[     0.391] I: AutoUpdates: 0
[     0.391] I: void MainWindow::setupLanguageMenu()
[     0.397] I: void MainWindow::restoreSettings()
[     0.397] I: void NotepadNextApplication::applyArguments(const QStringList&)
[     0.397] I: void MainWindow::newFile()
[     0.397] I: void EditorManager::setupEditor(ScintillaNext*)
[     0.398] I: void MainWindow::addEditor(ScintillaNext*)
[     0.398] I: void MainWindow::detectLanguage(ScintillaNext*)
[     0.398] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
[     0.398] I: Language Name: Text
[     0.399] I: void DockedEditor::addEditor(ScintillaNext*)
[     0.439] I: void MainWindow::activateEditor(ScintillaNext*)
[     0.439] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[     0.439] I: void MainWindow::updateGui(ScintillaNext*)
[     0.439] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
[     0.439] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[     0.439] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
[     0.439] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)
[     0.536] I: void MainWindow::focusIn()
[     0.536] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[    18.200] I: void MainWindow::saveSettings() const




QT6_NotepadNext-x86_64.AppImage 
/tmp/.mount_QT6_Nokk1oqg/AppRun.wrapped: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_QT6_Nokk1oqg/AppRun.wrapped)
/tmp/.mount_QT6_Nokk1oqg/AppRun.wrapped: /lib64/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_QT6_Nokk1oqg/usr/bin/../lib/libsystemd.so.0)

**Comment by dail8859** [comment]
@lxtwin 

> QT5 works on RHEL 8.4, QT6 does not.

Thanks for testing. The plan is to just use Qt5 for the time being and at some point move to Qt6. I would guess #84 will help solve alot of these types of issues and make things more compatible.
