### ISSUE TITLE
loading files

### ISSUE THREAD

**Issue by TeLLie** [dail8859/NotepadNext#82]
Hi
When i try to load a file out of the recent files list they never get opened
Any ide how to fix?

Also i like to see a future to get split window, to comppare f.e 2 same files at the same time. 

Greetings Elbert

**Comment by dail8859** [comment]
Thanks for opening the issue.

If you could provide a few details that would be helpful for trouble shooting.

- What OS are you using?
- Your Notepad Next version?
- I'm assuming you ensured the files do exist?
- Are they on a network or external drive?
- Does it do it for all files or just some files?
- If you run Notepad Next from command line is there any debugging output?

**Comment by TeLLie** [comment]
Hi
Using OS/2
Using V0,49
Yes the files are there
No there on the HD
Yes all file types
Strange part is that if i choose all  it opens all recent files.
I see this in log when i open 1 recent file....


[     0.046] I: =============================
[     0.046] I: NotepadNext v
[     0.046] I: Qt: 5.15.2
[     0.046] I: OS: unknown
[     0.046] I: CPU: i386
[     0.046] I: File Path: F:/NotepadNext/NotepadNext/src/515-os2/NotepadNext/NotepadNext.exe
[     0.046] I: Arguments: F:\NotepadNext\NotepadNext\src\515-os2\NotepadNext\NotepadNext.exe
[     0.048] I: =============================
[     0.048] I: bool NotepadNextApplication::init()
[     0.048] I: LuaState::LuaState()
[     0.048] W: [string "table.remove(package.searchers, 4); table.rem..."]:1: bad argument #1 to 'remove' (position out of bounds)
[     0.066] I: MainWindow::MainWindow(NotepadNextApplication*)
[     0.150] I: setupUi Completed
[     0.191] I: AutoUpdates: 0
[     0.193] I: void MainWindow::setupLanguageMenu()
[     0.203] I: void MainWindow::restoreSettings()
[     0.210] I: void NotepadNextApplication::applyArguments(const QStringList&)
[     0.210] I: void MainWindow::newFile()
[     0.210] I: void EditorManager::setupEditor(ScintillaNext*)
[     0.216] I: void MainWindow::addEditor(ScintillaNext*)
[     0.218] I: void MainWindow::detectLanguage(ScintillaNext*)
[     0.218] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
[     0.218] I: Language Name: Text
[     0.218] I: void DockedEditor::addEditor(ScintillaNext*)
[     0.232] I: void MainWindow::activateEditor(ScintillaNext*)
[     0.232] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[     0.232] I: void MainWindow::updateGui(ScintillaNext*)
[     0.244] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
[     0.244] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[     0.244] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
[     0.244] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)
[     0.246] I: void MainWindow::focusIn()
[     0.246] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[    19.127] I: void MainWindow::saveSettings() const

**Comment by dail8859** [comment]
Is this the AppImage from the releases page or did you build this yourself?

**Comment by TeLLie** [comment]
HI
I build myself

**Comment by dail8859** [comment]
Glancing through the output quickly...

> [ 0.046] I: NotepadNext v

That looks odd. It should be showing a version number at least...oh well not a big deal.

> [ 0.048] W: [string "table.remove(package.searchers, 4); table.rem..."]:1: bad argument https://github.com/dail8859/NotepadNext/issues/1 to 'remove' (position out of bounds)

Guess OS/2 has different file paths for Lua's package searching. I'll have to check to see if this shows up for other Linux distros since I don't see it on Windows. Shouldn't be causing your issue...but not 100% for sure.

---

If it is attempting to open a file it should at least show something similar to this:

> [     x.xxx] I: void __cdecl MainWindow::openFileList(const class QStringList &)

Can you post a picture of your recent file list menu?

![Untitled](https://user-images.githubusercontent.com/3694843/162652648-5c55679d-84d8-4ed6-b8ca-ca3763cf4563.png)


How are you triggering it? With the 'Ctrl+Shift+T' shortcut? Or clicking the file name in the menu? etc

**Comment by TeLLie** [comment]
Hi

Op ma 11 apr. 2022 04:00 schreef dail8859 ***@***.***>:

> Glancing through the output quickly...
>
> [ 0.046] I: NotepadNext v
>
> That looks odd. It should be showing a version number at least...oh well
> not a big deal.
>
> [ 0.048] W: [string "table.remove(package.searchers, 4); table.rem..."]:1:
> bad argument #1 <https://github.com/dail8859/NotepadNext/issues/1> to
> 'remove' (position out of bounds)
>
> Guess OS/2 has different file paths for Lua's package searching. I'll have
> to check to see if this shows up for other Linux distros since I don't see
> it on Windows. Shouldn't be causing your issue...but not 100% for sure.
> ------------------------------
>
> If it is attempting to open a file it should at least show something
> similar to this:
>
> [ x.xxx] I: void __cdecl MainWindow::openFileList(const class QStringList
> &)
>
> Can you post a picture of your recent file list menu?
>
> [image: Untitled]
> <https://user-images.githubusercontent.com/3694843/162652648-5c55679d-84d8-4ed6-b8ca-ca3763cf4563.png>
>
> How are you triggering it? With the 'Ctrl+Shift+T' shortcut? Or clicking
> the file name in the menu? etc
>
> I do it normally with mouse, but that seems not to work.
If i do shortcut i opens the first file.
When using keyboard i can open all files.
So i blame the mouse...
Tekst uit oorspronkelijke berichten tonen

**Comment by dail8859** [comment]
I checked Ubuntu 21.10 and everything seems to work as expected.

Since you are able to build this for OS/2 hopefully I can point you in a direction and maybe if you add some extra debug output might help.

The recent file list menu is dynamically generated as needed, and the `triggered` slot is connected here:

https://github.com/dail8859/NotepadNext/blob/a87990164315a9eef2b7a066df44ec9b298082da/src/NotepadNext/RecentFilesListManager.cpp#L79-L95

And should trigger this function:

https://github.com/dail8859/NotepadNext/blob/a87990164315a9eef2b7a066df44ec9b298082da/src/NotepadNext/RecentFilesListManager.cpp#L97-L101

**Comment by TeLLie** [comment]
Hi
I have no knowledge about debugging.
As os/2 have no decent debugging tools.
So im no help in here 😭


Op di 12 apr. 2022 03:52 schreef dail8859 ***@***.***>:

**Comment by dail8859** [comment]
> As os/2 have no decent debugging tools.

That's why I suggested adding additional debug output that way it will show up in the log and at least narrow down the issue. No need for a true debugger.

**Comment by TeLLie** [comment]
Hi,
Then you have to know how :)
As i told before my knowlegde is zero about debugging...
Sorry but i really dont know what to do..

**Comment by dail8859** [comment]
I added an extra debugging line. If the mouse click does actually trigger the menu you'll see:

```
[    xx.xxx] I: void __cdecl RecentFilesListManager::recentFileActionTriggered(void)
```

If not then for some reason the dynamic list of actions isn't getting set up correctly for some reason. That's about all the help I can provide for OS/2.

**Comment by TeLLie** [comment]
Hi
Thankz for helping me out
I see this in log....

NotepadNext.exe]

[     0.066] I: =============================
[     0.066] I: NotepadNext v
[     0.066] I: Build Date/Time: Apr 17 2022 17:16:43
[     0.066] I: Qt: 5.15.2
[     0.066] I: OS: unknown
[     0.066] I: CPU: i386
[     0.066] I: File Path:
F:/NotepadNext/src/515-os2/NotepadNext/NotepadNext.exe
[     0.066] I: Arguments:
F:\NotepadNext\src\515-os2\NotepadNext\NotepadNext.exe
[     0.068] I: =============================
[     0.068] I: bool NotepadNextApplication::init()
[     0.068] I: LuaState::LuaState()
[     0.070] W: [string "table.remove(package.searchers, 4);
table.rem..."]:1: bad argument #1 to 'remove' (position out of bounds)
[     0.086] I: MainWindow::MainWindow(NotepadNextApplication*)
[     0.182] I: setupUi Completed
[     0.242] I: AutoUpdates: 0
[     0.242] I: void MainWindow::setupLanguageMenu()
[     0.252] I: void MainWindow::restoreSettings()
[     0.266] I: void NotepadNextApplication::applyArguments(const QStringList&)
[     0.266] I: void MainWindow::newFile()
[     0.266] I: void EditorManager::setupEditor(ScintillaNext*)
[     0.271] I: void MainWindow::addEditor(ScintillaNext*)
[     0.271] I: void MainWindow::detectLanguage(ScintillaNext*)
[     0.271] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
[     0.271] I: Language Name: Text
[     0.271] I: void DockedEditor::addEditor(ScintillaNext*)
[     0.289] I: void MainWindow::activateEditor(ScintillaNext*)
[     0.289] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[     0.289] I: void MainWindow::updateGui(ScintillaNext*)
[     0.289] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
[     0.289] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[     0.289] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
[     0.289] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)
[     0.291] I: void MainWindow::focusIn()
[     0.291] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[    29.258] I: void RecentFilesListManager::recentFileActionTriggered()
[    29.258] I: void MainWindow::openFileList(const QStringList&)
[    29.258] I: D:\specfiles\jasper.spec
[    29.260] D: Read 4311 bytes
[    29.260] I: Encoding detected as: ASCII
[    29.260] I: jasper.spec last modified Fri Apr 8 16:58:54 2022
[    29.260] I: void EditorManager::setupEditor(ScintillaNext*)
[    29.292] D: EditorConfig settings for: "D:\\specfiles\\jasper.spec"
[    29.292] I: void MainWindow::addEditor(ScintillaNext*)
[    29.292] I: void MainWindow::detectLanguage(ScintillaNext*)
[    29.292] I: QString
NotepadNextApplication::detectLanguageFromExtension(const QString&)
const
[    29.292] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
[    29.292] I: Language Name: Text
[    29.292] I: void DockedEditor::addEditor(ScintillaNext*)
[    29.294] I: void MainWindow::activateEditor(ScintillaNext*)
[    29.294] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[    29.294] I: jasper.spec last modified Fri Apr 8 16:58:54 2022
[    29.294] I: void MainWindow::updateGui(ScintillaNext*)
[    29.294] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
[    29.296] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[    29.296] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
[    29.296] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)
[    34.180] I: void RecentFilesListManager::addFile(const QString&)
[    34.182] I: void MainWindow::saveSettings() const



Itry with mouse but that show Notting.

Just keyboard works.


But that's ok for me ..







Op vr 15 apr. 2022 15:53 schreef dail8859 ***@***.***>:
