### ISSUE TITLE
About needs to be the last entry in the Help menu

### ISSUE THREAD

**Issue by tmssngr** [dail8859/NotepadNext#86]
by an unwritten law.

**Comment by dail8859** [comment]
Agreed, the Help menu grew a bit over time and needs reorganized.

**Comment by mandyedi** [comment]
As a warm-up, I'd like to resolve this issue. How about this order:
Lua Console
Language Inspector
Editor Inspector
Check for Updates...
About Qt
About Notepad Next

**Comment by dail8859** [comment]
@mandyedi 

> How about this order

That sounds reasonable.
