### ISSUE TITLE
Settings | Preferences: shows the wrong page by default

### ISSUE THREAD

**Issue by tmssngr** [dail8859/NotepadNext#87]
After restarting Notepad Next on Windows, and opening the Preferences, in the left list "General" is selected, but on the right side "Caret Settings..." is shown. Clicking left onto "Editing" nothing changes, clicking on "General" again shows "Localization..." on the right side.

**Comment by dail8859** [comment]
Thanks for opening the issue.

As with the other issue you opened the Preference dialog needs alot of attention. I'll close this specific issue for now but I'll open another more generic issue about the Preference dialog in general.
