### ISSUE TITLE
Encoding menu is empty

### ISSUE THREAD

**Issue by tmssngr** [dail8859/NotepadNext#88]
ditto for the Run menu. If you don't have something to show there, don't show the menu.

**Comment by dail8859** [comment]
I first fleshed out the menus quite some time ago in hopes to keep adding functionality but some menus I just haven't gotten around to using yet or just aren't a priority. Removing the Run menu makes sense. There is #49 about file encoding. Might just remove the Encoding menu or add some conversions if I can handle the basic cases correct.

**Comment by dail8859** [comment]
Closing as a duplicate of #49
