### ISSUE TITLE
Build with Debug version: Assertion failed

### ISSUE THREAD

**Issue by inkydragon** [dail8859/NotepadNext#89]
Clone and build, then Assertion failed.

![image](https://user-images.githubusercontent.com/5158738/162677873-73dd5ac1-cd4e-4f2c-983d-e42f70161cb0.png)

If I ignore this error, the program runs normally.
Build the release version, the program also works fine.

https://github.com/dail8859/NotepadNext/blob/91c0f0aec3303489d1b7526f326ca03159929e0e/src/lexilla/lexlib/LexAccessor.h#L178

In debug mode, all three values are `0`.

## Version
- npn: dev branch - v0.4.9 release
- Qt 5.15.2 - MSVC 2019 x64
- OS: Windows 10 Version 2009 [winnt version 10.0.19044]
- cl 19.29.30137

**Comment by dail8859** [comment]
Thanks for opening this issue. This was discussed in #63 and the conclusion was the Lexilla project would need to fix this (https://github.com/ScintillaOrg/lexilla/issues/35), however that project didn't seem to concerned with the assertion error. As far as I know there's nothing Notepad Next can do differently. I'll keep this open for now to see if there can be some simple changes in the Lexilla project.

**Comment by elcuco** [comment]
You can define NDEBUG while building, this will remove that issue.  I did that on the CMake port here: https://github.com/dail8859/NotepadNext/pull/100
