### ISSUE TITLE
Add option to disable autocompletion

### ISSUE THREAD

**Issue by bgstack15** [dail8859/NotepadNext#95]
Related to #90, can we please have a configurable option to disable auto-completion? Autocomplete is already there, so turning it off should be easier than adding it if it were new!

**Comment by dail8859** [comment]
Yeah I completely agree. There is a lot of configuration that needs made accessible and #90 hopefully will do that. Not only with the autocompletion but many other parts of the application.

My hope is #90 will provide a way to make the application very customizable, but not have a mess of a preference dialog like Notepad++ has.

**Comment by dail8859** [comment]
I know this is still something that needs added but I'm closing this in favor or #90 which will address adding this option.
